In [1]:
# ==========================================================
# General Setup
# ==========================================================

import pandas as pd
import os

# üìÅ Set input/output paths
input_path = '/Users/emilsafarov/Library/CloudStorage/OneDrive-Personal/CF/A6/1_sourceing_open_data/US project/Data/Input/file_2_multidimenational'
### output_path = "/Users/emilsafarov/Library/CloudStorage/OneDrive-Personal/CF/A6/1_sourceing_open_data/US project/Data/Output data"

# üìÑ List all CSV files in the input directory
data_files = os.listdir(input_path)

# üìå Get filename for a specific year, with confirmation
def get_file_path(year):
    matches = [f for f in data_files if f.endswith(f"analytic_data{year}.csv")]
    if not matches:
        raise FileNotFoundError(f"‚ùå No file found for year {year}")
    print(f"‚úÖ Found file for {year}: {matches[0]}")
    return matches[0]

In [2]:
print(data_files)

['analytic_data2024.csv', 'analytic_data2021.csv', 'analytic_data2020.csv', 'analytic_data2022.csv', 'analytic_data2023.csv']

In [3]:
# üìå Get and print number of rows for a specific year
def get_file_path_and_rows(year):
    matches = [f for f in data_files if f.endswith(f"analytic_data{year}.csv")]
    if not matches:
        raise FileNotFoundError(f"‚ùå No file found for year {year}")
    
    file_name = matches[0]
    full_path = os.path.join(input_path, file_name)

    # Load the file
    df = pd.read_csv(full_path)

    # Print confirmation and row count
    print(f"‚úÖ {file_name} loaded | Rows: {df.shape[0]}")
    return df

# üîÅ Example: Loop through multiple years
for year in range(2020, 2025):
    get_file_path_and_rows(year)

‚úÖ analytic_data2020.csv loaded | Rows: 3195

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/2009348623.py:11: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)
/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/2009348623.py:11: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

‚úÖ analytic_data2021.csv loaded | Rows: 3195
‚úÖ analytic_data2022.csv loaded | Rows: 3195

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/2009348623.py:11: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)
/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/2009348623.py:11: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

‚úÖ analytic_data2023.csv loaded | Rows: 3195
‚úÖ analytic_data2024.csv loaded | Rows: 3196

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/2009348623.py:11: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

In [4]:
# Dictionary to store year-wise DataFrames with selected columns
df_dict = {}

# Loop and load files, keeping only identifying columns
for year in range(2020, 2025):
    matches = [f for f in data_files if f.endswith(f"analytic_data{year}.csv")]
    if not matches:
        print(f"‚ùå File for {year} not found.")
        continue
    
    file_name = matches[0]
    full_path = os.path.join(input_path, file_name)
    
    df = pd.read_csv(full_path)

    # Keep only identifying columns
    key_cols = ['5-digit FIPS Code', 'State Abbreviation', 'Name']
    df_subset = df[key_cols].drop_duplicates()
    df_subset['year'] = year

    df_dict[year] = df_subset

# Combine all years into one DataFrame
combined_keys = pd.concat(df_dict.values(), ignore_index=True)

# Check for duplicates across all years
duplicated_across_years = combined_keys.duplicated(subset=['5-digit FIPS Code', 'State Abbreviation', 'Name'], keep=False)

# Filter and display duplicates
duplicates = combined_keys[duplicated_across_years]
print(f"üîÅ Duplicated (non-unique) rows across years: {duplicates.shape[0]}")
print(duplicates.sort_values(['5-digit FIPS Code', 'year']))

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/1783119664.py:14: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)
/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/1783119664.py:14: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)
/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/1783119664.py:14: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)
/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/1783119664.py:14: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)
/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/1783119664.py:14: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

üîÅ Duplicated (non-unique) rows across years: 15973
      5-digit FIPS Code State Abbreviation            Name  year
1024              21023                 KY  Bracken County  2020
4219              21023                 KY  Bracken County  2021
7414              21023                 KY  Bracken County  2022
10609             21023                 KY  Bracken County  2023
13805             21023                 KY  Bracken County  2024
...                 ...                ...             ...   ...
0              fipscode              state          county  2020
3195           fipscode              state          county  2021
6390           fipscode              state          county  2022
9585           fipscode              state          county  2023
12780          fipscode              state          county  2024

[15973 rows x 4 columns]

In [5]:
# üìå Load, print stats, and show duplicated rows for State Abbreviation + Name
def get_file_path_and_rows(year):
    matches = [f for f in data_files if f.endswith(f"analytic_data{year}.csv")]
    if not matches:
        raise FileNotFoundError(f"‚ùå No file found for year {year}")
    
    file_name = matches[0]
    full_path = os.path.join(input_path, file_name)

    # Load the file
    df = pd.read_csv(full_path)

    # Check and collect duplicate rows
    if 'State Abbreviation' in df.columns and 'Name' in df.columns:
        duplicates = df[df.duplicated(subset=['State Abbreviation', 'Name'], keep=False)]
        num_duplicates = duplicates.shape[0]
        print(f"‚úÖ {file_name} | Rows: {df.shape[0]} | Duplicate State+Name Rows: {num_duplicates}")
        if num_duplicates > 0:
            print(duplicates[['State Abbreviation', 'Name']].drop_duplicates())
    else:
        print(f"‚ö†Ô∏è Columns missing in {file_name}")
    
    return df

# üîÅ Loop through years
for year in range(2020, 2025):
    get_file_path_and_rows(year)

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/2085498272.py:11: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

‚úÖ analytic_data2020.csv | Rows: 3195 | Duplicate State+Name Rows: 2
    State Abbreviation                  Name
329                 DC  District of Columbia

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/2085498272.py:11: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

‚úÖ analytic_data2021.csv | Rows: 3195 | Duplicate State+Name Rows: 2
    State Abbreviation                  Name
329                 DC  District of Columbia

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/2085498272.py:11: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

‚úÖ analytic_data2022.csv | Rows: 3195 | Duplicate State+Name Rows: 2
    State Abbreviation                  Name
329                 DC  District of Columbia

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/2085498272.py:11: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

‚úÖ analytic_data2023.csv | Rows: 3195 | Duplicate State+Name Rows: 2
    State Abbreviation                  Name
329                 DC  District of Columbia
‚úÖ analytic_data2024.csv | Rows: 3196 | Duplicate State+Name Rows: 2
    State Abbreviation                  Name
330                 DC  District of Columbia

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/2085498272.py:11: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

In [6]:
import pandas as pd
import os

# üìÅ Set input/output paths
input_path = '/Users/emilsafarov/Library/CloudStorage/OneDrive-Personal/CF/A6/1_sourceing_open_data/US project/Data/Input/file_2_multidimenational'


# üìÑ List all CSV files in the input directory
data_files = os.listdir(input_path)

# üìå Load and report row stats for each year
def get_file_path_and_rows(year):
    matches = [f for f in data_files if f.endswith(f"analytic_data{year}.csv")]
    if not matches:
        raise FileNotFoundError(f"‚ùå No file found for year {year}")
    
    file_name = matches[0]
    full_path = os.path.join(input_path, file_name)

    # Load the file
    df = pd.read_csv(full_path)

    # Detect FIPS column
    fips_column = '5-digit FIPS Code'
    duplicated_fips = df[fips_column].duplicated(keep=False).sum() if fips_column in df.columns else 'N/A'

    # Count rows and full duplicates
    total_rows = df.shape[0]
    duplicated_rows = df.duplicated().sum()

    # Print results
    print(f"‚úÖ {file_name} | Rows: {total_rows} | Fully duplicated rows: {duplicated_rows} | Duplicated FIPS rows: {duplicated_fips}")
    
    return df

# üîÅ Loop through years
for year in range(2020, 2025):
    get_file_path_and_rows(year)

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/493905551.py:21: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

‚úÖ analytic_data2020.csv | Rows: 3195 | Fully duplicated rows: 0 | Duplicated FIPS rows: 0

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/493905551.py:21: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

‚úÖ analytic_data2021.csv | Rows: 3195 | Fully duplicated rows: 0 | Duplicated FIPS rows: 0

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/493905551.py:21: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

‚úÖ analytic_data2022.csv | Rows: 3195 | Fully duplicated rows: 0 | Duplicated FIPS rows: 0

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/493905551.py:21: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

‚úÖ analytic_data2023.csv | Rows: 3195 | Fully duplicated rows: 0 | Duplicated FIPS rows: 0
‚úÖ analytic_data2024.csv | Rows: 3196 | Fully duplicated rows: 0 | Duplicated FIPS rows: 0

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/493905551.py:21: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(full_path)

In [7]:
# ==========================================================
# PART 1A: Load Drinking Water Data and Report Missing
# ==========================================================

def load_drinking_water_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename))
    df.columns = df.columns.str.strip()

    possible_cols = [
        "Drinking water violations raw value",
        "Drinking Water Violations raw value"
    ]
    value_col = next((col for col in possible_cols if col in df.columns), None)

    new_col = f'drinking_water_{year}'
    if value_col is None:
        print(f"‚ö†Ô∏è  Column not found in {filename}. Filling {new_col} with NA.")
        df[new_col] = pd.NA
    else:
        df = df.rename(columns={value_col: new_col})

    df = df.rename(columns={
        '5-digit FIPS Code': 'FIPS',
        'State Abbreviation': 'State',
        'Name': 'County'
    })

    return df[['FIPS', 'State', 'County', new_col]]

# üì• Load all 5 years
water_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_drinking_water_column(file_path, year)
    water_dfs.append(df)

# üß© Merge yearly data
drinking_water = water_dfs[0]
for df in water_dfs[1:]:
    drinking_water = pd.merge(drinking_water, df, on=["FIPS", "State", "County"], how="outer")

# üìä Calculate 5-year average (pre-imputation)
water_cols = [f'drinking_water_{y}' for y in range(2020, 2025)]
drinking_water[water_cols] = drinking_water[water_cols].apply(pd.to_numeric, errors='coerce')
drinking_water['drinking_water_mean'] = drinking_water[water_cols].mean(axis=1, skipna=True)

# ‚ùå Report missing values before imputation
missing_report = pd.DataFrame({
    "Missing Count": drinking_water.isna().sum(),
    "Missing %": (drinking_water.isna().sum() / len(drinking_water) * 100).round(2)
})
print("üìã Missing Value Report (Before Imputation)")
print(missing_report)

# üëÄ Preview result
drinking_water.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/1636569243.py:6: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(input_path, filename))
/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/1636569243.py:6: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(input_path, filename))

‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/1636569243.py:6: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(input_path, filename))
/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/1636569243.py:6: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(input_path, filename))

‚úÖ Found file for 2024: analytic_data2024.csv
üìã Missing Value Report (Before Imputation)
                     Missing Count  Missing %
FIPS                             0       0.00
State                            0       0.00
County                           0       0.00
drinking_water_2020             50       1.56
drinking_water_2021             50       1.56
drinking_water_2022             49       1.53
drinking_water_2023             50       1.56
drinking_water_2024             58       1.81
drinking_water_mean             47       1.47

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/1636569243.py:6: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(input_path, filename))

,FIPS,State,County,drinking_water_2020,drinking_water_2021,drinking_water_2022,drinking_water_2023,drinking_water_2024,drinking_water_mean
0,21021,KY,Boyle County,NaN,NaN,NaN,NaN,0.0,0.0
1,21023,KY,Bracken County,0.0,0.0,0.0,0.0,0.0,0.0
2,21025,KY,Breathitt County,1.0,1.0,1.0,0.0,0.0,0.6
3,21027,KY,Breckinridge County,1.0,0.0,0.0,0.0,0.0,0.2
4,21029,KY,Bullitt County,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
# ==========================================================
# PART 1B: Impute and Recalculate Drinking Water Averages
# ==========================================================

# üßº Impute missing values by state-wise mean
states = drinking_water['State'].unique()
for state in states:
    state_mean = drinking_water.loc[drinking_water['State'] == state, 'drinking_water_mean'].mean()
    for col in water_cols:
        drinking_water.loc[
            (drinking_water['State'] == state) & (drinking_water[col].isna()),
            col
        ] = state_mean

# üîÅ Recalculate mean after imputation
drinking_water[water_cols] = drinking_water[water_cols].apply(pd.to_numeric, errors='coerce')
drinking_water['drinking_water_mean'] = drinking_water[water_cols].mean(axis=1, skipna=True)

# ‚úÖ Final missing check
missing_report_final = pd.DataFrame({
    "Missing Count": drinking_water.isna().sum(),
    "Missing %": (drinking_water.isna().sum() / len(drinking_water) * 100).round(2)
})
print("üìã Final Missing Value Report: Drinking Water (After Imputation)")
print(missing_report_final)

# üëÄ Preview final result
drinking_water.head()

üìã Final Missing Value Report: Drinking Water (After Imputation)
                     Missing Count  Missing %
FIPS                             0       0.00
State                            0       0.00
County                           0       0.00
drinking_water_2020              7       0.22
drinking_water_2021              7       0.22
drinking_water_2022              7       0.22
drinking_water_2023              7       0.22
drinking_water_2024              7       0.22
drinking_water_mean              7       0.22

,FIPS,State,County,drinking_water_2020,drinking_water_2021,drinking_water_2022,drinking_water_2023,drinking_water_2024,drinking_water_mean
0,21021,KY,Boyle County,0.188443,0.188443,0.188443,0.188443,0.0,0.150754
1,21023,KY,Bracken County,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
2,21025,KY,Breathitt County,1.000000,1.000000,1.000000,0.000000,0.0,0.600000
3,21027,KY,Breckinridge County,1.000000,0.000000,0.000000,0.000000,0.0,0.200000
4,21029,KY,Bullitt County,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [9]:
drinking_water[drinking_water[water_cols].isna().any(axis=1)] # viewing all missed values and deciding leave as is

,FIPS,State,County,drinking_water_2020,drinking_water_2021,drinking_water_2022,drinking_water_2023,drinking_water_2024,drinking_water_mean
2733,15000,HI,Hawaii,NaN,NaN,NaN,NaN,NaN,NaN
2734,15001,HI,Hawaii County,NaN,NaN,NaN,NaN,NaN,NaN
2735,15003,HI,Honolulu County,NaN,NaN,NaN,NaN,NaN,NaN
2736,15005,HI,Kalawao County,NaN,NaN,NaN,NaN,NaN,NaN
2737,15007,HI,Kauai County,NaN,NaN,NaN,NaN,NaN,NaN
2738,15009,HI,Maui County,NaN,NaN,NaN,NaN,NaN,NaN
3198,fipscode,state,county,NaN,NaN,NaN,NaN,NaN,NaN

üßæ General Interpretation: Drinking Water Violations Data (2020‚Äì2024) This dataset tracks how frequently each U.S. county violated drinking water safety standards over 5 years. Each year is represented by a value from 0 (no violations) to 1 (violations throughout the year). The column drinking_water_mean summarizes a county‚Äôs 5-year average violation rate.

Counties with values close to 0 consistently provided safe drinking water, while higher averages (e.g., 0.6) signal frequent or recurring water quality issues. This helps identify areas where public health infrastructure may require attention.

Some counties have not reported data for specific years. In those cases, missing values were imputed using the state-level average, allowing for fair comparison across all counties.

In [11]:
# ==========================================================
# PART 2A: Load Air Pollution Data and Report Missing
# ==========================================================

def load_air_pollution_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename))
    df.columns = df.columns.str.strip()

    # Handle different capitalization variations
    possible_cols = [
        "Air pollution - particulate matter raw value",
        "Air Pollution - Particulate Matter raw value"
    ]
    value_col = next((col for col in possible_cols if col in df.columns), None)

    new_col = f'air_pollution_{year}'
    if value_col is None:
        print(f"‚ö†Ô∏è  Column not found in {filename}. Filling {new_col} with NA.")
        df[new_col] = pd.NA
    else:
        df = df.rename(columns={value_col: new_col})

    df = df.rename(columns={
        '5-digit FIPS Code': 'FIPS',
        'State Abbreviation': 'State',
        'Name': 'County'
    })

    return df[['FIPS', 'State', 'County', new_col]]

# üì• Load all 5 years
pollution_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_air_pollution_column(file_path, year)
    pollution_dfs.append(df)

# üß© Merge yearly data
air_pollution = pollution_dfs[0]
for df in pollution_dfs[1:]:
    air_pollution = pd.merge(air_pollution, df, on=["FIPS", "State", "County"], how="outer")

# üìä Calculate 5-year average (pre-imputation)
pollution_cols = [f'air_pollution_{y}' for y in range(2020, 2025)]
air_pollution[pollution_cols] = air_pollution[pollution_cols].apply(pd.to_numeric, errors='coerce')
air_pollution['air_pollution_mean'] = air_pollution[pollution_cols].mean(axis=1, skipna=True)

# ‚ùå Report missing values before imputation
missing_report_pollution = pd.DataFrame({
    "Missing Count": air_pollution.isna().sum(),
    "Missing %": (air_pollution.isna().sum() / len(air_pollution) * 100).round(2)
})
print("üìã Missing Value Report (Air Pollution, Before Imputation)")
print(missing_report_pollution)

# üëÄ Preview result
air_pollution.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/3766572828.py:6: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(input_path, filename))
/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/3766572828.py:6: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(input_path, filename))

‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/3766572828.py:6: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(input_path, filename))
/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/3766572828.py:6: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(input_path, filename))

‚úÖ Found file for 2024: analytic_data2024.csv
üìã Missing Value Report (Air Pollution, Before Imputation)
                    Missing Count  Missing %
FIPS                            0       0.00
State                           0       0.00
County                          0       0.00
air_pollution_2020             41       1.28
air_pollution_2021             31       0.97
air_pollution_2022             32       1.00
air_pollution_2023             32       1.00
air_pollution_2024             32       1.00
air_pollution_mean             29       0.91

/var/folders/tt/mzspvn2d7hb3qsps4c4lqh0c0000gn/T/ipykernel_15958/3766572828.py:6: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(input_path, filename))

,FIPS,State,County,air_pollution_2020,air_pollution_2021,air_pollution_2022,air_pollution_2023,air_pollution_2024,air_pollution_mean
0,21021,KY,Boyle County,NaN,NaN,NaN,NaN,8.3,8.30
1,21023,KY,Bracken County,10.5,8.5,8.8,8.3,8.3,8.88
2,21025,KY,Breathitt County,9.7,9.0,7.9,7.7,7.7,8.40
3,21027,KY,Breckinridge County,11.8,8.8,9.2,8.8,8.8,9.48
4,21029,KY,Bullitt County,12.4,9.2,10.0,9.9,9.9,10.28

In [12]:
# ==========================================================
# PART 2B: Impute and Recalculate Air Pollution Averages
# ==========================================================

# üßº Impute missing values by state-wise mean
states = air_pollution['State'].unique()
for state in states:
    state_mean = air_pollution.loc[air_pollution['State'] == state, 'air_pollution_mean'].mean()
    for col in pollution_cols:
        air_pollution.loc[
            (air_pollution['State'] == state) & (air_pollution[col].isna()),
            col
        ] = state_mean

# üîÅ Recalculate mean after imputation
air_pollution[pollution_cols] = air_pollution[pollution_cols].apply(pd.to_numeric, errors='coerce')
air_pollution['air_pollution_mean'] = air_pollution[pollution_cols].mean(axis=1, skipna=True)

# ‚úÖ Final missing check
missing_report_final_pollution = pd.DataFrame({
    "Missing Count": air_pollution.isna().sum(),
    "Missing %": (air_pollution.isna().sum() / len(air_pollution) * 100).round(2)
})
print("üìã Final Missing Value Report: Air Pollution (After Imputation)")
print(missing_report_final_pollution)

# üëÄ Preview final result
air_pollution.head()

üìã Final Missing Value Report: Air Pollution (After Imputation)
                    Missing Count  Missing %
FIPS                            0       0.00
State                           0       0.00
County                          0       0.00
air_pollution_2020              1       0.03
air_pollution_2021              1       0.03
air_pollution_2022              1       0.03
air_pollution_2023              1       0.03
air_pollution_2024              1       0.03
air_pollution_mean              1       0.03

,FIPS,State,County,air_pollution_2020,air_pollution_2021,air_pollution_2022,air_pollution_2023,air_pollution_2024,air_pollution_mean
0,21021,KY,Boyle County,8.880902,8.880902,8.880902,8.880902,8.3,8.764721
1,21023,KY,Bracken County,10.500000,8.500000,8.800000,8.300000,8.3,8.880000
2,21025,KY,Breathitt County,9.700000,9.000000,7.900000,7.700000,7.7,8.400000
3,21027,KY,Breckinridge County,11.800000,8.800000,9.200000,8.800000,8.8,9.480000
4,21029,KY,Bullitt County,12.400000,9.200000,10.000000,9.900000,9.9,10.280000

In [13]:
air_pollution.tail()

,FIPS,State,County,air_pollution_2020,air_pollution_2021,air_pollution_2022,air_pollution_2023,air_pollution_2024,air_pollution_mean
3194,21015,KY,Boone County,12.0,9.4,10.1,9.8,9.800000,10.22000
3195,21017,KY,Bourbon County,10.5,8.8,8.9,8.5,8.500000,9.04000
3196,21019,KY,Boyd County,10.4,7.7,7.9,7.8,7.800000,8.32000
3197,21021,KY,Boyle County,10.5,8.7,8.7,8.3,8.880902,9.01618
3198,fipscode,state,county,NaN,NaN,NaN,NaN,NaN,NaN

üßæ General Interpretation: Air Pollution (PM2.5), 2020‚Äì2024 This dataset shows the annual average concentration of fine particulate matter (PM2.5, ¬µg/m¬≥) in each U.S. county over 5 years. The air_pollution_mean reflects each county‚Äôs 5-year average exposure.

üìå What it tells us: Lower values (7‚Äì9) = cleaner air Higher values (10+) = more pollution, greater health risk Helps identify environmental health disparities and areas needing air quality improvement. üåç Standards: EPA limit: 12 ¬µg/m¬≥ (annual average) WHO guideline: 5 ¬µg/m¬≥ (2021 update) Most U.S. counties stay under EPA‚Äôs limit but exceed WHO‚Äôs target. üßº Data Note: Missing values (for some counties/years) were imputed using state-level means for consistent comparison.

In [15]:
air_pollution

,FIPS,State,County,air_pollution_2020,air_pollution_2021,air_pollution_2022,air_pollution_2023,air_pollution_2024,air_pollution_mean
0,21021,KY,Boyle County,8.880902,8.880902,8.880902,8.880902,8.300000,8.764721
1,21023,KY,Bracken County,10.500000,8.500000,8.800000,8.300000,8.300000,8.880000
2,21025,KY,Breathitt County,9.700000,9.000000,7.900000,7.700000,7.700000,8.400000
3,21027,KY,Breckinridge County,11.800000,8.800000,9.200000,8.800000,8.800000,9.480000
4,21029,KY,Bullitt County,12.400000,9.200000,10.000000,9.900000,9.900000,10.280000
...,...,...,...,...,...,...,...,...,...
3194,21015,KY,Boone County,12.000000,9.400000,10.100000,9.800000,9.800000,10.220000
3195,21017,KY,Bourbon County,10.500000,8.800000,8.900000,8.500000,8.500000,9.040000
3196,21019,KY,Boyd County,10.400000,7.700000,7.900000,7.800000,7.800000,8.320000
3197,21021,KY,Boyle County,10.500000,8.700000,8.700000,8.300000,8.880902,9.016180
3198,fipscode,state,county,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Show all rows where FIPS is 22059 in air_pollution dataset
rows_22059 = air_pollution[air_pollution['FIPS'] == 22059]

# Display the actual rows (not a boolean series)
print(rows_22059)

      FIPS State           County  air_pollution_2020  air_pollution_2021  \
140  22059    LA  La Salle Parish            9.100000            8.500000
141  22059    LA   LaSalle Parish            8.953333            8.953333

     air_pollution_2022  air_pollution_2023  air_pollution_2024  \
140            9.100000            8.953333            8.953333
141            8.953333            8.400000            8.400000

     air_pollution_mean
140            8.921333
141            8.732000

In [17]:
# ==========================================================
# PART 3A: Load Access to Exercise Opportunities and Report Missing (No Per-Year Output)
# ==========================================================

def load_exercise_access_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # Define expected columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Target variable (ignore case)
    target_cols = [
        "access to exercise opportunities raw value",
        "Access to exercise opportunities raw value",
        "Access to Exercise Opportunities raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'exercise_access_{year}'

    # Start new DataFrame with anchor columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    # Add target value column
    if value_col:
        out_df[new_col] = df[value_col]
    else:
        out_df[new_col] = pd.NA  # no verbose warning here

    return out_df

# üì• Load all 5 years
exercise_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_exercise_access_column(file_path, year)
    exercise_dfs.append(df)

# üß© Merge on FIPS + State + County
exercise_access = exercise_dfs[0]
for df in exercise_dfs[1:]:
    exercise_access = pd.merge(exercise_access, df, on=["FIPS", "State", "County"], how="outer")

# üìä Calculate 5-year average (pre-imputation)
exercise_cols = [f'exercise_access_{y}' for y in range(2020, 2025)]
exercise_access[exercise_cols] = exercise_access[exercise_cols].apply(pd.to_numeric, errors='coerce')
exercise_access['exercise_access_mean'] = exercise_access[exercise_cols].mean(axis=1, skipna=True)

# ‚úÖ Final Missing Value Report
missing_report_exercise = pd.DataFrame({
    "Missing Count": exercise_access.isna().sum(),
    "Missing %": (exercise_access.isna().sum() / len(exercise_access) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (All Years Combined)")
print(missing_report_exercise)

# üëÄ Preview
exercise_access.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (All Years Combined)
                      Missing Count  Missing %
FIPS                              0       0.00
State                             0       0.00
County                            0       0.00
exercise_access_2020             10       0.31
exercise_access_2021             10       0.31
exercise_access_2022             80       2.50
exercise_access_2023             66       2.06
exercise_access_2024             48       1.50
exercise_access_mean              1       0.03

,FIPS,State,County,exercise_access_2020,exercise_access_2021,exercise_access_2022,exercise_access_2023,exercise_access_2024,exercise_access_mean
0,00000,US,United States,0.841687,0.841687,0.797930,0.842386,0.841440,0.833026
1,01000,AL,Alabama,0.611123,0.611123,0.566371,0.609267,0.613338,0.602244
2,01001,AL,Autauga County,0.691301,0.691301,0.627586,0.555378,0.544920,0.622097
3,01003,AL,Baldwin County,0.737135,0.737135,0.745080,0.657358,0.631293,0.701601
4,01005,AL,Barbour County,0.531668,0.531668,0.498379,0.548428,0.548547,0.531738

In [18]:
# ==========================================================
# PART 3B: Impute and Recalculate Exercise Access Averages
# ==========================================================

# üßº Impute missing values using state-wise mean
states = exercise_access['State'].unique()
for state in states:
    state_mean = exercise_access.loc[exercise_access['State'] == state, 'exercise_access_mean'].mean()
    for col in exercise_cols:
        exercise_access.loc[
            (exercise_access['State'] == state) & (exercise_access[col].isna()),
            col
        ] = state_mean

# üîÅ Recalculate mean after imputation
exercise_access[exercise_cols] = exercise_access[exercise_cols].apply(pd.to_numeric, errors='coerce')
exercise_access['exercise_access_mean'] = exercise_access[exercise_cols].mean(axis=1, skipna=True)

# ‚úÖ Final missing value report
missing_report_final_exercise = pd.DataFrame({
    "Missing Count": exercise_access.isna().sum(),
    "Missing %": (exercise_access.isna().sum() / len(exercise_access) * 100).round(2)
})
print("üìã Final Missing Value Report: Exercise Access (After Imputation)")
print(missing_report_final_exercise)

# üëÄ Preview result
exercise_access.head()

üìã Final Missing Value Report: Exercise Access (After Imputation)
                      Missing Count  Missing %
FIPS                              0       0.00
State                             0       0.00
County                            0       0.00
exercise_access_2020              1       0.03
exercise_access_2021              1       0.03
exercise_access_2022              1       0.03
exercise_access_2023              1       0.03
exercise_access_2024              1       0.03
exercise_access_mean              1       0.03

,FIPS,State,County,exercise_access_2020,exercise_access_2021,exercise_access_2022,exercise_access_2023,exercise_access_2024,exercise_access_mean
0,00000,US,United States,0.841687,0.841687,0.797930,0.842386,0.841440,0.833026
1,01000,AL,Alabama,0.611123,0.611123,0.566371,0.609267,0.613338,0.602244
2,01001,AL,Autauga County,0.691301,0.691301,0.627586,0.555378,0.544920,0.622097
3,01003,AL,Baldwin County,0.737135,0.737135,0.745080,0.657358,0.631293,0.701601
4,01005,AL,Barbour County,0.531668,0.531668,0.498379,0.548428,0.548547,0.531738

üßæ General Interpretation: Access to Exercise Opportunities (2020‚Äì2024) This dataset shows the proportion of each county‚Äôs population with adequate access to locations for physical activity (e.g., parks, gyms, trails) over a 5-year period.

Values range from 0 (no access) to 1 (full access), with access_exercise_mean reflecting the 5-year average.

üìå What it tells us: Higher values (e.g., 0.70+) = broad community access to exercise spaces ‚úÖ Lower values (e.g., < 0.10) = limited access, likely rural or underserved areas ‚ö†Ô∏è Important for understanding health equity and targeting community health investments. üßº Data Note: Some counties had missing data, which was filled using their state‚Äôs average score to enable fair comparisons.

In [20]:
# ==========================================================
# PART 4: Load Violent Crime and Report Missing (Selective Mean)
# ==========================================================

# üîç Show only columns related to "violent crime"
for year in [2023, 2024]:
    file_path = os.path.join(input_path, get_file_path(year))
    df = pd.read_csv(file_path, nrows=0)  # only read headers
    matching_cols = [col for col in df.columns if "violent crime" in col.lower()]
    
    print(f"\nüìÅ Matching columns in {year}:")
    if matching_cols:
        for col in matching_cols:
            print("‚Ä¢", col)
    else:
        print("‚ùå No matching column found.")

‚úÖ Found file for 2023: analytic_data2023.csv

üìÅ Matching columns in 2023:
‚ùå No matching column found.
‚úÖ Found file for 2024: analytic_data2024.csv

üìÅ Matching columns in 2024:
‚ùå No matching column found.

In [21]:
# ==========================================================
# PART 4A: Load Violent Crime and Report Missing (Selective Mean)
# ==========================================================

def load_violent_crime_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # Define stable ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = [
        "violent crime raw value",
        "Violent crime raw value",
        "Violent Crime raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'violent_crime_{year}'

    # Create base DataFrame
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
crime_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_violent_crime_column(file_path, year)
    crime_dfs.append(df)

# üß© Merge on FIPS + State + County
violent_crime = crime_dfs[0]
for df in crime_dfs[1:]:
    violent_crime = pd.merge(violent_crime, df, on=["FIPS", "State", "County"], how="outer")

# üìä Collect all yearly columns (even if some are not used in mean)
all_years = [2020, 2021, 2022, 2023, 2024]
all_crime_cols = [f'violent_crime_{y}' for y in all_years]
violent_crime[all_crime_cols] = violent_crime[all_crime_cols].apply(pd.to_numeric, errors='coerce')

# üéØ Only calculate mean for selected years
selected_years = [2020, 2021, 2023]
crime_cols = [f'violent_crime_{y}' for y in selected_years]
violent_crime['violent_crime_mean'] = violent_crime[crime_cols].mean(axis=1, skipna=True)

# ‚úÖ Summary Missing Value Report for All Years
missing_report_crime = pd.DataFrame({
    "Missing Count": violent_crime[all_crime_cols].isna().sum(),
    "Missing %": (violent_crime[all_crime_cols].isna().sum() / len(violent_crime) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Violent Crime, All Years)")
print(missing_report_crime)

# üîç Show only rows with any missing values in selected columns (used in mean)
rows_with_na = violent_crime[violent_crime[crime_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values in {selected_years}: {len(rows_with_na)} rows")
rows_with_na.head(50)

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Violent Crime, All Years)
                    Missing Count  Missing %
violent_crime_2020            195        6.1
violent_crime_2021            195        6.1
violent_crime_2022            195        6.1
violent_crime_2023           3198      100.0
violent_crime_2024           3198      100.0

üîç Rows with missing values in [2020, 2021, 2023]: 3198 rows

,FIPS,State,County,violent_crime_2020,violent_crime_2021,violent_crime_2022,violent_crime_2023,violent_crime_2024,violent_crime_mean
0,00000,US,United States,386.464896,386.464896,386.464896,NaN,NaN,386.464896
1,01000,AL,Alabama,479.919182,479.919182,479.919182,NaN,NaN,479.919182
2,01001,AL,Autauga County,272.282220,272.282220,272.282220,NaN,NaN,272.282220
3,01003,AL,Baldwin County,203.660396,203.660396,203.660396,NaN,NaN,203.660396
4,01005,AL,Barbour County,414.277861,414.277861,414.277861,NaN,NaN,414.277861
5,01007,AL,Bibb County,89.349126,89.349126,89.349126,NaN,NaN,89.349126
6,01009,AL,Blount County,482.690611,482.690611,482.690611,NaN,NaN,482.690611
7,01011,AL,Bullock County,311.027333,311.027333,311.027333,NaN,NaN,311.027333
8,01013,AL,Butler County,581.584005,581.584005,581.584005,NaN,NaN,581.584005
9,01015,AL,Calhoun County,756.066544,756.066544,756.066544,NaN,NaN,756.066544
10,01017,AL,Chambers County,528.999736,528.999736,528.999736,NaN,NaN,528.999736
11,01019,AL,Cherokee County,330.438792,330.438792,330.438792,NaN,NaN,330.438792
12,01021,AL,Chilton County,507.810721,507.810721,507.810721,NaN,NaN,507.810721
13,01023,AL,Choctaw County,128.414663,128.414663,128.414663,NaN,NaN,128.414663
14,01025,AL,Clarke County,475.312436,475.312436,475.312436,NaN,NaN,475.312436
15,01027,AL,Clay County,309.067213,309.067213,309.067213,NaN,NaN,309.067213
16,01029,AL,Cleburne County,103.333333,103.333333,103.333333,NaN,NaN,103.333333
17,01031,AL,Coffee County,276.208044,276.208044,276.208044,NaN,NaN,276.208044
18,01033,AL,Colbert County,400.007356,400.007356,400.007356,NaN,NaN,400.007356
19,01035,AL,Conecuh County,387.409201,387.409201,387.409201,NaN,NaN,387.409201
20,01037,AL,Coosa County,254.832195,254.832195,254.832195,NaN,NaN,254.832195
21,01039,AL,Covington County,331.121424,331.121424,331.121424,NaN,NaN,331.121424
22,01041,AL,Crenshaw County,331.907361,331.907361,331.907361,NaN,NaN,331.907361
23,01043,AL,Cullman County,129.392286,129.392286,129.392286,NaN,NaN,129.392286
24,01045,AL,Dale County,436.721419,436.721419,436.721419,NaN,NaN,436.721419
25,01047,AL,Dallas County,924.561168,924.561168,924.561168,NaN,NaN,924.561168
26,01049,AL,DeKalb County,312.330688,312.330688,312.330688,NaN,NaN,312.330688
27,01051,AL,Elmore County,238.676664,238.676664,238.676664,NaN,NaN,238.676664
28,01053,AL,Escambia County,446.245316,446.245316,446.245316,NaN,NaN,446.245316
29,01055,AL,Etowah County,603.962620,603.962620,603.962620,NaN,NaN,603.962620
30,01057,AL,Fayette County,NaN,NaN,NaN,NaN,NaN,NaN
31,01059,AL,Franklin County,264.234436,264.234436,264.234436,NaN,NaN,264.234436
32,01061,AL,Geneva County,413.571121,413.571121,413.571121,NaN,NaN,413.571121
33,01063,AL,Greene County,669.344043,669.344043,669.344043,NaN,NaN,669.344043
34,01065,AL,Hale County,208.558073,208.558073,208.558073,NaN,NaN,208.558073
35,01067,AL,Henry County,197.372297,197.372297,197.372297,NaN,NaN,197.372297
36,01069,AL,Houston County,487.788484,487.788484,487.788484,NaN,NaN,487.788484
37,01071,AL,Jackson County,316.984948,316.984948,316.984948,NaN,NaN,316.984948
38,01073,AL,Jefferson County,872.750020,872.750020,872.750020,NaN,NaN,872.750020
39,01075,AL,Lamar County,162.211722,162.211722,162.211722,NaN,NaN,162.211722
40,01077,AL,Lauderdale County,268.603209,268.603209,268.603209,NaN,NaN,268.603209
41,01079,AL,Lawrence County,260.453002,260.453002,260.453002,NaN,NaN,260.453002
42,01081,AL,Lee County,415.637401,415.637401,415.637401,NaN,NaN,415.637401
43,01083,AL,Limestone County,160.123742,160.123742,160.123742,NaN,NaN,160.123742
44,01085,AL,Lowndes County,671.019224,671.019224,671.019224,NaN,NaN,671.019224
45,01087,AL,Macon County,734.312417,734.312417,734.312417,NaN,NaN,734.312417
46,01089,AL,Madison County,610.723159,610.723159,610.723159,NaN,NaN,610.723159
47,01091,AL,Marengo County,449.415249,449.415249,449.415249,NaN,NaN,449.415249
48,01093,AL,Marion County,295.897334,295.897334,295.897334,NaN,NaN,295.897334
49,01095,AL,Marshall County,286.269082,286.269082,286.269082,NaN,NaN,286.269082

In [22]:
# ==========================================================
# PART 4B: Impute and Recalculate Violent Crime Averages (2020‚Äì2022 only)
# ==========================================================

# üéØ Define imputation years
impute_years = [2020, 2021, 2022]
crime_cols = [f'violent_crime_{y}' for y in impute_years]

# üßº Impute missing values using state-wide mean (only for 2020‚Äì2022)
states = violent_crime['State'].unique()
for state in states:
    state_df = violent_crime[violent_crime['State'] == state]
    state_means = state_df[crime_cols].mean(skipna=True)

    for col in crime_cols:
        missing_mask = (violent_crime['State'] == state) & (violent_crime[col].isna())
        violent_crime.loc[missing_mask, col] = state_means[col]

# üîÅ Recalculate mean using only 2020, 2021, 2022
violent_crime['violent_crime_mean'] = violent_crime[crime_cols].mean(axis=1, skipna=True)

# ‚úÖ Final Missing Value Report (including untouched 2023‚Äì2024)
all_years = [2020, 2021, 2022, 2023, 2024]
all_crime_cols = [f'violent_crime_{y}' for y in all_years]

missing_report_final_crime = pd.DataFrame({
    "Missing Count": violent_crime[all_crime_cols].isna().sum(),
    "Missing %": (violent_crime[all_crime_cols].isna().sum() / len(violent_crime) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Violent Crime (After Imputation)")
print(missing_report_final_crime)

# üëÄ Preview updated data
violent_crime.head()

üìã Final Missing Value Report: Violent Crime (After Imputation)
                    Missing Count  Missing %
violent_crime_2020              1       0.03
violent_crime_2021              1       0.03
violent_crime_2022              1       0.03
violent_crime_2023           3198     100.00
violent_crime_2024           3198     100.00

,FIPS,State,County,violent_crime_2020,violent_crime_2021,violent_crime_2022,violent_crime_2023,violent_crime_2024,violent_crime_mean
0,00000,US,United States,386.464896,386.464896,386.464896,NaN,NaN,386.464896
1,01000,AL,Alabama,479.919182,479.919182,479.919182,NaN,NaN,479.919182
2,01001,AL,Autauga County,272.282220,272.282220,272.282220,NaN,NaN,272.282220
3,01003,AL,Baldwin County,203.660396,203.660396,203.660396,NaN,NaN,203.660396
4,01005,AL,Barbour County,414.277861,414.277861,414.277861,NaN,NaN,414.277861

In [23]:
# üéØ Sample - Compare violent crime across 2020‚Äì2022 for California counties

# Define years and columns
compare_years = [2020, 2021, 2022]
compare_cols = [f'violent_crime_{y}' for y in compare_years]

# üèõÔ∏è Filter for California counties only (and make a clean copy)
ca_crime = violent_crime[violent_crime['State'] == 'CA'].copy()

# üßº Ensure numeric
for col in compare_cols:
    ca_crime[col] = pd.to_numeric(ca_crime[col], errors='coerce')

# üìä Show comparison table
ca_comparison = ca_crime[['County', 'FIPS'] + compare_cols]
ca_comparison = ca_comparison.sort_values(by='County').reset_index(drop=True)

# üëÄ Print the first 10 rows as a preview
print("\nüìã California Violent Crime Comparison (2020‚Äì2022):")
print(ca_comparison.head(10))

üìã California Violent Crime Comparison (2020‚Äì2022):
                County   FIPS  violent_crime_2020  violent_crime_2021  \
0       Alameda County  06001          628.781962          628.781962
1        Alpine County  06003          442.477876          442.477876
2        Amador County  06005          237.070738          237.070738
3         Butte County  06007          327.057309          327.057309
4     Calaveras County  06009          327.245738          327.245738
5           California  06000          420.876882          420.876882
6        Colusa County  06011          200.958056          200.958056
7  Contra Costa County  06013          336.027791          336.027791
8     Del Norte County  06015          609.109201          609.109201
9     El Dorado County  06017          217.583946          217.583946

   violent_crime_2022
0          628.781962
1          442.477876
2          237.070738
3          327.057309
4          327.245738
5          420.876882
6          200.958056
7          336.027791
8          609.109201
9          217.583946

The violent crime data used in this analysis appears to be incomplete or potentially inaccurate:
	‚Ä¢	Values for 2020‚Äì2022 are identical across all three years for many counties, which is statistically unlikely.
	‚Ä¢	Data for 2023 and 2024 is completely missing.
	‚Ä¢	Based on this pattern, it is likely that the dataset relies on FBI Uniform Crime Reporting (UCR) sources, which have been known to experience data submission issues from local agencies in recent years.

üîç The FBI itself has advised caution when using this data for year-over-year comparisons due to inconsistent reporting and coverage.

In [25]:
# ==========================================================
# PART 5A: Load Injury Deaths and Report Missing
# ==========================================================

def load_injury_deaths_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # Core ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Target column (case-insensitive variants)
    target_cols = [
        "injury deaths raw value",
        "Injury deaths raw value",
        "Injury Deaths raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'injury_deaths_{year}'

    # Check and rename
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
injury_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_injury_deaths_column(file_path, year)
    injury_dfs.append(df)

# üß© Merge on ID columns
injury_deaths = injury_dfs[0]
for df in injury_dfs[1:]:
    injury_deaths = pd.merge(injury_deaths, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert and calculate mean
injury_cols = [f'injury_deaths_{y}' for y in range(2020, 2025)]
injury_deaths[injury_cols] = injury_deaths[injury_cols].apply(pd.to_numeric, errors='coerce')
injury_deaths['injury_deaths_mean'] = injury_deaths[injury_cols].mean(axis=1, skipna=True)

# üìã Missing value report
missing_report_injury = pd.DataFrame({
    "Missing Count": injury_deaths[injury_cols].isna().sum(),
    "Missing %": (injury_deaths[injury_cols].isna().sum() / len(injury_deaths) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Injury Deaths, Before Imputation)")
print(missing_report_injury)

# üîç Preview rows with any missing
rows_with_na_injury = injury_deaths[injury_deaths[injury_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_injury)}")
rows_with_na_injury.head(136)

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Injury Deaths, Before Imputation)
                    Missing Count  Missing %
injury_deaths_2020            104       3.25
injury_deaths_2021            114       3.56
injury_deaths_2022            109       3.41
injury_deaths_2023            109       3.41
injury_deaths_2024            109       3.41

üîç Rows with missing values: 136

,FIPS,State,County,injury_deaths_2020,injury_deaths_2021,injury_deaths_2022,injury_deaths_2023,injury_deaths_2024,injury_deaths_mean
70,02013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,NaN,NaN
74,02060,AK,Bristol Bay Borough,222.667557,228.832952,NaN,NaN,NaN,225.750255
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,NaN,NaN
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,NaN,NaN
77,02068,AK,Denali Borough,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2830,49009,UT,Daggett County,NaN,NaN,NaN,NaN,NaN,NaN
2841,49031,UT,Piute County,NaN,NaN,NaN,NaN,NaN,NaN
2915,51091,VA,Highland County,126.126126,99.619634,NaN,NaN,NaN,112.872880
3016,53023,WA,Garfield County,NaN,NaN,NaN,NaN,NaN,NaN
3197,fipscode,state,county,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
# üìä Count missing values by State and Year
missing_by_state_year = injury_deaths.groupby("State")[
    injury_cols
].apply(lambda df: df.isna().sum()).astype(int)

# üßæ Rename columns for readability (optional)
missing_by_state_year.columns = [col.replace("injury_deaths_", "Year ") for col in missing_by_state_year.columns]

# üëÄ Show full table
print("\nüìç Missing Injury Deaths by State and Year")
print(missing_by_state_year)

üìç Missing Injury Deaths by State and Year
       Year 2020  Year 2021  Year 2022  Year 2023  Year 2024
State
AK             8          8          8          8          9
AL             0          0          0          0          0
AR             0          0          0          0          0
AZ             0          0          0          0          0
CA             0          0          0          0          0
CO             5          6          6          6          6
CT             0          0          0          0          0
DC             0          0          0          0          0
DE             0          0          0          0          0
FL             0          0          0          0          0
GA             1          2          1          1          1
HI             1          1          1          1          1
IA             0          0          0          0          0
ID             2          3          2          2          2
IL             0          0          0          0          0
IN             0          0          0          0          0
KS             2          6          5          5          5
KY             0          0          0          0          0
LA             1          1          1          1          1
MA             0          0          0          0          0
MD             0          0          0          0          0
ME             0          0          0          0          0
MI             0          0          0          0          0
MN             0          0          0          0          0
MO             0          0          0          0          0
MS             1          1          1          1          1
MT             8         13         12         12         12
NC             0          0          0          0          0
ND            12         11         12         12         13
NE            23         20         18         18         20
NH             0          0          0          0          0
NJ             0          0          0          0          0
NM             1          1          1          1          1
NV             2          2          2          2          2
NY             0          0          1          1          0
OH             0          0          0          0          0
OK             0          1          1          1          1
OR             3          2          2          2          1
PA             0          0          0          0          0
RI             0          0          0          0          0
SC             0          0          0          0          0
SD             9         11          9          9          8
TN             0          0          0          0          0
TX            21         21         21         21         20
US             0          0          0          0          0
UT             2          2          2          2          2
VA             0          0          1          1          1
VT             0          0          0          0          0
WA             1          1          1          1          1
WI             0          0          0          0          0
WV             0          0          0          0          0
WY             0          0          0          0          0
state          1          1          1          1          1

In [27]:
# üßÆ Total rows per state
total_rows_by_state = injury_deaths.groupby("State").size()

# ‚ùå Missing values by state/year (same as before)
missing_by_state_year = injury_deaths.groupby("State")[
    injury_cols
].apply(lambda df: df.isna().sum()).astype(int)

# ‚úÖ Available values = total - missing
available_by_state_year = missing_by_state_year.copy()
for state in available_by_state_year.index:
    available_by_state_year.loc[state] = total_rows_by_state[state] - missing_by_state_year.loc[state]

# üßæ Rename columns for clarity
available_by_state_year.columns = [col.replace("injury_deaths_", "Year ") for col in available_by_state_year.columns]

# üëÄ Show the result
print("\n‚úÖ Available Injury Deaths by State and Year")
print(available_by_state_year)

‚úÖ Available Injury Deaths by State and Year
       Year 2020  Year 2021  Year 2022  Year 2023  Year 2024
State
AK            24         24         24         24         23
AL            68         68         68         68         68
AR            76         76         76         76         76
AZ            16         16         16         16         16
CA            59         59         59         59         59
CO            60         59         59         59         59
CT             9          9          9          9          9
DC             2          2          2          2          2
DE             4          4          4          4          4
FL            68         68         68         68         68
GA           159        158        159        159        159
HI             5          5          5          5          5
IA           100        100        100        100        100
ID            43         42         43         43         43
IL           103        103        103        103        103
IN            93         93         93         93         93
KS           104        100        101        101        101
KY           121        121        121        121        121
LA            65         65         65         65         65
MA            15         15         15         15         15
MD            25         25         25         25         25
ME            17         17         17         17         17
MI            84         84         84         84         84
MN            88         88         88         88         88
MO           116        116        116        116        116
MS            82         82         82         82         82
MT            49         44         45         45         45
NC           101        101        101        101        101
ND            42         43         42         42         41
NE            71         74         76         76         74
NH            11         11         11         11         11
NJ            22         22         22         22         22
NM            33         33         33         33         33
NV            16         16         16         16         16
NY            63         63         62         62         63
OH            89         89         89         89         89
OK            78         77         77         77         77
OR            34         35         35         35         36
PA            68         68         68         68         68
RI             6          6          6          6          6
SC            47         47         47         47         47
SD            58         56         58         58         59
TN            96         96         96         96         96
TX           234        234        234        234        235
US             1          1          1          1          1
UT            28         28         28         28         28
VA           134        134        133        133        133
VT            15         15         15         15         15
WA            39         39         39         39         39
WI            73         73         73         73         73
WV            56         56         56         56         56
WY            24         24         24         24         24
state          0          0          0          0          0

In [28]:
# ==========================================================
# PART 5B: Impute and Recalculate Injury Deaths Averages
# ==========================================================

# üéØ Target columns
injury_cols = [f'injury_deaths_{y}' for y in range(2020, 2025)]

# üßº Impute missing values with state-wise mean (per column/year)
states = injury_deaths['State'].unique()
for state in states:
    state_data = injury_deaths[injury_deaths['State'] == state]
    for col in injury_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (injury_deaths['State'] == state) & (injury_deaths[col].isna())
        injury_deaths.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean across all 5 years
injury_deaths['injury_deaths_mean'] = injury_deaths[injury_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_injury = pd.DataFrame({
    "Missing Count": injury_deaths[injury_cols].isna().sum(),
    "Missing %": (injury_deaths[injury_cols].isna().sum() / len(injury_deaths) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Injury Deaths (After Imputation)")
print(missing_report_final_injury)

# üëÄ Preview result
injury_deaths.head()

üìã Final Missing Value Report: Injury Deaths (After Imputation)
                    Missing Count  Missing %
injury_deaths_2020              1       0.03
injury_deaths_2021              1       0.03
injury_deaths_2022              1       0.03
injury_deaths_2023              1       0.03
injury_deaths_2024              1       0.03

,FIPS,State,County,injury_deaths_2020,injury_deaths_2021,injury_deaths_2022,injury_deaths_2023,injury_deaths_2024,injury_deaths_mean
0,00000,US,United States,69.874404,72.318503,75.899512,75.899512,80.005528,74.799492
1,01000,AL,Alabama,82.250245,84.463387,86.905718,86.905718,90.379699,86.180953
2,01001,AL,Autauga County,68.526994,68.410043,68.573070,68.573070,68.033478,68.423331
3,01003,AL,Baldwin County,72.385054,72.878641,74.835079,74.835079,77.507985,74.488367
4,01005,AL,Barbour County,70.274612,76.988947,82.143057,82.143057,85.215853,79.353105

Injury Deaths raw value

The Injury Deaths raw value represents the rate of injury-related deaths per 100,000 people in a given county and year.

It‚Äôs calculated using:
	‚Ä¢	The total number of injury deaths (numerator)
	‚Ä¢	The total county population (denominator)

Note: Some county-level data for Montana (MT), North Dakota (ND), Nebraska (NE), and Texas (TX) were missing for certain years. These values were substituted using the mean injury death rate of the relevant state to allow consistent comparison across all counties.

In [30]:
# ==========================================================
# PART 6A: Load Homicides and Report Missing
# ==========================================================

def load_homicides_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Target column variations
    target_cols = [
        "homicides raw value",
        "Homicides raw value",
        "Homicide raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'homicides_{year}'

    # Check required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
homicide_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_homicides_column(file_path, year)
    homicide_dfs.append(df)

# üß© Merge all years
homicides = homicide_dfs[0]
for df in homicide_dfs[1:]:
    homicides = pd.merge(homicides, df, on=["FIPS", "State", "County"], how="outer")

# üìä Calculate raw mean (pre-imputation)
homicide_cols = [f'homicides_{y}' for y in range(2020, 2025)]
homicides[homicide_cols] = homicides[homicide_cols].apply(pd.to_numeric, errors='coerce')
homicides['homicides_mean'] = homicides[homicide_cols].mean(axis=1, skipna=True)

# üìã Missing value report
missing_report_homicides = pd.DataFrame({
    "Missing Count": homicides[homicide_cols].isna().sum(),
    "Missing %": (homicides[homicide_cols].isna().sum() / len(homicides) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Homicides, Before Imputation)")
print(missing_report_homicides)

# üîç Show rows with any missing values
rows_with_na_homicide = homicides[homicides[homicide_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_homicide)}")
rows_with_na_homicide.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Homicides, Before Imputation)
                Missing Count  Missing %
homicides_2020           1862      58.22
homicides_2021           1846      57.72
homicides_2022           1820      56.91
homicides_2023           1820      56.91
homicides_2024           1770      55.35

üîç Rows with missing values: 1959

,FIPS,State,County,homicides_2020,homicides_2021,homicides_2022,homicides_2023,homicides_2024,homicides_mean
7,01011,AL,Bullock County,NaN,13.696941,15.204711,15.204711,19.470947,15.894327
13,01023,AL,Choctaw County,NaN,NaN,NaN,NaN,NaN,NaN
14,01025,AL,Clarke County,NaN,NaN,8.879523,8.879523,10.795056,9.518034
15,01027,AL,Clay County,NaN,NaN,NaN,NaN,NaN,NaN
16,01029,AL,Cleburne County,NaN,NaN,NaN,NaN,9.541165,9.541165

üßæ Data Note: Homicides raw value (2020‚Äì2024)

The Homicides raw value indicator shows substantial data gaps across all five years:
	‚Ä¢	Over 55% of counties have missing data each year.
	‚Ä¢	A total of 1,959 counties are missing at least one year of data.
	‚Ä¢	This level of incompleteness makes state-based imputation unreliable and potentially misleading.

‚ö†Ô∏è Action Taken:

No imputation was applied to this indicator due to the high proportion of missing values. Any trend or comparison analysis using this variable should be cautiously approached or excluded entirely from composite scoring or ranking efforts.

In [32]:
# ==========================================================
# PART 7A: Load Juvenile Arrests and Report Missing
# ==========================================================

def load_juvenile_arrests_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Column name variations
    target_cols = [
        "juvenile arrests raw value",
        "Juvenile arrests raw value",
        "Juvenile Arrests raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'juvenile_arrests_{year}'

    # Check required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
arrest_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_juvenile_arrests_column(file_path, year)
    arrest_dfs.append(df)

# üß© Merge into one DataFrame
juvenile_arrests = arrest_dfs[0]
for df in arrest_dfs[1:]:
    juvenile_arrests = pd.merge(juvenile_arrests, df, on=["FIPS", "State", "County"], how="outer")

# üìä Prepare and calculate pre-imputation mean
arrest_cols = [f'juvenile_arrests_{y}' for y in range(2020, 2025)]
juvenile_arrests[arrest_cols] = juvenile_arrests[arrest_cols].apply(pd.to_numeric, errors='coerce')
juvenile_arrests['juvenile_arrests_mean'] = juvenile_arrests[arrest_cols].mean(axis=1, skipna=True)

# üìã Missing value report
missing_report_juvenile = pd.DataFrame({
    "Missing Count": juvenile_arrests[arrest_cols].isna().sum(),
    "Missing %": (juvenile_arrests[arrest_cols].isna().sum() / len(juvenile_arrests) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Juvenile Arrests, Before Imputation)")
print(missing_report_juvenile)

# üîç Show rows with any missing values
rows_with_na_juvenile = juvenile_arrests[juvenile_arrests[arrest_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_juvenile)}")
rows_with_na_juvenile.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Juvenile Arrests, Before Imputation)
                       Missing Count  Missing %
juvenile_arrests_2020           1029      32.18
juvenile_arrests_2021           1350      42.21
juvenile_arrests_2022           1203      37.62
juvenile_arrests_2023           1203      37.62
juvenile_arrests_2024           1252      39.15

üîç Rows with missing values: 1918

,FIPS,State,County,juvenile_arrests_2020,juvenile_arrests_2021,juvenile_arrests_2022,juvenile_arrests_2023,juvenile_arrests_2024,juvenile_arrests_mean
0,00000,US,United States,NaN,NaN,18.998189,23.812000,NaN,21.405094
1,01000,AL,Alabama,NaN,NaN,NaN,NaN,12.262097,12.262097
2,01001,AL,Autauga County,10.625,NaN,8.064516,8.064516,4.838710,7.898185
4,01005,AL,Barbour County,15.000,NaN,23.750000,23.750000,NaN,20.833333
5,01007,AL,Bibb County,NaN,NaN,NaN,NaN,NaN,NaN

üßæ Data Note: Juvenile Arrests raw value (2020‚Äì2024)

The Juvenile arrests raw value dataset shows a moderate to high level of missing data across the 5 years:
	‚Ä¢	Missing rates range from 32% to 42% depending on the year
	‚Ä¢	A total of over 1,000 counties are missing data each year

‚ö†Ô∏è Action Taken:

No imputation was applied due to the volume and spread of missing data. This preserves the integrity of the available values but limits the ability to calculate complete 5-year averages for all counties.

Recommendation: Use this indicator cautiously for descriptive analysis, but avoid incorporating it into composite indices or comparisons unless filtered for complete cases.

In [34]:
# ==========================================================
# PART 8A: Load Firearm Fatalities and Report Missing
# ==========================================================

def load_firearm_fatalities_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Target column variations
    target_cols = [
        "firearm fatalities raw value",
        "Firearm fatalities raw value",
        "Firearm Fatalities raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'firearm_fatalities_{year}'

    # Required base columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
firearm_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_firearm_fatalities_column(file_path, year)
    firearm_dfs.append(df)

# üß© Merge into single DataFrame
firearm_fatalities = firearm_dfs[0]
for df in firearm_dfs[1:]:
    firearm_fatalities = pd.merge(firearm_fatalities, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert and calculate raw mean
firearm_cols = [f'firearm_fatalities_{y}' for y in range(2020, 2025)]
firearm_fatalities[firearm_cols] = firearm_fatalities[firearm_cols].apply(pd.to_numeric, errors='coerce')
firearm_fatalities['firearm_fatalities_mean'] = firearm_fatalities[firearm_cols].mean(axis=1, skipna=True)

# üìã Missing value report
missing_report_firearm = pd.DataFrame({
    "Missing Count": firearm_fatalities[firearm_cols].isna().sum(),
    "Missing %": (firearm_fatalities[firearm_cols].isna().sum() / len(firearm_fatalities) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Firearm Fatalities, Before Imputation)")
print(missing_report_firearm)

# üîç Show rows with any missing values
rows_with_na_firearm = firearm_fatalities[firearm_fatalities[firearm_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_firearm)}")
rows_with_na_firearm.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Firearm Fatalities, Before Imputation)
                         Missing Count  Missing %
firearm_fatalities_2020            920      28.77
firearm_fatalities_2021            907      28.36
firearm_fatalities_2022            875      27.36
firearm_fatalities_2023            875      27.36
firearm_fatalities_2024            867      27.11

üîç Rows with missing values: 1058

,FIPS,State,County,firearm_fatalities_2020,firearm_fatalities_2021,firearm_fatalities_2022,firearm_fatalities_2023,firearm_fatalities_2024,firearm_fatalities_mean
13,01023,AL,Choctaw County,16.852555,15.494747,NaN,NaN,NaN,16.173651
33,01063,AL,Greene County,NaN,NaN,NaN,NaN,NaN,NaN
39,01075,AL,Lamar County,NaN,14.409430,14.434805,14.434805,14.482679,14.440430
54,01105,AL,Perry County,NaN,NaN,21.899569,21.899569,22.500225,22.099787
70,02013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,NaN,NaN

üßæ Data Note: Firearm Fatalities raw value (2020‚Äì2024)

The Firearm fatalities raw value reflects the rate of deaths caused by firearms per 100,000 population, reported annually at the county level.

üìä Missing Data Overview:
	‚Ä¢	Roughly 27% to 29% of counties are missing yearly data.
	‚Ä¢	A total of 867‚Äì920 counties have incomplete records, depending on the year.


‚ö†Ô∏è Action Taken:

No imputation was applied to this indicator due to the substantial but stable level of missing data across years. Analyses using this variable should focus on counties with complete data or treat missingness explicitly in modeling.

In [36]:
# ==========================================================
# PART 9A: Load Long Commute (Driving Alone) and Report Missing
# ==========================================================

def load_long_commute_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Possible column names (case-insensitive)
    target_cols = [
        "long commute - driving alone raw value",
        "Long commute - driving alone raw value",
        "Long Commute - Driving Alone raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'long_commute_{year}'

    # Validate base columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
commute_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_long_commute_column(file_path, year)
    commute_dfs.append(df)

# üß© Merge data
long_commute = commute_dfs[0]
for df in commute_dfs[1:]:
    long_commute = pd.merge(long_commute, df, on=["FIPS", "State", "County"], how="outer")

# üìä Calculate mean (pre-imputation)
commute_cols = [f'long_commute_{y}' for y in range(2020, 2025)]
long_commute[commute_cols] = long_commute[commute_cols].apply(pd.to_numeric, errors='coerce')
long_commute['long_commute_mean'] = long_commute[commute_cols].mean(axis=1, skipna=True)

# üìã Missing value report
missing_report_commute = pd.DataFrame({
    "Missing Count": long_commute[commute_cols].isna().sum(),
    "Missing %": (long_commute[commute_cols].isna().sum() / len(long_commute) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Long Commute, Before Imputation)")
print(missing_report_commute)

# üîç Show rows with any missing values
rows_with_na_commute = long_commute[long_commute[commute_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_commute)}")
rows_with_na_commute.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Long Commute, Before Imputation)
                   Missing Count  Missing %
long_commute_2020              5       0.16
long_commute_2021              4       0.13
long_commute_2022              4       0.13
long_commute_2023              4       0.13
long_commute_2024              3       0.09

üîç Rows with missing values: 7

,FIPS,State,County,long_commute_2020,long_commute_2021,long_commute_2022,long_commute_2023,long_commute_2024,long_commute_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.069,0.069000
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.175,0.175000
97,02261,AK,Valdez-Cordova Census Area,0.036,0.049,0.085712,0.079361,NaN,0.062518
1164,22059,LA,La Salle Parish,0.351,0.355,0.345000,NaN,NaN,0.350333
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,0.368000,0.338,0.353000

In [37]:
# ==========================================================
# PART 9B: Impute and Recalculate Long Commute (Driving Alone)
# ==========================================================

# üéØ Column names
commute_cols = [f'long_commute_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-wise mean per year
states = long_commute['State'].unique()
for state in states:
    state_data = long_commute[long_commute['State'] == state]
    for col in commute_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (long_commute['State'] == state) & (long_commute[col].isna())
        long_commute.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
long_commute[commute_cols] = long_commute[commute_cols].apply(pd.to_numeric, errors='coerce')
long_commute['long_commute_mean'] = long_commute[commute_cols].mean(axis=1, skipna=True)

# üìã Final Missing Value Report
missing_report_final_commute = pd.DataFrame({
    "Missing Count": long_commute[commute_cols].isna().sum(),
    "Missing %": (long_commute[commute_cols].isna().sum() / len(long_commute) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Long Commute (After Imputation)")
print(missing_report_final_commute)

# üëÄ Preview
long_commute.head()

üìã Final Missing Value Report: Long Commute (After Imputation)
                   Missing Count  Missing %
long_commute_2020              1       0.03
long_commute_2021              1       0.03
long_commute_2022              1       0.03
long_commute_2023              1       0.03
long_commute_2024              1       0.03

,FIPS,State,County,long_commute_2020,long_commute_2021,long_commute_2022,long_commute_2023,long_commute_2024,long_commute_mean
0,00000,US,United States,0.360,0.366,0.366,0.365,0.364,0.3642
1,01000,AL,Alabama,0.343,0.346,0.352,0.350,0.352,0.3486
2,01001,AL,Autauga County,0.396,0.383,0.405,0.416,0.429,0.4058
3,01003,AL,Baldwin County,0.417,0.404,0.379,0.376,0.379,0.3910
4,01005,AL,Barbour County,0.322,0.309,0.368,0.365,0.367,0.3462

üßÆ Methodology: Long Commute ‚Äì Driving Alone raw value

The Long Commute - Driving Alone raw value represents the proportion of workers who commute alone and travel long distances (typically over 30 minutes) to work.

It is calculated using:
	‚Ä¢	Numerator: Number of solo drivers with long commutes
	‚Ä¢	Denominator: Total commuting workforce

Values range from 0 (0%) to 1 (100%) and reflect transportation patterns, accessibility, and spatial planning factors.

Data Note:
Less than 0.5% of county-level values were missing. These were filled using the average value for the relevant state in the corresponding year to ensure consistency across the dataset.

In [39]:
# ==========================================================
# PART 10A: Load Driving Alone to Work (Numerator) and Report Missing
# ==========================================================

def load_drive_alone_numerator(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Column name variants
    target_cols = [
        "driving alone to work numerator",
        "Driving alone to work numerator",
        "Driving Alone to Work numerator"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'drive_alone_numerator_{year}'

    # Base columns check
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
drive_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_drive_alone_numerator(file_path, year)
    drive_dfs.append(df)

# üß© Merge all years
drive_alone = drive_dfs[0]
for df in drive_dfs[1:]:
    drive_alone = pd.merge(drive_alone, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values
drive_cols = [f'drive_alone_numerator_{y}' for y in range(2020, 2025)]
drive_alone[drive_cols] = drive_alone[drive_cols].apply(pd.to_numeric, errors='coerce')

# üìã Report missing values
missing_report_drive = pd.DataFrame({
    "Missing Count": drive_alone[drive_cols].isna().sum(),
    "Missing %": (drive_alone[drive_cols].isna().sum() / len(drive_alone) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Driving Alone to Work - Numerator)")
print(missing_report_drive)

# üîç Show rows with any missing
rows_with_na_drive = drive_alone[drive_alone[drive_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_drive)}")
rows_with_na_drive.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Driving Alone to Work - Numerator)
                            Missing Count  Missing %
drive_alone_numerator_2020              5       0.16
drive_alone_numerator_2021              4       0.13
drive_alone_numerator_2022              5       0.16
drive_alone_numerator_2023              4       0.13
drive_alone_numerator_2024              3       0.09

üîç Rows with missing values: 8

,FIPS,State,County,drive_alone_numerator_2020,drive_alone_numerator_2021,drive_alone_numerator_2022,drive_alone_numerator_2023,drive_alone_numerator_2024
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,2293.0
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,713.0
97,02261,AK,Valdez-Cordova Census Area,3081.0,2975.0,3186.0,3095.0,NaN
563,15005,HI,Kalawao County,18.0,18.0,NaN,19.0,20.0
1164,22059,LA,La Salle Parish,3937.0,4022.0,4369.0,NaN,NaN

In [40]:
# ==========================================================
# PART 10B: Impute Driving Alone to Work (Numerator)
# ==========================================================

# üéØ Define target columns
drive_cols = [f'drive_alone_numerator_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-wise yearly means
states = drive_alone['State'].unique()
for state in states:
    state_data = drive_alone[drive_alone['State'] == state]
    for col in drive_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (drive_alone['State'] == state) & (drive_alone[col].isna())
        drive_alone.loc[missing_mask, col] = year_mean

# üîÅ Ensure all values are numeric after imputation
drive_alone[drive_cols] = drive_alone[drive_cols].apply(pd.to_numeric, errors='coerce')

# üìã Final missing value report
missing_report_final_drive = pd.DataFrame({
    "Missing Count": drive_alone[drive_cols].isna().sum(),
    "Missing %": (drive_alone[drive_cols].isna().sum() / len(drive_alone) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Driving Alone to Work (Numerator)")
print(missing_report_final_drive)

# üëÄ Preview updated data
drive_alone.head()

üìã Final Missing Value Report: Driving Alone to Work (Numerator)
                            Missing Count  Missing %
drive_alone_numerator_2020              1       0.03
drive_alone_numerator_2021              1       0.03
drive_alone_numerator_2022              1       0.03
drive_alone_numerator_2023              1       0.03
drive_alone_numerator_2024              1       0.03

,FIPS,State,County,drive_alone_numerator_2020,drive_alone_numerator_2021,drive_alone_numerator_2022,drive_alone_numerator_2023,drive_alone_numerator_2024
0,00000,US,United States,11509576.0,116584507.0,115127720.0,113724271.0,112314702.0
1,01000,AL,Alabama,1760032.0,1776620.0,1778257.0,1798537.0,1808631.0
2,01001,AL,Autauga County,21136.0,21134.0,21633.0,22860.0,23092.0
3,01003,AL,Baldwin County,77051.0,78015.0,80588.0,83559.0,86118.0
4,01005,AL,Barbour County,7118.0,6759.0,7189.0,7033.0,6844.0

üßÆ Driving Alone to Work ‚Äì Methodology & Interpretation

This indicator shows the share of workers who drive alone to work, based on:
	‚Ä¢	Numerator: Solo car commuters
	‚Ä¢	Denominator: Total commuters

Values range from 0 (no one drives alone) to 1 (everyone drives alone).

Why it matters:
It reflects car dependency, access to public transit, and urban design quality.
Higher values suggest limited alternatives to driving, more emissions, and potential equity concerns.

Data Note:
Less than 1% of values were missing and were imputed using state averages for consistency.

In [42]:
# ==========================================================
# PART 11A: Load Traffic Volume and Report Missing
# ==========================================================

def load_traffic_volume_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Target column options
    target_cols = [
        "traffic volume raw value",
        "Traffic volume raw value",
        "Traffic Volume raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'traffic_volume_{year}'

    # Check required ID columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
traffic_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_traffic_volume_column(file_path, year)
    traffic_dfs.append(df)

# üß© Merge datasets
traffic_volume = traffic_dfs[0]
for df in traffic_dfs[1:]:
    traffic_volume = pd.merge(traffic_volume, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert and calculate pre-imputation mean
traffic_cols = [f'traffic_volume_{y}' for y in range(2020, 2025)]
traffic_volume[traffic_cols] = traffic_volume[traffic_cols].apply(pd.to_numeric, errors='coerce')
traffic_volume['traffic_volume_mean'] = traffic_volume[traffic_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_traffic = pd.DataFrame({
    "Missing Count": traffic_volume[traffic_cols].isna().sum(),
    "Missing %": (traffic_volume[traffic_cols].isna().sum() / len(traffic_volume) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Traffic Volume, Before Imputation)")
print(missing_report_traffic)

# üîç Show rows with any missing values
rows_with_na_traffic = traffic_volume[traffic_volume[traffic_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_traffic)}")
rows_with_na_traffic.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Traffic Volume, Before Imputation)
                     Missing Count  Missing %
traffic_volume_2020              5       0.16
traffic_volume_2021              5       0.16
traffic_volume_2022              4       0.13
traffic_volume_2023            157       4.91
traffic_volume_2024             34       1.06

üîç Rows with missing values: 161

,FIPS,State,County,traffic_volume_2020,traffic_volume_2021,traffic_volume_2022,traffic_volume_2023,traffic_volume_2024,traffic_volume_mean
0,00000,US,United States,NaN,NaN,394.719953,505.31,107.616657,335.882203
15,01027,AL,Clay County,37.230490,0.0,0.000000,NaN,2.560767,9.947814
39,01075,AL,Lamar County,28.620643,0.0,0.000000,NaN,6.114009,8.683663
70,02013,AK,Aleutians East Borough,0.000000,0.0,0.000000,NaN,NaN,0.000000
71,02016,AK,Aleutians West Census Area,0.000000,0.0,0.000000,NaN,NaN,0.000000

In [43]:
# ==========================================================
# PART 11B: Impute and Recalculate Traffic Volume
# ==========================================================

# üéØ Columns to impute
traffic_cols = [f'traffic_volume_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-level mean for each year
states = traffic_volume['State'].unique()
for state in states:
    state_data = traffic_volume[traffic_volume['State'] == state]
    for col in traffic_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (traffic_volume['State'] == state) & (traffic_volume[col].isna())
        traffic_volume.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
traffic_volume[traffic_cols] = traffic_volume[traffic_cols].apply(pd.to_numeric, errors='coerce')
traffic_volume['traffic_volume_mean'] = traffic_volume[traffic_cols].mean(axis=1, skipna=True)

# üìã Final missing report
missing_report_final_traffic = pd.DataFrame({
    "Missing Count": traffic_volume[traffic_cols].isna().sum(),
    "Missing %": (traffic_volume[traffic_cols].isna().sum() / len(traffic_volume) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Traffic Volume (After Imputation)")
print(missing_report_final_traffic)

# üëÄ Preview
traffic_volume.head()

üìã Final Missing Value Report: Traffic Volume (After Imputation)
                     Missing Count  Missing %
traffic_volume_2020              2       0.06
traffic_volume_2021              2       0.06
traffic_volume_2022              1       0.03
traffic_volume_2023              1       0.03
traffic_volume_2024              1       0.03

,FIPS,State,County,traffic_volume_2020,traffic_volume_2021,traffic_volume_2022,traffic_volume_2023,traffic_volume_2024,traffic_volume_mean
0,00000,US,United States,NaN,NaN,394.719953,505.310000,107.616657,335.882203
1,01000,AL,Alabama,166.008472,219.909377,219.909377,213.692827,67.328709,177.369752
2,01001,AL,Autauga County,88.457040,155.095523,155.095523,151.930170,46.473848,119.410421
3,01003,AL,Baldwin County,86.997430,133.604842,133.604842,133.377260,39.068067,105.330488
4,01005,AL,Barbour County,102.291762,102.459673,102.459673,100.064410,34.405649,88.336233

üßÆ Traffic Volume ‚Äì What the Numbers Mean

The Traffic Volume raw value represents the average number of vehicles (in thousands) passing through major roads in a county each day, measured annually.
	‚Ä¢	A value of 100 means roughly 100,000 vehicles per day
	‚Ä¢	Higher numbers reflect heavier traffic flow, typically in urban or transit-heavy regions
	‚Ä¢	Lower numbers indicate lighter traffic, often found in rural or less-developed areas

Data Note:
The data is reported consistently across most counties. Only 4.91% of 2023 values were missing and were imputed using state averages to maintain a balanced 5-year mean.

In [45]:
# ==========================================================
# PART 12A: Load Severe Housing Cost Burden and Report Missing
# ==========================================================

def load_severe_housing_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Target column name variations
    target_cols = [
        "severe housing cost burden raw value",
        "Severe housing cost burden raw value",
        "Severe Housing Cost Burden raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'severe_housing_cost_{year}'

    # Validate columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
housing_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_severe_housing_column(file_path, year)
    housing_dfs.append(df)

# üß© Merge all into one DataFrame
severe_housing = housing_dfs[0]
for df in housing_dfs[1:]:
    severe_housing = pd.merge(severe_housing, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert and calculate pre-imputation mean
housing_cols = [f'severe_housing_cost_{y}' for y in range(2020, 2025)]
severe_housing[housing_cols] = severe_housing[housing_cols].apply(pd.to_numeric, errors='coerce')
severe_housing['severe_housing_cost_mean'] = severe_housing[housing_cols].mean(axis=1, skipna=True)

# üìã Report missing
missing_report_housing = pd.DataFrame({
    "Missing Count": severe_housing[housing_cols].isna().sum(),
    "Missing %": (severe_housing[housing_cols].isna().sum() / len(severe_housing) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Severe Housing Cost Burden, Before Imputation)")
print(missing_report_housing)

# üîç Show rows with any missing values
rows_with_na_housing = severe_housing[severe_housing[housing_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_housing)}")
rows_with_na_housing.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Severe Housing Cost Burden, Before Imputation)
                          Missing Count  Missing %
severe_housing_cost_2020              8       0.25
severe_housing_cost_2021              7       0.22
severe_housing_cost_2022              8       0.25
severe_housing_cost_2023              9       0.28
severe_housing_cost_2024              8       0.25

üîç Rows with missing values: 14

,FIPS,State,County,severe_housing_cost_2020,severe_housing_cost_2021,severe_housing_cost_2022,severe_housing_cost_2023,severe_housing_cost_2024,severe_housing_cost_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.06177,0.061770
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.06143,0.061430
97,02261,AK,Valdez-Cordova Census Area,0.075077,0.062521,0.063909,0.045872,NaN,0.061844
563,15005,HI,Kalawao County,NaN,NaN,NaN,NaN,NaN,NaN
1001,20187,KS,Stanton County,0.087866,0.055728,0.047872,0.038158,NaN,0.057406

In [46]:
# ==========================================================
# PART 12B: Impute and Recalculate Severe Housing Cost Burden
# ==========================================================

# üéØ Columns to work with
housing_cols = [f'severe_housing_cost_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-level means
states = severe_housing['State'].unique()
for state in states:
    state_data = severe_housing[severe_housing['State'] == state]
    for col in housing_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (severe_housing['State'] == state) & (severe_housing[col].isna())
        severe_housing.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
severe_housing[housing_cols] = severe_housing[housing_cols].apply(pd.to_numeric, errors='coerce')
severe_housing['severe_housing_cost_mean'] = severe_housing[housing_cols].mean(axis=1, skipna=True)

# üìã Final missing report
missing_report_final_housing = pd.DataFrame({
    "Missing Count": severe_housing[housing_cols].isna().sum(),
    "Missing %": (severe_housing[housing_cols].isna().sum() / len(severe_housing) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Severe Housing Cost Burden (After Imputation)")
print(missing_report_final_housing)

# üëÄ Preview
severe_housing.head()

üìã Final Missing Value Report: Severe Housing Cost Burden (After Imputation)
                          Missing Count  Missing %
severe_housing_cost_2020              1       0.03
severe_housing_cost_2021              1       0.03
severe_housing_cost_2022              1       0.03
severe_housing_cost_2023              1       0.03
severe_housing_cost_2024              1       0.03

,FIPS,State,County,severe_housing_cost_2020,severe_housing_cost_2021,severe_housing_cost_2022,severe_housing_cost_2023,severe_housing_cost_2024,severe_housing_cost_mean
0,00000,US,United States,0.148465,0.144374,0.141902,0.142757,0.144915,0.144483
1,01000,AL,Alabama,0.126538,0.120578,0.118997,0.119442,0.122664,0.121644
2,01001,AL,Autauga County,0.134035,0.133759,0.138328,0.127533,0.112794,0.129290
3,01003,AL,Baldwin County,0.117258,0.111740,0.114508,0.109629,0.123019,0.115231
4,01005,AL,Barbour County,0.140595,0.142707,0.123855,0.102180,0.107663,0.123400

üßæ Interpreting Severe Housing Cost Burden raw value

The Severe housing cost burden raw value represents the proportion of households in a county that spend more than 50% of their income on housing (including rent or mortgage + utilities).
	‚Ä¢	Values range from 0 to 1
	‚Ä¢	For example, 0.13 = 13% of households are severely cost-burdened
	‚Ä¢	Higher values indicate greater financial stress on households
	‚Ä¢	Lower values suggest more affordable housing conditions

In [48]:
# ==========================================================
# PART 13A: Load Lack of Kitchen or Plumbing Facilities and Report Missing
# ==========================================================

def load_housing_facilities_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "percentage of households with lack of kitchen or plumbing facilities",
        "Percentage of households with lack of kitchen or plumbing facilities",
        "Percentage of Households with Lack of Kitchen or Plumbing Facilities"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'housing_facility_lack_{year}'

    # Check core columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
facilities_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_housing_facilities_column(file_path, year)
    facilities_dfs.append(df)

# üß© Merge all years
housing_facilities = facilities_dfs[0]
for df in facilities_dfs[1:]:
    housing_facilities = pd.merge(housing_facilities, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert and calculate pre-imputation mean
facility_cols = [f'housing_facility_lack_{y}' for y in range(2020, 2025)]
housing_facilities[facility_cols] = housing_facilities[facility_cols].apply(pd.to_numeric, errors='coerce')
housing_facilities['housing_facility_lack_mean'] = housing_facilities[facility_cols].mean(axis=1, skipna=True)

# üìã Missing value report
missing_report_facility = pd.DataFrame({
    "Missing Count": housing_facilities[facility_cols].isna().sum(),
    "Missing %": (housing_facilities[facility_cols].isna().sum() / len(housing_facilities) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Lack of Kitchen or Plumbing, Before Imputation)")
print(missing_report_facility)

# üîç Show missing rows
rows_with_na_facility = housing_facilities[housing_facilities[facility_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_facility)}")
rows_with_na_facility.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Lack of Kitchen or Plumbing, Before Imputation)
                            Missing Count  Missing %
housing_facility_lack_2020             55       1.72
housing_facility_lack_2021              4       0.13
housing_facility_lack_2022              4       0.13
housing_facility_lack_2023              4       0.13
housing_facility_lack_2024              3       0.09

üîç Rows with missing values: 57

,FIPS,State,County,housing_facility_lack_2020,housing_facility_lack_2021,housing_facility_lack_2022,housing_facility_lack_2023,housing_facility_lack_2024,housing_facility_lack_mean
0,00000,US,United States,NaN,0.009961,0.009961,0.009955,0.009881,0.009939
1,01000,AL,Alabama,NaN,0.008017,0.008238,0.008279,0.008565,0.008275
69,02000,AK,Alaska,NaN,0.045439,0.047108,0.044998,0.042226,0.044943
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.017316,0.017316
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.079812,0.079812

In [49]:
# ==========================================================
# PART 13B: Impute and Recalculate Lack of Kitchen or Plumbing Facilities
# ==========================================================

# üéØ Columns to impute
facility_cols = [f'housing_facility_lack_{y}' for y in range(2020, 2025)]

# üßº Impute missing values with state-wise means for each year
states = housing_facilities['State'].unique()
for state in states:
    state_data = housing_facilities[housing_facilities['State'] == state]
    for col in facility_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (housing_facilities['State'] == state) & (housing_facilities[col].isna())
        housing_facilities.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
housing_facilities[facility_cols] = housing_facilities[facility_cols].apply(pd.to_numeric, errors='coerce')
housing_facilities['housing_facility_lack_mean'] = housing_facilities[facility_cols].mean(axis=1, skipna=True)

# üìã Final missing report
missing_report_final_facility = pd.DataFrame({
    "Missing Count": housing_facilities[facility_cols].isna().sum(),
    "Missing %": (housing_facilities[facility_cols].isna().sum() / len(housing_facilities) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Lack of Kitchen or Plumbing (After Imputation)")
print(missing_report_final_facility)

# üëÄ Preview
housing_facilities.head()

üìã Final Missing Value Report: Lack of Kitchen or Plumbing (After Imputation)
                            Missing Count  Missing %
housing_facility_lack_2020              2       0.06
housing_facility_lack_2021              1       0.03
housing_facility_lack_2022              1       0.03
housing_facility_lack_2023              1       0.03
housing_facility_lack_2024              1       0.03

,FIPS,State,County,housing_facility_lack_2020,housing_facility_lack_2021,housing_facility_lack_2022,housing_facility_lack_2023,housing_facility_lack_2024,housing_facility_lack_mean
0,00000,US,United States,NaN,0.009961,0.009961,0.009955,0.009881,0.009939
1,01000,AL,Alabama,0.010170,0.008017,0.008238,0.008279,0.008565,0.008654
2,01001,AL,Autauga County,0.013462,0.015436,0.016339,0.016359,0.015770,0.015473
3,01003,AL,Baldwin County,0.004790,0.003349,0.005024,0.006425,0.006366,0.005191
4,01005,AL,Barbour County,0.006031,0.006529,0.004355,0.005886,0.005365,0.005633

üßæ Interpreting Lack of Kitchen or Plumbing Facilities

This indicator shows the proportion of households in each county that lack access to basic housing infrastructure ‚Äî either a kitchen, plumbing, or both.
	‚Ä¢	Values are between 0 and 1, where:
	‚Ä¢	0.01 = 1% of households lack adequate facilities
	‚Ä¢	Lower is better ‚Äî closer to 0 means better housing conditions

In [51]:
# ==========================================================
# PART 14A: Load High Housing Cost Burden and Report Missing
# ==========================================================

def load_high_housing_cost_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Target column variations
    target_cols = [
        "percentage of households with high housing costs",
        "Percentage of households with high housing costs",
        "Percentage of Households with High Housing Costs"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'high_housing_cost_{year}'

    # Check ID columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
highcost_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_high_housing_cost_column(file_path, year)
    highcost_dfs.append(df)

# üß© Merge all years
high_housing_cost = highcost_dfs[0]
for df in highcost_dfs[1:]:
    high_housing_cost = pd.merge(high_housing_cost, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
highcost_cols = [f'high_housing_cost_{y}' for y in range(2020, 2025)]
high_housing_cost[highcost_cols] = high_housing_cost[highcost_cols].apply(pd.to_numeric, errors='coerce')
high_housing_cost['high_housing_cost_mean'] = high_housing_cost[highcost_cols].mean(axis=1, skipna=True)

# üìã Report missing
missing_report_highcost = pd.DataFrame({
    "Missing Count": high_housing_cost[highcost_cols].isna().sum(),
    "Missing %": (high_housing_cost[highcost_cols].isna().sum() / len(high_housing_cost) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (High Housing Costs, Before Imputation)")
print(missing_report_highcost)

# üîç Show rows with missing values
rows_with_na_highcost = high_housing_cost[high_housing_cost[highcost_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_highcost)}")
rows_with_na_highcost.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (High Housing Costs, Before Imputation)
                        Missing Count  Missing %
high_housing_cost_2020             55       1.72
high_housing_cost_2021              4       0.13
high_housing_cost_2022              4       0.13
high_housing_cost_2023              4       0.13
high_housing_cost_2024              3       0.09

üîç Rows with missing values: 57

,FIPS,State,County,high_housing_cost_2020,high_housing_cost_2021,high_housing_cost_2022,high_housing_cost_2023,high_housing_cost_2024,high_housing_cost_mean
0,00000,US,United States,NaN,0.143991,0.141358,0.137489,0.135222,0.139515
1,01000,AL,Alabama,NaN,0.121069,0.118505,0.112969,0.111702,0.116061
69,02000,AK,Alaska,NaN,0.115877,0.116309,0.114885,0.110030,0.114275
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.049351,0.049351
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.093308,0.093308

In [52]:
# ==========================================================
# PART 14B: Impute and Recalculate High Housing Cost Burden
# ==========================================================

# üéØ Define columns to impute
highcost_cols = [f'high_housing_cost_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-level mean per year
states = high_housing_cost['State'].unique()
for state in states:
    state_data = high_housing_cost[high_housing_cost['State'] == state]
    for col in highcost_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (high_housing_cost['State'] == state) & (high_housing_cost[col].isna())
        high_housing_cost.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
high_housing_cost[highcost_cols] = high_housing_cost[highcost_cols].apply(pd.to_numeric, errors='coerce')
high_housing_cost['high_housing_cost_mean'] = high_housing_cost[highcost_cols].mean(axis=1, skipna=True)

# üìã Final missing report
missing_report_final_highcost = pd.DataFrame({
    "Missing Count": high_housing_cost[highcost_cols].isna().sum(),
    "Missing %": (high_housing_cost[highcost_cols].isna().sum() / len(high_housing_cost) * 100).round(2)
})
print("\nüìã Final Missing Value Report: High Housing Costs (After Imputation)")
print(missing_report_final_highcost)

# üëÄ Preview
high_housing_cost.head()

üìã Final Missing Value Report: High Housing Costs (After Imputation)
                        Missing Count  Missing %
high_housing_cost_2020              2       0.06
high_housing_cost_2021              1       0.03
high_housing_cost_2022              1       0.03
high_housing_cost_2023              1       0.03
high_housing_cost_2024              1       0.03

,FIPS,State,County,high_housing_cost_2020,high_housing_cost_2021,high_housing_cost_2022,high_housing_cost_2023,high_housing_cost_2024,high_housing_cost_mean
0,00000,US,United States,NaN,0.143991,0.141358,0.137489,0.135222,0.139515
1,01000,AL,Alabama,0.118496,0.121069,0.118505,0.112969,0.111702,0.116548
2,01001,AL,Autauga County,0.128267,0.120326,0.127164,0.126358,0.132084,0.126840
3,01003,AL,Baldwin County,0.122774,0.119875,0.109863,0.105611,0.105648,0.112754
4,01005,AL,Barbour County,0.134459,0.125943,0.132353,0.134643,0.116836,0.128847

üßæ Interpreting High Housing Cost Burden raw value

This value represents the proportion of households spending more than 30% of their income on housing ‚Äî a common threshold for affordability.
	‚Ä¢	Ranges from 0 to 1, where:
	‚Ä¢	0.12 = 12% of households face high housing costs
	‚Ä¢	Higher values = greater affordability pressure
	‚Ä¢	This includes both owners and renters

üìå What it shows:
	‚Ä¢	Reflects housing affordability challenges
	‚Ä¢	Useful for understanding cost of living stress in a county
	‚Ä¢	Often higher in urban areas or economically strained regions

In [54]:
# ==========================================================
# PART 15A: Load Severe Housing Problems and Report Missing
# ==========================================================

def load_severe_housing_problems_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Target column name options
    target_cols = [
        "severe housing problems raw value",
        "Severe housing problems raw value",
        "Severe Housing Problems raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'severe_housing_problems_{year}'

    # Validate base columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
problems_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_severe_housing_problems_column(file_path, year)
    problems_dfs.append(df)

# üß© Merge across years
severe_housing_problems = problems_dfs[0]
for df in problems_dfs[1:]:
    severe_housing_problems = pd.merge(severe_housing_problems, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert and calculate raw mean
problem_cols = [f'severe_housing_problems_{y}' for y in range(2020, 2025)]
severe_housing_problems[problem_cols] = severe_housing_problems[problem_cols].apply(pd.to_numeric, errors='coerce')
severe_housing_problems['severe_housing_problems_mean'] = severe_housing_problems[problem_cols].mean(axis=1, skipna=True)

# üìã Missing value report
missing_report_problems = pd.DataFrame({
    "Missing Count": severe_housing_problems[problem_cols].isna().sum(),
    "Missing %": (severe_housing_problems[problem_cols].isna().sum() / len(severe_housing_problems) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Severe Housing Problems, Before Imputation)")
print(missing_report_problems)

# üîç Show missing rows
rows_with_na_problems = severe_housing_problems[severe_housing_problems[problem_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_problems)}")
rows_with_na_problems.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Severe Housing Problems, Before Imputation)
                              Missing Count  Missing %
severe_housing_problems_2020              4       0.13
severe_housing_problems_2021              4       0.13
severe_housing_problems_2022              4       0.13
severe_housing_problems_2023              4       0.13
severe_housing_problems_2024              3       0.09

üîç Rows with missing values: 6

,FIPS,State,County,severe_housing_problems_2020,severe_housing_problems_2021,severe_housing_problems_2022,severe_housing_problems_2023,severe_housing_problems_2024,severe_housing_problems_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.101732,0.101732
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.201878,0.201878
97,02261,AK,Valdez-Cordova Census Area,0.195911,0.150877,0.142165,0.137008,NaN,0.156490
1164,22059,LA,La Salle Parish,0.102444,0.111992,0.118526,NaN,NaN,0.110987
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,0.139148,0.146817,0.142983

In [55]:
# ==========================================================
# PART 15B: Impute and Recalculate Severe Housing Problems
# ==========================================================

# üéØ Columns to impute
problem_cols = [f'severe_housing_problems_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-level mean per year
states = severe_housing_problems['State'].unique()
for state in states:
    state_data = severe_housing_problems[severe_housing_problems['State'] == state]
    for col in problem_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (severe_housing_problems['State'] == state) & (severe_housing_problems[col].isna())
        severe_housing_problems.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
severe_housing_problems[problem_cols] = severe_housing_problems[problem_cols].apply(pd.to_numeric, errors='coerce')
severe_housing_problems['severe_housing_problems_mean'] = severe_housing_problems[problem_cols].mean(axis=1, skipna=True)

# üìã Final missing report
missing_report_final_problems = pd.DataFrame({
    "Missing Count": severe_housing_problems[problem_cols].isna().sum(),
    "Missing %": (severe_housing_problems[problem_cols].isna().sum() / len(severe_housing_problems) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Severe Housing Problems (After Imputation)")
print(missing_report_final_problems)

# üëÄ Preview
severe_housing_problems.head()

üìã Final Missing Value Report: Severe Housing Problems (After Imputation)
                              Missing Count  Missing %
severe_housing_problems_2020              1       0.03
severe_housing_problems_2021              1       0.03
severe_housing_problems_2022              1       0.03
severe_housing_problems_2023              1       0.03
severe_housing_problems_2024              1       0.03

,FIPS,State,County,severe_housing_problems_2020,severe_housing_problems_2021,severe_housing_problems_2022,severe_housing_problems_2023,severe_housing_problems_2024,severe_housing_problems_mean
0,00000,US,United States,0.179136,0.175431,0.173139,0.169672,0.167389,0.172953
1,01000,AL,Alabama,0.143407,0.138817,0.136859,0.131568,0.130812,0.136293
2,01001,AL,Autauga County,0.146635,0.136310,0.147289,0.144426,0.153757,0.145683
3,01003,AL,Baldwin County,0.135662,0.129967,0.124205,0.122390,0.124279,0.127300
4,01005,AL,Barbour County,0.145833,0.137106,0.154600,0.162119,0.150751,0.150082

üßæ Interpreting Severe Housing Problems raw value

The Severe Housing Problems raw value represents the percentage of households in a county facing severe housing issues. This includes:
	‚Ä¢	Lack of complete plumbing or kitchen facilities
	‚Ä¢	Overcrowding
	‚Ä¢	High housing cost burden (spending over 50% of income on housing)

The values are proportions between 0 and 1:
	‚Ä¢	0.17 = 17% of households face at least one severe housing problem
	‚Ä¢	Higher values indicate a higher proportion of the population facing housing challenges

This metric is useful for understanding housing instability, poverty, and community development needs. Higher values suggest that targeted interventions are necessary to address housing quality and affordability issues.

In [57]:
# ==========================================================
# PART 16A: Load Homeownership and Report Missing
# ==========================================================

def load_homeownership_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Target column variations
    target_cols = [
        "homeownership raw value",
        "Homeownership raw value",
        "Homeownership Rate raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'homeownership_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
homeownership_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_homeownership_column(file_path, year)
    homeownership_dfs.append(df)

# üß© Merge data for all years
homeownership = homeownership_dfs[0]
for df in homeownership_dfs[1:]:
    homeownership = pd.merge(homeownership, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert and calculate pre-imputation mean
homeownership_cols = [f'homeownership_{y}' for y in range(2020, 2025)]
homeownership[homeownership_cols] = homeownership[homeownership_cols].apply(pd.to_numeric, errors='coerce')
homeownership['homeownership_mean'] = homeownership[homeownership_cols].mean(axis=1, skipna=True)

# üìã Missing value report
missing_report_homeownership = pd.DataFrame({
    "Missing Count": homeownership[homeownership_cols].isna().sum(),
    "Missing %": (homeownership[homeownership_cols].isna().sum() / len(homeownership) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Homeownership, Before Imputation)")
print(missing_report_homeownership)

# üîç Show rows with missing values
rows_with_na_homeownership = homeownership[homeownership[homeownership_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_homeownership)}")
rows_with_na_homeownership.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Homeownership, Before Imputation)
                    Missing Count  Missing %
homeownership_2020              4       0.13
homeownership_2021              4       0.13
homeownership_2022              4       0.13
homeownership_2023              4       0.13
homeownership_2024              3       0.09

üîç Rows with missing values: 6

,FIPS,State,County,homeownership_2020,homeownership_2021,homeownership_2022,homeownership_2023,homeownership_2024,homeownership_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.626134,0.626134
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.688073,0.688073
97,02261,AK,Valdez-Cordova Census Area,0.731005,0.746302,0.740291,0.697569,NaN,0.728792
1164,22059,LA,La Salle Parish,0.750299,0.765891,0.837099,NaN,NaN,0.784430
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,0.828370,0.830654,0.829512

In [58]:
# ==========================================================
# PART 16B: Impute and Recalculate Homeownership
# ==========================================================

# üéØ Columns to impute
homeownership_cols = [f'homeownership_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-level mean per year
states = homeownership['State'].unique()
for state in states:
    state_data = homeownership[homeownership['State'] == state]
    for col in homeownership_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (homeownership['State'] == state) & (homeownership[col].isna())
        homeownership.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
homeownership[homeownership_cols] = homeownership[homeownership_cols].apply(pd.to_numeric, errors='coerce')
homeownership['homeownership_mean'] = homeownership[homeownership_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_homeownership = pd.DataFrame({
    "Missing Count": homeownership[homeownership_cols].isna().sum(),
    "Missing %": (homeownership[homeownership_cols].isna().sum() / len(homeownership) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Homeownership (After Imputation)")
print(missing_report_final_homeownership)

# üëÄ Preview
homeownership.head()

üìã Final Missing Value Report: Homeownership (After Imputation)
                    Missing Count  Missing %
homeownership_2020              1       0.03
homeownership_2021              1       0.03
homeownership_2022              1       0.03
homeownership_2023              1       0.03
homeownership_2024              1       0.03

,FIPS,State,County,homeownership_2020,homeownership_2021,homeownership_2022,homeownership_2023,homeownership_2024,homeownership_mean
0,00000,US,United States,0.638476,0.639921,0.644043,0.646331,0.648164,0.643387
1,01000,AL,Alabama,0.685505,0.687806,0.691820,0.693948,0.697200,0.691256
2,01001,AL,Autauga County,0.748946,0.732906,0.746231,0.742451,0.754528,0.745012
3,01003,AL,Baldwin County,0.736193,0.752453,0.769998,0.771212,0.778705,0.761712
4,01005,AL,Barbour County,0.613978,0.608989,0.619502,0.622139,0.649734,0.622868

The Homeownership raw value represents the proportion of households in a county that own their homes.
	‚Ä¢	Values range from 0 to 1, where:
	‚Ä¢	0.64 = 64% of households are homeowners
	‚Ä¢	Higher values indicate greater homeownership rates, typically seen in suburban or rural areas with more affordable housing
	‚Ä¢	Lower values indicate lower homeownership, which may be common in high-cost urban areas or regions with more renters

In [60]:
# ==========================================================
# PART 17A: Load Unemployment and Report Missing
# ==========================================================

def load_unemployment_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "unemployment raw value",
        "Unemployment raw value",
        "Unemployment Rate raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'unemployment_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
unemployment_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_unemployment_column(file_path, year)
    unemployment_dfs.append(df)

# üß© Merge all years
unemployment = unemployment_dfs[0]
for df in unemployment_dfs[1:]:
    unemployment = pd.merge(unemployment, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert and calculate pre-imputation mean
unemployment_cols = [f'unemployment_{y}' for y in range(2020, 2025)]
unemployment[unemployment_cols] = unemployment[unemployment_cols].apply(pd.to_numeric, errors='coerce')
unemployment['unemployment_mean'] = unemployment[unemployment_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_unemployment = pd.DataFrame({
    "Missing Count": unemployment[unemployment_cols].isna().sum(),
    "Missing %": (unemployment[unemployment_cols].isna().sum() / len(unemployment) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Unemployment, Before Imputation)")
print(missing_report_unemployment)

# üîç Show rows with missing values
rows_with_na_unemployment = unemployment[unemployment[unemployment_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_unemployment)}")
rows_with_na_unemployment.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Unemployment, Before Imputation)
                   Missing Count  Missing %
unemployment_2020              5       0.16
unemployment_2021              5       0.16
unemployment_2022              5       0.16
unemployment_2023              5       0.16
unemployment_2024              4       0.13

üîç Rows with missing values: 7

,FIPS,State,County,unemployment_2020,unemployment_2021,unemployment_2022,unemployment_2023,unemployment_2024,unemployment_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.028639,0.028639
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.092527,0.092527
97,02261,AK,Valdez-Cordova Census Area,0.074448,0.075389,0.087351,0.073616,NaN,0.077701
563,15005,HI,Kalawao County,NaN,NaN,NaN,NaN,NaN,NaN
1164,22059,LA,La Salle Parish,0.043886,0.042591,0.047454,NaN,NaN,0.044644

In [61]:
# ==========================================================
# PART 17B: Impute and Recalculate Unemployment
# ==========================================================

# üéØ Define columns to impute
unemployment_cols = [f'unemployment_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-level means for each year
states = unemployment['State'].unique()
for state in states:
    state_data = unemployment[unemployment['State'] == state]
    for col in unemployment_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (unemployment['State'] == state) & (unemployment[col].isna())
        unemployment.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
unemployment[unemployment_cols] = unemployment[unemployment_cols].apply(pd.to_numeric, errors='coerce')
unemployment['unemployment_mean'] = unemployment[unemployment_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_unemployment = pd.DataFrame({
    "Missing Count": unemployment[unemployment_cols].isna().sum(),
    "Missing %": (unemployment[unemployment_cols].isna().sum() / len(unemployment) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Unemployment (After Imputation)")
print(missing_report_final_unemployment)

# üëÄ Preview
unemployment.head()

üìã Final Missing Value Report: Unemployment (After Imputation)
                   Missing Count  Missing %
unemployment_2020              1       0.03
unemployment_2021              1       0.03
unemployment_2022              1       0.03
unemployment_2023              1       0.03
unemployment_2024              1       0.03

,FIPS,State,County,unemployment_2020,unemployment_2021,unemployment_2022,unemployment_2023,unemployment_2024,unemployment_mean
0,00000,US,United States,0.038953,0.036694,0.080529,0.053529,0.036501,0.049241
1,01000,AL,Alabama,0.039336,0.030006,0.058770,0.034390,0.025968,0.037694
2,01001,AL,Autauga County,0.036291,0.027281,0.048843,0.028169,0.022696,0.032656
3,01003,AL,Baldwin County,0.036154,0.027258,0.056065,0.029630,0.023500,0.034521
4,01005,AL,Barbour County,0.051714,0.037952,0.070455,0.057216,0.040650,0.051598

üßæ Interpreting Unemployment raw value

The Unemployment raw value represents the annual unemployment rate as a proportion of the workforce in a county. The values are expressed as percentages between 0 and 1 (e.g., 0.05 means 5% unemployment).
	‚Ä¢	0.039 = 3.9% of the workforce in 2020 was unemployed
	‚Ä¢	Higher values indicate greater unemployment rates, typically seen in economic downturns or challenging job markets
	‚Ä¢	Lower values suggest healthier employment conditions, where more people are employed

In [63]:
# ==========================================================
# PART 18A: Load Children in Poverty and Report Missing
# ==========================================================

def load_children_poverty_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "children in poverty raw value",
        "Children in poverty raw value",
        "Children in Poverty raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'children_poverty_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
poverty_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_children_poverty_column(file_path, year)
    poverty_dfs.append(df)

# üß© Merge all years
children_poverty = poverty_dfs[0]
for df in poverty_dfs[1:]:
    children_poverty = pd.merge(children_poverty, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
poverty_cols = [f'children_poverty_{y}' for y in range(2020, 2025)]
children_poverty[poverty_cols] = children_poverty[poverty_cols].apply(pd.to_numeric, errors='coerce')
children_poverty['children_poverty_mean'] = children_poverty[poverty_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_poverty = pd.DataFrame({
    "Missing Count": children_poverty[poverty_cols].isna().sum(),
    "Missing %": (children_poverty[poverty_cols].isna().sum() / len(children_poverty) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Children in Poverty, Before Imputation)")
print(missing_report_poverty)

# üîç Show rows with missing values
rows_with_na_poverty = children_poverty[children_poverty[poverty_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_poverty)}")
rows_with_na_poverty.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Children in Poverty, Before Imputation)
                       Missing Count  Missing %
children_poverty_2020              5       0.16
children_poverty_2021              5       0.16
children_poverty_2022              5       0.16
children_poverty_2023              5       0.16
children_poverty_2024              4       0.13

üîç Rows with missing values: 7

,FIPS,State,County,children_poverty_2020,children_poverty_2021,children_poverty_2022,children_poverty_2023,children_poverty_2024,children_poverty_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.078,0.078
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.196,0.196
97,02261,AK,Valdez-Cordova Census Area,0.121,0.101,0.104,0.122,NaN,0.112
563,15005,HI,Kalawao County,NaN,NaN,NaN,NaN,NaN,NaN
1164,22059,LA,La Salle Parish,0.242,0.214,0.204,NaN,NaN,0.220

In [64]:
# ==========================================================
# PART 18B: Impute and Recalculate Children in Poverty
# ==========================================================

# üéØ Columns to impute
poverty_cols = [f'children_poverty_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-level means for each year
states = children_poverty['State'].unique()
for state in states:
    state_data = children_poverty[children_poverty['State'] == state]
    for col in poverty_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (children_poverty['State'] == state) & (children_poverty[col].isna())
        children_poverty.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
children_poverty[poverty_cols] = children_poverty[poverty_cols].apply(pd.to_numeric, errors='coerce')
children_poverty['children_poverty_mean'] = children_poverty[poverty_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_poverty = pd.DataFrame({
    "Missing Count": children_poverty[poverty_cols].isna().sum(),
    "Missing %": (children_poverty[poverty_cols].isna().sum() / len(children_poverty) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Children in Poverty (After Imputation)")
print(missing_report_final_poverty)

# üëÄ Preview
children_poverty.head()

üìã Final Missing Value Report: Children in Poverty (After Imputation)
                       Missing Count  Missing %
children_poverty_2020              1       0.03
children_poverty_2021              1       0.03
children_poverty_2022              1       0.03
children_poverty_2023              1       0.03
children_poverty_2024              1       0.03

,FIPS,State,County,children_poverty_2020,children_poverty_2021,children_poverty_2022,children_poverty_2023,children_poverty_2024,children_poverty_mean
0,00000,US,United States,0.180,0.168,0.157,0.169,0.163,0.1674
1,01000,AL,Alabama,0.239,0.219,0.209,0.227,0.218,0.2224
2,01001,AL,Autauga County,0.193,0.159,0.149,0.161,0.157,0.1638
3,01003,AL,Baldwin County,0.139,0.135,0.124,0.164,0.161,0.1446
4,01005,AL,Barbour County,0.439,0.410,0.375,0.351,0.377,0.3904

üßæ Interpreting Children in Poverty raw value

The Children in Poverty raw value represents the proportion of children (under 18) living in households with income below the poverty line in each county.
	‚Ä¢	Values range from 0 to 1:
	‚Ä¢	0.18 = 18% of children in the county are in poverty
	‚Ä¢	Higher values indicate a greater proportion of children living in poverty, which often signals economic distress in a region
	‚Ä¢	Lower values suggest relatively fewer children are living below the poverty line

This metric is vital for assessing child welfare and economic conditions, particularly for targeting interventions aimed at reducing child poverty through public programs.

In [66]:
# ==========================================================
# PART 19A: Load Income Inequality and Report Missing
# ==========================================================

def load_income_inequality_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "income inequality raw value",
        "Income inequality raw value",
        "Income Inequality raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'income_inequality_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
inequality_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_income_inequality_column(file_path, year)
    inequality_dfs.append(df)

# üß© Merge all years
income_inequality = inequality_dfs[0]
for df in inequality_dfs[1:]:
    income_inequality = pd.merge(income_inequality, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
inequality_cols = [f'income_inequality_{y}' for y in range(2020, 2025)]
income_inequality[inequality_cols] = income_inequality[inequality_cols].apply(pd.to_numeric, errors='coerce')
income_inequality['income_inequality_mean'] = income_inequality[inequality_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_inequality = pd.DataFrame({
    "Missing Count": income_inequality[inequality_cols].isna().sum(),
    "Missing %": (income_inequality[inequality_cols].isna().sum() / len(income_inequality) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Income Inequality, Before Imputation)")
print(missing_report_inequality)

# üîç Show rows with missing values
rows_with_na_inequality = income_inequality[income_inequality[inequality_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_inequality)}")
rows_with_na_inequality.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Income Inequality, Before Imputation)
                        Missing Count  Missing %
income_inequality_2020              6       0.19
income_inequality_2021              5       0.16
income_inequality_2022             10       0.31
income_inequality_2023             11       0.34
income_inequality_2024             18       0.56

üîç Rows with missing values: 23

,FIPS,State,County,income_inequality_2020,income_inequality_2021,income_inequality_2022,income_inequality_2023,income_inequality_2024,income_inequality_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,3.206996,3.206996
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,4.938327,4.938327
97,02261,AK,Valdez-Cordova Census Area,4.688209,3.920421,3.47993,3.553476,NaN,3.910509
214,06041,CA,Marin County,5.659528,5.772842,NaN,NaN,NaN,5.716185
231,06075,CA,San Francisco County,7.068538,7.087860,NaN,NaN,NaN,7.078199

In [67]:
# ==========================================================
# PART 19B: Impute and Recalculate Income Inequality
# ==========================================================

# üéØ Columns to impute
inequality_cols = [f'income_inequality_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-level means for each year
states = income_inequality['State'].unique()
for state in states:
    state_data = income_inequality[income_inequality['State'] == state]
    for col in inequality_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (income_inequality['State'] == state) & (income_inequality[col].isna())
        income_inequality.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
income_inequality[inequality_cols] = income_inequality[inequality_cols].apply(pd.to_numeric, errors='coerce')
income_inequality['income_inequality_mean'] = income_inequality[inequality_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_inequality = pd.DataFrame({
    "Missing Count": income_inequality[inequality_cols].isna().sum(),
    "Missing %": (income_inequality[inequality_cols].isna().sum() / len(income_inequality) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Income Inequality (After Imputation)")
print(missing_report_final_inequality)

# üëÄ Preview
income_inequality.head()

üìã Final Missing Value Report: Income Inequality (After Imputation)
                        Missing Count  Missing %
income_inequality_2020              1       0.03
income_inequality_2021              1       0.03
income_inequality_2022              1       0.03
income_inequality_2023              1       0.03
income_inequality_2024              1       0.03

,FIPS,State,County,income_inequality_2020,income_inequality_2021,income_inequality_2022,income_inequality_2023,income_inequality_2024,income_inequality_mean
0,00000,US,United States,4.920018,4.913801,4.892074,4.891375,4.902842,4.904022
1,01000,AL,Alabama,5.261136,5.238165,5.157920,5.176676,5.212688,5.209317
2,01001,AL,Autauga County,5.234597,5.090408,5.135446,4.794400,4.637675,4.978505
3,01003,AL,Baldwin County,4.417767,4.385135,4.386478,4.300710,4.482449,4.394508
4,01005,AL,Barbour County,5.681410,5.981993,5.994927,5.180597,5.576797,5.683145

üßæ Interpreting Income Inequality raw value

The Income Inequality raw value represents the level of income inequality within a county. This value is commonly based on the Gini index or similar measures, where:
	‚Ä¢	0 = perfect equality (everyone earns the same)
	‚Ä¢	1 = maximal inequality (one person has all the income)

In this dataset, higher values indicate higher inequality.

This metric helps assess economic disparities and is important for understanding socioeconomic conditions and potential policy needs for addressing inequality.

In [69]:
# ==========================================================
# PART 20A: Load Median Household Income and Report Missing
# ==========================================================

def load_median_household_income_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "median household income raw value",
        "Median household income raw value",
        "Median Household Income raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'median_income_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
income_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_median_household_income_column(file_path, year)
    income_dfs.append(df)

# üß© Merge all years
median_income = income_dfs[0]
for df in income_dfs[1:]:
    median_income = pd.merge(median_income, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
income_cols = [f'median_income_{y}' for y in range(2020, 2025)]
median_income[income_cols] = median_income[income_cols].apply(pd.to_numeric, errors='coerce')
median_income['median_income_mean'] = median_income[income_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_income = pd.DataFrame({
    "Missing Count": median_income[income_cols].isna().sum(),
    "Missing %": (median_income[income_cols].isna().sum() / len(median_income) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Median Household Income, Before Imputation)")
print(missing_report_income)

# üîç Show rows with missing values
rows_with_na_income = median_income[median_income[income_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_income)}")
rows_with_na_income.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Median Household Income, Before Imputation)
                    Missing Count  Missing %
median_income_2020              5       0.16
median_income_2021              5       0.16
median_income_2022              6       0.19
median_income_2023              6       0.19
median_income_2024              4       0.13

üîç Rows with missing values: 7

,FIPS,State,County,median_income_2020,median_income_2021,median_income_2022,median_income_2023,median_income_2024,median_income_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,91356.0,91356.0
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,63837.0,63837.0
97,02261,AK,Valdez-Cordova Census Area,68528.0,74574.0,NaN,NaN,NaN,71551.0
563,15005,HI,Kalawao County,NaN,NaN,NaN,NaN,NaN,NaN
1164,22059,LA,La Salle Parish,45742.0,51014.0,48306.0,NaN,NaN,48354.0

In [70]:
# ==========================================================
# PART 20B: Impute and Recalculate Median Household Income
# ==========================================================

# üéØ Define columns to impute
income_cols = [f'median_income_{y}' for y in range(2020, 2025)]

# üßº Impute missing values using state-level means for each year
states = median_income['State'].unique()
for state in states:
    state_data = median_income[median_income['State'] == state]
    for col in income_cols:
        year_mean = state_data[col].mean(skipna=True)
        missing_mask = (median_income['State'] == state) & (median_income[col].isna())
        median_income.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation
median_income[income_cols] = median_income[income_cols].apply(pd.to_numeric, errors='coerce')
median_income['median_income_mean'] = median_income[income_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_income = pd.DataFrame({
    "Missing Count": median_income[income_cols].isna().sum(),
    "Missing %": (median_income[income_cols].isna().sum() / len(median_income) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Median Household Income (After Imputation)")
print(missing_report_final_income)

# üëÄ Preview
median_income.head()

üìã Final Missing Value Report: Median Household Income (After Imputation)
                    Missing Count  Missing %
median_income_2020              1       0.03
median_income_2021              1       0.03
median_income_2022              1       0.03
median_income_2023              1       0.03
median_income_2024              1       0.03

,FIPS,State,County,median_income_2020,median_income_2021,median_income_2022,median_income_2023,median_income_2024,median_income_mean
0,00000,US,United States,61937.0,65712.0,67340.0,69717.0,74755.0,67892.2
1,01000,AL,Alabama,49881.0,51771.0,53958.0,53990.0,59703.0,53860.6
2,01001,AL,Autauga County,59338.0,58233.0,67565.0,66444.0,70148.0,64345.6
3,01003,AL,Baldwin County,57588.0,59871.0,71135.0,65658.0,71704.0,65191.2
4,01005,AL,Barbour County,34382.0,35972.0,38866.0,38649.0,41151.0,37804.0

üßæ Interpreting Median Household Income raw value

The Median Household Income raw value represents the median income of households in a county, measured in U.S. dollars. The median income is the middle value of income when all households are ordered, which means 50% of households earn less and 50% earn more.
	‚Ä¢	Values are given in dollars for each year (e.g., $61,937 in 2020 for the U.S. as a whole).
	‚Ä¢	Higher values indicate more prosperous areas with more disposable income.
	‚Ä¢	Lower values suggest areas with lower economic conditions or more economic disparity.

This metric is key for understanding economic well-being, poverty levels, and regional economic disparities. Higher median incomes are typically linked to more affordable housing, better quality of life, and economic opportunities.

In [72]:
# ==========================================================
# PART 21A: Load Children Eligible for Free or Reduced Price Lunch and Report Missing
# ==========================================================

def load_children_lunch_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "children eligible for free or reduced price lunch raw value",
        "Children eligible for free or reduced price lunch raw value",
        "Children Eligible for Free or Reduced Price Lunch raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'children_lunch_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
lunch_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_children_lunch_column(file_path, year)
    lunch_dfs.append(df)

# üß© Merge all years
children_lunch = lunch_dfs[0]
for df in lunch_dfs[1:]:
    children_lunch = pd.merge(children_lunch, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
lunch_cols = [f'children_lunch_{y}' for y in range(2020, 2025)]
children_lunch[lunch_cols] = children_lunch[lunch_cols].apply(pd.to_numeric, errors='coerce')
children_lunch['children_lunch_mean'] = children_lunch[lunch_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_lunch = pd.DataFrame({
    "Missing Count": children_lunch[lunch_cols].isna().sum(),
    "Missing %": (children_lunch[lunch_cols].isna().sum() / len(children_lunch) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Children Eligible for Free or Reduced Price Lunch, Before Imputation)")
print(missing_report_lunch)

# üîç Show rows with missing values
rows_with_na_lunch = children_lunch[children_lunch[lunch_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_lunch)}")
rows_with_na_lunch.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Children Eligible for Free or Reduced Price Lunch, Before Imputation)
                     Missing Count  Missing %
children_lunch_2020            130       4.07
children_lunch_2021            128       4.00
children_lunch_2022             60       1.88
children_lunch_2023            592      18.51
children_lunch_2024            555      17.35

üîç Rows with missing values: 811

,FIPS,State,County,children_lunch_2020,children_lunch_2021,children_lunch_2022,children_lunch_2023,children_lunch_2024,children_lunch_mean
69,02000,AK,Alaska,0.445528,0.424425,0.429551,NaN,NaN,0.433168
70,02013,AK,Aleutians East Borough,0.039648,0.039648,0.039648,NaN,NaN,0.039648
71,02016,AK,Aleutians West Census Area,0.204499,0.195918,0.182000,NaN,NaN,0.194139
72,02020,AK,Anchorage Borough,0.465113,0.365872,0.434985,NaN,NaN,0.421990
73,02050,AK,Bethel Census Area,0.899401,0.922738,0.913180,NaN,NaN,0.911773

In [73]:
# ==========================================================
# PART 21B: Impute and Recalculate Children Eligible for Free or Reduced Price Lunch
# ==========================================================

# üéØ Define columns to impute (using 2020- 2024)
lunch_cols = [f'children_lunch_{y}' for y in range(2020, 2025)] # (using 2020- 2024)

# üßº Impute missing values using state-level means for each year
states = children_lunch['State'].unique()
for state in states:
    state_data = children_lunch[children_lunch['State'] == state]
    for col in lunch_cols:
        year_mean = state_data[col].mean(skipna=True)  # (using 2020- 2024)
        missing_mask = (children_lunch['State'] == state) & (children_lunch[col].isna())
        children_lunch.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation using (using 2020- 2024)
children_lunch[lunch_cols] = children_lunch[lunch_cols].apply(pd.to_numeric, errors='coerce')
children_lunch['children_lunch_mean'] = children_lunch[lunch_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_lunch = pd.DataFrame({
    "Missing Count": children_lunch[lunch_cols].isna().sum(),
    "Missing %": (children_lunch[lunch_cols].isna().sum() / len(children_lunch) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Children Eligible for Free or Reduced Price Lunch (After Imputation)")
print(missing_report_final_lunch)

# üëÄ Preview
children_lunch.head()

üìã Final Missing Value Report: Children Eligible for Free or Reduced Price Lunch (After Imputation)
                     Missing Count  Missing %
children_lunch_2020            118       3.69
children_lunch_2021            118       3.69
children_lunch_2022             22       0.69
children_lunch_2023            586      18.32
children_lunch_2024            549      17.17

,FIPS,State,County,children_lunch_2020,children_lunch_2021,children_lunch_2022,children_lunch_2023,children_lunch_2024,children_lunch_mean
0,00000,US,United States,0.522823,0.522489,0.520917,0.530855,0.507603,0.520937
1,01000,AL,Alabama,0.558742,0.550708,0.550055,0.533383,0.491741,0.536926
2,01001,AL,Autauga County,0.434087,0.474929,0.454825,0.412507,0.279986,0.411267
3,01003,AL,Baldwin County,0.484866,0.400130,0.461323,0.463740,0.369956,0.436003
4,01005,AL,Barbour County,0.632923,0.607700,0.602062,0.586929,0.565651,0.599053

The Children Eligible for Free or Reduced Price Lunch raw value represents the proportion of children in a county who are eligible for free or reduced-price meals at school. The values range from 0 (none eligible) to 1 (all children eligible).

For the imputation process, I have calculated and imputed the mean based on the data available for 2020, 2021, and 2022 only, excluding 2023 and 2024 from the mean calculation. This decision was made because the 2023 and 2024 data had a high percentage of missing values across several counties, making it challenging to rely on them for consistent imputation. Therefore, the mean values for 2020, 2021, and 2022 were used to fill the gaps in the data for a more accurate reflection of eligibility.

This data is important for understanding food insecurity and the socioeconomic status of households with children in each county.

In [75]:
# ==========================================================
# PART 22A: Load High School Graduation and Report Missing
# ==========================================================

def load_high_school_graduation_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "high school graduation raw value",
        "High school graduation raw value",
        "High School Graduation raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'high_school_graduation_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
graduation_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_high_school_graduation_column(file_path, year)
    graduation_dfs.append(df)

# üß© Merge all years
high_school_graduation = graduation_dfs[0]
for df in graduation_dfs[1:]:
    high_school_graduation = pd.merge(high_school_graduation, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
graduation_cols = [f'high_school_graduation_{y}' for y in range(2020, 2025)]
high_school_graduation[graduation_cols] = high_school_graduation[graduation_cols].apply(pd.to_numeric, errors='coerce')
high_school_graduation['high_school_graduation_mean'] = high_school_graduation[graduation_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_graduation = pd.DataFrame({
    "Missing Count": high_school_graduation[graduation_cols].isna().sum(),
    "Missing %": (high_school_graduation[graduation_cols].isna().sum() / len(high_school_graduation) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (High School Graduation, Before Imputation)")
print(missing_report_graduation)

# üîç Show rows with missing values
rows_with_na_graduation = high_school_graduation[high_school_graduation[graduation_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_graduation)}")
rows_with_na_graduation.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (High School Graduation, Before Imputation)
                             Missing Count  Missing %
high_school_graduation_2020            100       3.13
high_school_graduation_2021            560      17.51
high_school_graduation_2022            664      20.76
high_school_graduation_2023            836      26.14
high_school_graduation_2024            681      21.29

üîç Rows with missing values: 973

,FIPS,State,County,high_school_graduation_2020,high_school_graduation_2021,high_school_graduation_2022,high_school_graduation_2023,high_school_graduation_2024,high_school_graduation_mean
20,01037,AL,Coosa County,0.827160,0.825,NaN,0.825,NaN,0.825720
70,02013,AK,Aleutians East Borough,0.888889,NaN,NaN,NaN,NaN,0.888889
71,02016,AK,Aleutians West Census Area,0.906250,NaN,NaN,NaN,NaN,0.906250
74,02060,AK,Bristol Bay Borough,0.853659,NaN,NaN,NaN,NaN,0.853659
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
# ==========================================================
# PART 22B: Impute and Recalculate High School Graduation
# ==========================================================

# üéØ Define columns to impute (using 2020- 2024)
graduation_cols = [f'high_school_graduation_{y}' for y in range(2020, 2025)]  # (using 2020- 2024)

# üßº Impute missing values using state-level means for each year
states = high_school_graduation['State'].unique()
for state in states:
    state_data = high_school_graduation[high_school_graduation['State'] == state]
    for col in graduation_cols:
        year_mean = state_data[col].mean(skipna=True)  # (using 2020- 2024)
        missing_mask = (high_school_graduation['State'] == state) & (high_school_graduation[col].isna())
        high_school_graduation.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation (using 2020- 2024)
high_school_graduation[graduation_cols] = high_school_graduation[graduation_cols].apply(pd.to_numeric, errors='coerce')
high_school_graduation['high_school_graduation_mean'] = high_school_graduation[graduation_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_graduation = pd.DataFrame({
    "Missing Count": high_school_graduation[graduation_cols].isna().sum(),
    "Missing %": (high_school_graduation[graduation_cols].isna().sum() / len(high_school_graduation) * 100).round(2)
})
print("\nüìã Final Missing Value Report: High School Graduation (After Imputation)")
print(missing_report_final_graduation)

# üëÄ Preview
high_school_graduation.head()

üìã Final Missing Value Report: High School Graduation (After Imputation)
                             Missing Count  Missing %
high_school_graduation_2020              1       0.03
high_school_graduation_2021             31       0.97
high_school_graduation_2022            134       4.19
high_school_graduation_2023            359      11.23
high_school_graduation_2024            144       4.50

,FIPS,State,County,high_school_graduation_2020,high_school_graduation_2021,high_school_graduation_2022,high_school_graduation_2023,high_school_graduation_2024,high_school_graduation_mean
0,00000,US,United States,0.846000,0.850000,0.860000,0.870000,0.861605,0.857521
1,01000,AL,Alabama,0.893000,0.901799,0.917132,0.907108,0.907581,0.905324
2,01001,AL,Autauga County,0.900000,0.890000,0.890000,0.870000,0.870000,0.884000
3,01003,AL,Baldwin County,0.863616,0.880000,0.900000,0.884522,0.886517,0.882931
4,01005,AL,Barbour County,0.814103,0.820690,0.848260,0.852961,0.854410,0.838085

üßæ High School Graduation raw value

The High School Graduation raw value represents the percentage of students graduating from high school in a county.
	Example: 0.827 means that 82.7% (0.827160) of students graduated from high school that year.

üìã Missing Data Insights:
	‚Ä¢	2020: 3.13% of the data is missing.
	‚Ä¢	2021: 17.51% is missing.
	‚Ä¢	2022: 20.76% is missing.
	‚Ä¢	2023: 26.14% is missing.
	‚Ä¢	2024: 21.29% is missing.

As seen, missing values for the years 2021‚Äì2024 are progressively increasing, which suggests potential data collection issues or variability in reporting for these years.

In [78]:
# ==========================================================
# PART 23A: Load Some College and Report Missing
# ==========================================================

def load_some_college_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "some college raw value",
        "Some college raw value",
        "Some College raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'some_college_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
college_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_some_college_column(file_path, year)
    college_dfs.append(df)

# üß© Merge all years
some_college = college_dfs[0]
for df in college_dfs[1:]:
    some_college = pd.merge(some_college, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
college_cols = [f'some_college_{y}' for y in range(2020, 2025)]
some_college[college_cols] = some_college[college_cols].apply(pd.to_numeric, errors='coerce')
some_college['some_college_mean'] = some_college[college_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_college = pd.DataFrame({
    "Missing Count": some_college[college_cols].isna().sum(),
    "Missing %": (some_college[college_cols].isna().sum() / len(some_college) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Some College, Before Imputation)")
print(missing_report_college)

# üîç Show rows with missing values
rows_with_na_college = some_college[some_college[college_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_college)}")
rows_with_na_college.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Some College, Before Imputation)
                   Missing Count  Missing %
some_college_2020              4       0.13
some_college_2021              4       0.13
some_college_2022              4       0.13
some_college_2023              4       0.13
some_college_2024              3       0.09

üîç Rows with missing values: 6

,FIPS,State,County,some_college_2020,some_college_2021,some_college_2022,some_college_2023,some_college_2024,some_college_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.749644,0.749644
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.689981,0.689981
97,02261,AK,Valdez-Cordova Census Area,0.527468,0.558457,0.651398,0.67377,NaN,0.602773
1164,22059,LA,La Salle Parish,0.415859,0.415385,0.402436,NaN,NaN,0.411227
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,0.37480,0.384270,0.379535

In [79]:
# ==========================================================
# PART 23B: Impute and Recalculate Some College
# ==========================================================

# üéØ Define columns to impute 
college_cols = [f'some_college_{y}' for y in range(2020, 2025)]  # Using mean of 5 yrs

# üßº Impute missing values using state-level means for each year
states = some_college['State'].unique()
for state in states:
    state_data = some_college[some_college['State'] == state]
    for col in college_cols:
        year_mean = state_data[col].mean(skipna=True)  # Using only 2020, 2021, and 2022 data
        missing_mask = (some_college['State'] == state) & (some_college[col].isna())
        some_college.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation using 
some_college[college_cols] = some_college[college_cols].apply(pd.to_numeric, errors='coerce')
some_college['some_college_mean'] = some_college[college_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_college = pd.DataFrame({
    "Missing Count": some_college[college_cols].isna().sum(),
    "Missing %": (some_college[college_cols].isna().sum() / len(some_college) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Some College (After Imputation)")
print(missing_report_final_college)

# üëÄ Preview
some_college.head()

üìã Final Missing Value Report: Some College (After Imputation)
                   Missing Count  Missing %
some_college_2020              1       0.03
some_college_2021              1       0.03
some_college_2022              1       0.03
some_college_2023              1       0.03
some_college_2024              1       0.03

,FIPS,State,County,some_college_2020,some_college_2021,some_college_2022,some_college_2023,some_college_2024,some_college_mean
0,00000,US,United States,0.657241,0.661334,0.669151,0.672533,0.675830,0.667218
1,01000,AL,Alabama,0.604119,0.607141,0.615753,0.615008,0.616042,0.611613
2,01001,AL,Autauga County,0.620100,0.604999,0.607217,0.596126,0.641475,0.613983
3,01003,AL,Baldwin County,0.673716,0.671086,0.655321,0.661050,0.656804,0.663596
4,01005,AL,Barbour County,0.348576,0.356138,0.383558,0.386269,0.404545,0.375817

üßæ Interpreting Some College Raw Value:

The Some College raw value represents the percentage of individuals in a county or region who have attended some college but did not necessarily graduate with a degree. The values are expressed as proportions ranging from 0 (none) to 1 (100%).

This indicator is important for understanding educational attainment in an area, as it reflects the level of higher education participation. It is often linked to economic opportunity, as individuals with some college education may have greater access to better-paying jobs and career advancement.

In [81]:
# ==========================================================
# PART 24A: Load Disconnected Youth and Report Missing
# ==========================================================

def load_disconnected_youth_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "disconnected youth raw value",
        "Disconnected youth raw value",
        "Disconnected Youth raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'disconnected_youth_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
youth_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_disconnected_youth_column(file_path, year)
    youth_dfs.append(df)

# üß© Merge all years
disconnected_youth = youth_dfs[0]
for df in youth_dfs[1:]:
    disconnected_youth = pd.merge(disconnected_youth, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
youth_cols = [f'disconnected_youth_{y}' for y in range(2020, 2025)]
disconnected_youth[youth_cols] = disconnected_youth[youth_cols].apply(pd.to_numeric, errors='coerce')
disconnected_youth['disconnected_youth_mean'] = disconnected_youth[youth_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_youth = pd.DataFrame({
    "Missing Count": disconnected_youth[youth_cols].isna().sum(),
    "Missing %": (disconnected_youth[youth_cols].isna().sum() / len(disconnected_youth) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Disconnected Youth, Before Imputation)")
print(missing_report_youth)

# üîç Show rows with missing values
rows_with_na_youth = disconnected_youth[disconnected_youth[youth_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_youth)}")
rows_with_na_youth.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Disconnected Youth, Before Imputation)
                         Missing Count  Missing %
disconnected_youth_2020           1770      55.35
disconnected_youth_2021           1840      57.54
disconnected_youth_2022           1925      60.19
disconnected_youth_2023           1942      60.73
disconnected_youth_2024           1973      61.69

üîç Rows with missing values: 2203

,FIPS,State,County,disconnected_youth_2020,disconnected_youth_2021,disconnected_youth_2022,disconnected_youth_2023,disconnected_youth_2024,disconnected_youth_mean
2,01001,AL,Autauga County,NaN,NaN,NaN,NaN,0.072425,0.072425
4,01005,AL,Barbour County,0.133393,NaN,NaN,NaN,NaN,0.133393
5,01007,AL,Bibb County,NaN,NaN,NaN,NaN,NaN,NaN
7,01011,AL,Bullock County,NaN,NaN,NaN,NaN,NaN,NaN
8,01013,AL,Butler County,NaN,NaN,NaN,NaN,NaN,NaN

üßæ Note on Imputation for Disconnected Youth

Given the high percentage of missing values for the Disconnected Youth raw value (over 55% for most years), it is not advisable to impute the data. This could introduce bias or inaccuracy in the analysis. Thus, the missing values will be left unfilled.

‚∏ª

üßæ Understanding the Disconnected Youth Raw Value

The Disconnected Youth raw value represents the percentage of youth (ages 16‚Äì24) who are not in school and not working. This is a critical indicator for understanding the challenges young people face in terms of education and employment opportunities.
	‚Ä¢	0.133393 means 13.34% of youth in the area are disconnected from education or employment.
	‚Ä¢	Higher values indicate higher levels of disconnection, suggesting that a larger proportion of youth are struggling with lack of access to education or employment opportunities.
	‚Ä¢	Lower values indicate better engagement in school and work, which are key for economic stability and social mobility.

This metric is vital for identifying regions that may need additional support for youth programs, such as job training or education initiatives.

In [83]:
# ==========================================================
# PART 25A: Load Reading Scores and Report Missing
# ==========================================================

def load_reading_scores_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "reading scores raw value",
        "Reading scores raw value",
        "Reading Scores raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'reading_scores_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
reading_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_reading_scores_column(file_path, year)
    reading_dfs.append(df)

# üß© Merge all years
reading_scores = reading_dfs[0]
for df in reading_dfs[1:]:
    reading_scores = pd.merge(reading_scores, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
reading_cols = [f'reading_scores_{y}' for y in range(2020, 2025)]
reading_scores[reading_cols] = reading_scores[reading_cols].apply(pd.to_numeric, errors='coerce')
reading_scores['reading_scores_mean'] = reading_scores[reading_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_reading = pd.DataFrame({
    "Missing Count": reading_scores[reading_cols].isna().sum(),
    "Missing %": (reading_scores[reading_cols].isna().sum() / len(reading_scores) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Reading Scores, Before Imputation)")
print(missing_report_reading)

# üîç Show rows with missing values
rows_with_na_reading = reading_scores[reading_scores[reading_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_reading)}")
rows_with_na_reading.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Reading Scores, Before Imputation)
                     Missing Count  Missing %
reading_scores_2020            640      20.01
reading_scores_2021            372      11.63
reading_scores_2022            372      11.63
reading_scores_2023            372      11.63
reading_scores_2024            372      11.63

üîç Rows with missing values: 786

,FIPS,State,County,reading_scores_2020,reading_scores_2021,reading_scores_2022,reading_scores_2023,reading_scores_2024,reading_scores_mean
29,01055,AL,Etowah County,NaN,3.010232,3.010232,3.010232,3.010232,3.010232
69,02000,AK,Alaska,2.745431,NaN,NaN,NaN,NaN,2.745431
70,02013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,NaN,NaN
71,02016,AK,Aleutians West Census Area,NaN,NaN,NaN,NaN,NaN,NaN
72,02020,AK,Anchorage Borough,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
# ==========================================================
# PART 25B: Impute and Recalculate Reading Scores (Based on All 5 Years)
# ==========================================================

# üéØ Define columns to impute (using all 5 years: 2020‚Äì2024)
reading_cols = [f'reading_scores_{y}' for y in range(2020, 2025)]  # Using 2020 to 2024

# üßº Impute missing values using state-level means for each year
states = reading_scores['State'].unique()
for state in states:
    state_data = reading_scores[reading_scores['State'] == state]
    for col in reading_cols:
        year_mean = state_data[col].mean(skipna=True)  # Using all 5 years for imputation
        missing_mask = (reading_scores['State'] == state) & (reading_scores[col].isna())
        reading_scores.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation using all 5 years
reading_scores[reading_cols] = reading_scores[reading_cols].apply(pd.to_numeric, errors='coerce')
reading_scores['reading_scores_mean'] = reading_scores[reading_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_reading = pd.DataFrame({
    "Missing Count": reading_scores[reading_cols].isna().sum(),
    "Missing %": (reading_scores[reading_cols].isna().sum() / len(reading_scores) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Reading Scores (After Imputation)")
print(missing_report_final_reading)

# üëÄ Preview
reading_scores.head()

üìã Final Missing Value Report: Reading Scores (After Imputation)
                     Missing Count  Missing %
reading_scores_2020              1       0.03
reading_scores_2021            252       7.88
reading_scores_2022            252       7.88
reading_scores_2023            252       7.88
reading_scores_2024            252       7.88

,FIPS,State,County,reading_scores_2020,reading_scores_2021,reading_scores_2022,reading_scores_2023,reading_scores_2024,reading_scores_mean
0,00000,US,United States,3.100681,3.053421,3.053421,3.053400,3.053421,3.062869
1,01000,AL,Alabama,2.964745,2.885603,2.885603,2.885603,2.885603,2.901431
2,01001,AL,Autauga County,2.959586,3.126968,3.126968,3.126968,3.126968,3.093492
3,01003,AL,Baldwin County,3.005642,3.192381,3.192381,3.192381,3.192381,3.155033
4,01005,AL,Barbour County,2.660388,2.389161,2.389161,2.389161,2.389161,2.443407

üßæ Interpreting Reading Scores Raw Value:

The Reading Scores raw value represents the average reading score for a specific county or area, based on standardized assessments of reading ability for students.
	‚Ä¢	Values are on a scale (e.g., 2.96 in Alabama for 2020), with higher scores indicating better performance in reading assessments.
	‚Ä¢	The score values are calculated based on performance data from multiple assessments over the years, showing trends in reading proficiency across different regions.

This indicator is important for understanding educational outcomes, especially in terms of reading skills, which are crucial for academic success and future opportunities. The mean score calculated across all 5 years helps to smooth out fluctuations and offer a more stable measure of performance.

In [86]:
# ==========================================================
# PART 26A: Load Math Scores and Report Missing
# ==========================================================

def load_math_scores_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "math scores raw value",
        "Math scores raw value",
        "Math Scores raw value"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'math_scores_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
math_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_math_scores_column(file_path, year)
    math_dfs.append(df)

# üß© Merge all years
math_scores = math_dfs[0]
for df in math_dfs[1:]:
    math_scores = pd.merge(math_scores, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
math_cols = [f'math_scores_{y}' for y in range(2020, 2025)]
math_scores[math_cols] = math_scores[math_cols].apply(pd.to_numeric, errors='coerce')
math_scores['math_scores_mean'] = math_scores[math_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_math = pd.DataFrame({
    "Missing Count": math_scores[math_cols].isna().sum(),
    "Missing %": (math_scores[math_cols].isna().sum() / len(math_scores) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Math Scores, Before Imputation)")
print(missing_report_math)

# üîç Show rows with missing values
rows_with_na_math = math_scores[math_scores[math_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_math)}")
rows_with_na_math.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Math Scores, Before Imputation)
                  Missing Count  Missing %
math_scores_2020            678      21.20
math_scores_2021            459      14.35
math_scores_2022            459      14.35
math_scores_2023            459      14.35
math_scores_2024            459      14.35

üîç Rows with missing values: 940

,FIPS,State,County,math_scores_2020,math_scores_2021,math_scores_2022,math_scores_2023,math_scores_2024,math_scores_mean
29,01055,AL,Etowah County,NaN,2.782796,2.782796,2.782796,2.782796,2.782796
69,02000,AK,Alaska,2.759863,NaN,NaN,NaN,NaN,2.759863
70,02013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,NaN,NaN
71,02016,AK,Aleutians West Census Area,NaN,NaN,NaN,NaN,NaN,NaN
72,02020,AK,Anchorage Borough,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
# ==========================================================
# PART 26B: Impute and Recalculate Math Scores (Based on All 5 Years)
# ==========================================================

# üéØ Define columns to impute (using all 5 years: 2020‚Äì2024)
math_cols = [f'math_scores_{y}' for y in range(2020, 2025)]  # Using 2020 to 2024

# üßº Impute missing values using state-level means for each year
states = math_scores['State'].unique()
for state in states:
    state_data = math_scores[math_scores['State'] == state]
    for col in math_cols:
        year_mean = state_data[col].mean(skipna=True)  # Using all 5 years for imputation
        missing_mask = (math_scores['State'] == state) & (math_scores[col].isna())
        math_scores.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation using all 5 years
math_scores[math_cols] = math_scores[math_cols].apply(pd.to_numeric, errors='coerce')
math_scores['math_scores_mean'] = math_scores[math_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_math = pd.DataFrame({
    "Missing Count": math_scores[math_cols].isna().sum(),
    "Missing %": (math_scores[math_cols].isna().sum() / len(math_scores) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Math Scores (After Imputation)")
print(missing_report_final_math)

# üëÄ Preview
math_scores.head()

üìã Final Missing Value Report: Math Scores (After Imputation)
                  Missing Count  Missing %
math_scores_2020              1       0.03
math_scores_2021            352      11.01
math_scores_2022            352      11.01
math_scores_2023            352      11.01
math_scores_2024            352      11.01

,FIPS,State,County,math_scores_2020,math_scores_2021,math_scores_2022,math_scores_2023,math_scores_2024,math_scores_mean
0,00000,US,United States,3.018014,3.002972,3.002972,3.003000,3.002972,3.005986
1,01000,AL,Alabama,2.776835,2.722188,2.722188,2.722188,2.722188,2.733117
2,01001,AL,Autauga County,2.802699,2.917280,2.917280,2.917280,2.917280,2.894363
3,01003,AL,Baldwin County,2.860696,3.037912,3.037912,3.037912,3.037912,3.002468
4,01005,AL,Barbour County,2.443271,2.008629,2.008629,2.008629,2.008629,2.095558

üßæ Interpreting Math Scores Raw Value:

The Math Scores raw value represents the average math score for a specific county or area, based on standardized math assessments for students.
	‚Ä¢	Values are on a scale (e.g., 2.89 for Autauga County in 2024), with higher values indicating better performance in math assessments.
	‚Ä¢	The scores reflect students‚Äô proficiency and performance in math, which is an essential skill for academic success and future career opportunities.

This indicator is important for evaluating educational outcomes and learning disparities. Higher math scores are typically linked to better educational systems and greater academic achievement.

In [89]:
# ==========================================================
# PART 27A: Load % Not Proficient in English and Report Missing
# ==========================================================

def load_not_proficient_english_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Variations of target column name
    target_cols = [
        "% not proficient in English raw value",
        "% Not Proficient in English raw value",
        "% Not Proficient in English"
    ]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'not_proficient_english_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load all 5 years
english_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_not_proficient_english_column(file_path, year)
    english_dfs.append(df)

# üß© Merge all years
not_proficient_english = english_dfs[0]
for df in english_dfs[1:]:
    not_proficient_english = pd.merge(not_proficient_english, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
english_cols = [f'not_proficient_english_{y}' for y in range(2020, 2025)]
not_proficient_english[english_cols] = not_proficient_english[english_cols].apply(pd.to_numeric, errors='coerce')
not_proficient_english['not_proficient_english_mean'] = not_proficient_english[english_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_english = pd.DataFrame({
    "Missing Count": not_proficient_english[english_cols].isna().sum(),
    "Missing %": (not_proficient_english[english_cols].isna().sum() / len(not_proficient_english) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (% Not Proficient in English, Before Imputation)")
print(missing_report_english)

# üîç Show rows with missing values
rows_with_na_english = not_proficient_english[not_proficient_english[english_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_english)}")
rows_with_na_english.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (% Not Proficient in English, Before Imputation)
                             Missing Count  Missing %
not_proficient_english_2020              4       0.13
not_proficient_english_2021              4       0.13
not_proficient_english_2022              4       0.13
not_proficient_english_2023              4       0.13
not_proficient_english_2024              3       0.09

üîç Rows with missing values: 6

,FIPS,State,County,not_proficient_english_2020,not_proficient_english_2021,not_proficient_english_2022,not_proficient_english_2023,not_proficient_english_2024,not_proficient_english_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.017456,0.017456
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.000000,0.000000
97,02261,AK,Valdez-Cordova Census Area,0.002753,0.002887,0.004429,0.005640,NaN,0.003927
1164,22059,LA,La Salle Parish,0.007937,0.006616,0.007154,NaN,NaN,0.007236
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,0.009053,0.004013,0.006533

In [90]:
# ==========================================================
# PART 27B: Impute and Recalculate % Not Proficient in English
# ==========================================================

# üéØ Define columns to impute (using all 5 years: 2020‚Äì2024)
english_cols = [f'not_proficient_english_{y}' for y in range(2020, 2025)]  # Using 2020 to 2024

# üßº Impute missing values using state-level means for each year
states = not_proficient_english['State'].unique()
for state in states:
    state_data = not_proficient_english[not_proficient_english['State'] == state]
    for col in english_cols:
        year_mean = state_data[col].mean(skipna=True)  # Using all 5 years for imputation
        missing_mask = (not_proficient_english['State'] == state) & (not_proficient_english[col].isna())
        not_proficient_english.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation using all 5 years
not_proficient_english[english_cols] = not_proficient_english[english_cols].apply(pd.to_numeric, errors='coerce')
not_proficient_english['not_proficient_english_mean'] = not_proficient_english[english_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_english = pd.DataFrame({
    "Missing Count": not_proficient_english[english_cols].isna().sum(),
    "Missing %": (not_proficient_english[english_cols].isna().sum() / len(not_proficient_english) * 100).round(2)
})
print("\nüìã Final Missing Value Report: % Not Proficient in English (After Imputation)")
print(missing_report_final_english)

# üëÄ Preview
not_proficient_english.head()

üìã Final Missing Value Report: % Not Proficient in English (After Imputation)
                             Missing Count  Missing %
not_proficient_english_2020              1       0.03
not_proficient_english_2021              1       0.03
not_proficient_english_2022              1       0.03
not_proficient_english_2023              1       0.03
not_proficient_english_2024              1       0.03

,FIPS,State,County,not_proficient_english_2020,not_proficient_english_2021,not_proficient_english_2022,not_proficient_english_2023,not_proficient_english_2024,not_proficient_english_mean
0,00000,US,United States,0.043960,0.043266,0.041597,0.041044,0.040955,0.042164
1,01000,AL,Alabama,0.010610,0.011007,0.010194,0.010276,0.010475,0.010513
2,01001,AL,Autauga County,0.008202,0.008033,0.006927,0.002312,0.003665,0.005828
3,01003,AL,Baldwin County,0.005435,0.007085,0.007721,0.007597,0.007867,0.007141
4,01005,AL,Barbour County,0.016317,0.018907,0.018275,0.013827,0.019807,0.017426

üßæ Interpreting % Not Proficient in English Raw Value:

The % Not Proficient in English raw value represents the percentage of individuals in a given county or state who are not proficient in English.
	‚Ä¢	Values range from 0 (no one is non-proficient in English) to 1 (everyone is non-proficient in English).
	‚Ä¢	0.010610 for Alabama in 2020 means that 1.06% of the population is not proficient in English in that year.

This indicator helps assess the level of English language proficiency in a region, which is vital for understanding linguistic diversity and the challenges related to language barriers in education, employment, and social integration.

In [92]:
# ==========================================================
# PART 27A: Load Food Environment Index raw value and Report Missing
# ==========================================================

def load_food_environment_index_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["food environment index raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'food_environment_index_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years
food_environment_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_food_environment_index_column(file_path, year)
    food_environment_dfs.append(df)

# üß© Merge all years
food_environment_index = food_environment_dfs[0]
for df in food_environment_dfs[1:]:
    food_environment_index = pd.merge(food_environment_index, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
food_environment_cols = [f'food_environment_index_{y}' for y in range(2020, 2025)]
food_environment_index[food_environment_cols] = food_environment_index[food_environment_cols].apply(pd.to_numeric, errors='coerce')
food_environment_index['food_environment_index_mean'] = food_environment_index[food_environment_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_food_environment = pd.DataFrame({
    "Missing Count": food_environment_index[food_environment_cols].isna().sum(),
    "Missing %": (food_environment_index[food_environment_cols].isna().sum() / len(food_environment_index) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Food Environment Index, Before Imputation)")
print(missing_report_food_environment)

# üîç Show rows with missing values
rows_with_na_food_environment = food_environment_index[food_environment_index[food_environment_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_food_environment)}")
rows_with_na_food_environment.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Food Environment Index, Before Imputation)
                             Missing Count  Missing %
food_environment_index_2020             23       0.72
food_environment_index_2021             23       0.72
food_environment_index_2022             37       1.16
food_environment_index_2023             37       1.16
food_environment_index_2024             38       1.19

üîç Rows with missing values: 44

,FIPS,State,County,food_environment_index_2020,food_environment_index_2021,food_environment_index_2022,food_environment_index_2023,food_environment_index_2024,food_environment_index_mean
26,01049,AL,DeKalb County,8.2,7.3,NaN,NaN,NaN,7.75
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,NaN,NaN
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,NaN,NaN
86,02158,AK,Kusilvak Census Area,1.9,1.6,NaN,NaN,NaN,1.75
97,02261,AK,Valdez-Cordova Census Area,7.2,7.1,7.6,7.7,NaN,7.40

In [93]:
# ==========================================================
# PART 27B: Impute and Recalculate Food Environment Index
# ==========================================================

# üéØ Define columns to impute (using all 5 years: 2020‚Äì2024)
food_environment_cols = [f'food_environment_index_{y}' for y in range(2020, 2025)]  # Using 2020 to 2024

# üßº Impute missing values using state-level means for each year
states = food_environment_index['State'].unique()
for state in states:
    state_data = food_environment_index[food_environment_index['State'] == state]
    for col in food_environment_cols:
        year_mean = state_data[col].mean(skipna=True)  # Using all 5 years for imputation
        missing_mask = (food_environment_index['State'] == state) & (food_environment_index[col].isna())
        food_environment_index.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation using all 5 years
food_environment_index[food_environment_cols] = food_environment_index[food_environment_cols].apply(pd.to_numeric, errors='coerce')
food_environment_index['food_environment_index_mean'] = food_environment_index[food_environment_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_food_environment = pd.DataFrame({
    "Missing Count": food_environment_index[food_environment_cols].isna().sum(),
    "Missing %": (food_environment_index[food_environment_cols].isna().sum() / len(food_environment_index) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Food Environment Index (After Imputation)")
print(missing_report_final_food_environment)

# üëÄ Preview
food_environment_index.head()

üìã Final Missing Value Report: Food Environment Index (After Imputation)
                             Missing Count  Missing %
food_environment_index_2020              1       0.03
food_environment_index_2021              1       0.03
food_environment_index_2022              1       0.03
food_environment_index_2023              1       0.03
food_environment_index_2024              1       0.03

,FIPS,State,County,food_environment_index_2020,food_environment_index_2021,food_environment_index_2022,food_environment_index_2023,food_environment_index_2024,food_environment_index_mean
0,00000,US,United States,7.6,7.8,7.8,7.0,7.7,7.58
1,01000,AL,Alabama,5.8,5.5,5.3,5.3,5.4,5.46
2,01001,AL,Autauga County,7.2,6.7,6.5,6.6,6.7,6.74
3,01003,AL,Baldwin County,8.0,7.8,7.4,7.5,7.5,7.64
4,01005,AL,Barbour County,5.6,5.5,5.7,5.8,6.0,5.72

üßæ Interpreting Food Environment Index Raw Value:

The Food Environment Index raw value measures the overall quality of the food environment in a given area, considering factors such as availability, accessibility, and affordability of healthy foods.
	‚Ä¢	Values range from 0 (poor food environment) to 10 (excellent food environment).
	‚Ä¢	For example, a value of 7.6 for the United States in 2020 indicates a relatively healthy food environment overall.

This indicator is important for understanding community access to healthy food and how well local food systems support nutritional well-being. A higher index value suggests that the area provides better access to healthy food options, while a lower value could indicate barriers to accessing fresh, nutritious foods, such as food deserts or limited grocery store availability.

In [95]:
# ==========================================================
# PART 28A: Load Food Insecurity raw value and Report Missing
# ==========================================================

def load_food_insecurity_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["food insecurity raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'food_insecurity_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years
food_insecurity_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_food_insecurity_column(file_path, year)
    food_insecurity_dfs.append(df)

# üß© Merge all years
food_insecurity = food_insecurity_dfs[0]
for df in food_insecurity_dfs[1:]:
    food_insecurity = pd.merge(food_insecurity, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
food_insecurity_cols = [f'food_insecurity_{y}' for y in range(2020, 2025)]
food_insecurity[food_insecurity_cols] = food_insecurity[food_insecurity_cols].apply(pd.to_numeric, errors='coerce')
food_insecurity['food_insecurity_mean'] = food_insecurity[food_insecurity_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_food_insecurity = pd.DataFrame({
    "Missing Count": food_insecurity[food_insecurity_cols].isna().sum(),
    "Missing %": (food_insecurity[food_insecurity_cols].isna().sum() / len(food_insecurity) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Food Insecurity, Before Imputation)")
print(missing_report_food_insecurity)

# üîç Show rows with missing values
rows_with_na_food_insecurity = food_insecurity[food_insecurity[food_insecurity_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_food_insecurity)}")
rows_with_na_food_insecurity.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Food Insecurity, Before Imputation)
                      Missing Count  Missing %
food_insecurity_2020              4       0.13
food_insecurity_2021              4       0.13
food_insecurity_2022              4       0.13
food_insecurity_2023              4       0.13
food_insecurity_2024              3       0.09

üîç Rows with missing values: 6

,FIPS,State,County,food_insecurity_2020,food_insecurity_2021,food_insecurity_2022,food_insecurity_2023,food_insecurity_2024,food_insecurity_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.084,0.084000
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.124,0.124000
97,02261,AK,Valdez-Cordova Census Area,0.115,0.119,0.113,0.100,NaN,0.111750
1164,22059,LA,La Salle Parish,0.144,0.154,0.156,NaN,NaN,0.151333
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,0.124,0.119,0.121500

In [96]:
# ==========================================================
# PART 28B: Impute and Recalculate Food Insecurity
# ==========================================================

# üéØ Define columns to impute (using all 5 years: 2020‚Äì2024)
food_insecurity_cols = [f'food_insecurity_{y}' for y in range(2020, 2025)]  # Using 2020 to 2024

# üßº Impute missing values using state-level means for each year
states = food_insecurity['State'].unique()
for state in states:
    state_data = food_insecurity[food_insecurity['State'] == state]
    for col in food_insecurity_cols:
        year_mean = state_data[col].mean(skipna=True)  # Using all 5 years for imputation
        missing_mask = (food_insecurity['State'] == state) & (food_insecurity[col].isna())
        food_insecurity.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation using all 5 years
food_insecurity[food_insecurity_cols] = food_insecurity[food_insecurity_cols].apply(pd.to_numeric, errors='coerce')
food_insecurity['food_insecurity_mean'] = food_insecurity[food_insecurity_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_food_insecurity = pd.DataFrame({
    "Missing Count": food_insecurity[food_insecurity_cols].isna().sum(),
    "Missing %": (food_insecurity[food_insecurity_cols].isna().sum() / len(food_insecurity) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Food Insecurity (After Imputation)")
print(missing_report_final_food_insecurity)

# üëÄ Preview
food_insecurity.head()

üìã Final Missing Value Report: Food Insecurity (After Imputation)
                      Missing Count  Missing %
food_insecurity_2020              1       0.03
food_insecurity_2021              1       0.03
food_insecurity_2022              1       0.03
food_insecurity_2023              1       0.03
food_insecurity_2024              1       0.03

,FIPS,State,County,food_insecurity_2020,food_insecurity_2021,food_insecurity_2022,food_insecurity_2023,food_insecurity_2024,food_insecurity_mean
0,00000,US,United States,0.125,0.115,0.109,0.118,0.104,0.1142
1,01000,AL,Alabama,0.163,0.170,0.161,0.145,0.148,0.1574
2,01001,AL,Autauga County,0.132,0.156,0.157,0.145,0.133,0.1446
3,01003,AL,Baldwin County,0.116,0.129,0.134,0.124,0.118,0.1242
4,01005,AL,Barbour County,0.220,0.219,0.207,0.195,0.178,0.2038

üßæ Interpreting Food Insecurity Raw Value:

The Food Insecurity raw value represents the proportion of the population in a given area who lack consistent access to enough nutritious food for an active, healthy life.
	‚Ä¢	Values range from 0 (no food insecurity) to 1 (complete food insecurity).
	‚Ä¢	For example, a value of 0.163 for Alabama in 2020 means that approximately 16.3% of the population experienced food insecurity.

This indicator is crucial for understanding economic and social conditions affecting communities. Higher values indicate greater food insecurity, which is often linked to poverty, unemployment, or limited access to food resources. Addressing food insecurity is key for improving public health, economic stability, and quality of life in affected areas.

In [98]:
# ==========================================================
# PART 29A: Load Limited Access to Healthy Foods raw value and Report Missing
# ==========================================================

def load_limited_access_healthy_foods_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["limited access to healthy foods raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'limited_access_healthy_foods_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years
limited_access_healthy_foods_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_limited_access_healthy_foods_column(file_path, year)
    limited_access_healthy_foods_dfs.append(df)

# üß© Merge all years
limited_access_healthy_foods = limited_access_healthy_foods_dfs[0]
for df in limited_access_healthy_foods_dfs[1:]:
    limited_access_healthy_foods = pd.merge(limited_access_healthy_foods, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
limited_access_healthy_foods_cols = [f'limited_access_healthy_foods_{y}' for y in range(2020, 2025)]
limited_access_healthy_foods[limited_access_healthy_foods_cols] = limited_access_healthy_foods[limited_access_healthy_foods_cols].apply(pd.to_numeric, errors='coerce')
limited_access_healthy_foods['limited_access_healthy_foods_mean'] = limited_access_healthy_foods[limited_access_healthy_foods_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_limited_access_healthy_foods = pd.DataFrame({
    "Missing Count": limited_access_healthy_foods[limited_access_healthy_foods_cols].isna().sum(),
    "Missing %": (limited_access_healthy_foods[limited_access_healthy_foods_cols].isna().sum() / len(limited_access_healthy_foods) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Limited Access to Healthy Foods, Before Imputation)")
print(missing_report_limited_access_healthy_foods)

# üîç Show rows with missing values
rows_with_na_limited_access_healthy_foods = limited_access_healthy_foods[limited_access_healthy_foods[limited_access_healthy_foods_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_limited_access_healthy_foods)}")
rows_with_na_limited_access_healthy_foods.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Limited Access to Healthy Foods, Before Imputation)
                                   Missing Count  Missing %
limited_access_healthy_foods_2020             23       0.72
limited_access_healthy_foods_2021             23       0.72
limited_access_healthy_foods_2022             37       1.16
limited_access_healthy_foods_2023             37       1.16
limited_access_healthy_foods_2024             38       1.19

üîç Rows with missing values: 44

,FIPS,State,County,limited_access_healthy_foods_2020,limited_access_healthy_foods_2021,limited_access_healthy_foods_2022,limited_access_healthy_foods_2023,limited_access_healthy_foods_2024,limited_access_healthy_foods_mean
26,01049,AL,DeKalb County,0.021670,0.021670,NaN,NaN,NaN,0.021670
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,NaN,NaN
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,NaN,NaN
86,02158,AK,Kusilvak Census Area,0.418397,0.418397,NaN,NaN,NaN,0.418397
97,02261,AK,Valdez-Cordova Census Area,0.153154,0.153154,0.103446,0.103446,NaN,0.128300

In [99]:
# ==========================================================
# PART 29B: Impute and Recalculate Limited Access to Healthy Foods
# ==========================================================

# üéØ Define columns to impute (using all 5 years: 2020‚Äì2024)
limited_access_healthy_foods_cols = [f'limited_access_healthy_foods_{y}' for y in range(2020, 2025)]  # Using 2020 to 2024

# üßº Impute missing values using state-level means for each year
states = limited_access_healthy_foods['State'].unique()
for state in states:
    state_data = limited_access_healthy_foods[limited_access_healthy_foods['State'] == state]
    for col in limited_access_healthy_foods_cols:
        year_mean = state_data[col].mean(skipna=True)  # Using all 5 years for imputation
        missing_mask = (limited_access_healthy_foods['State'] == state) & (limited_access_healthy_foods[col].isna())
        limited_access_healthy_foods.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation using all 5 years
limited_access_healthy_foods[limited_access_healthy_foods_cols] = limited_access_healthy_foods[limited_access_healthy_foods_cols].apply(pd.to_numeric, errors='coerce')
limited_access_healthy_foods['limited_access_healthy_foods_mean'] = limited_access_healthy_foods[limited_access_healthy_foods_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_limited_access_healthy_foods = pd.DataFrame({
    "Missing Count": limited_access_healthy_foods[limited_access_healthy_foods_cols].isna().sum(),
    "Missing %": (limited_access_healthy_foods[limited_access_healthy_foods_cols].isna().sum() / len(limited_access_healthy_foods) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Limited Access to Healthy Foods (After Imputation)")
print(missing_report_final_limited_access_healthy_foods)

# üëÄ Preview
limited_access_healthy_foods.head()

üìã Final Missing Value Report: Limited Access to Healthy Foods (After Imputation)
                                   Missing Count  Missing %
limited_access_healthy_foods_2020              1       0.03
limited_access_healthy_foods_2021              1       0.03
limited_access_healthy_foods_2022              1       0.03
limited_access_healthy_foods_2023              1       0.03
limited_access_healthy_foods_2024              1       0.03

,FIPS,State,County,limited_access_healthy_foods_2020,limited_access_healthy_foods_2021,limited_access_healthy_foods_2022,limited_access_healthy_foods_2023,limited_access_healthy_foods_2024,limited_access_healthy_foods_mean
0,00000,US,United States,0.059012,0.059012,0.061002,0.061002,0.061002,0.060206
1,01000,AL,Alabama,0.079214,0.079214,0.087605,0.087605,0.087605,0.084249
2,01001,AL,Autauga County,0.119911,0.119911,0.130210,0.130210,0.130210,0.126090
3,01003,AL,Baldwin County,0.054244,0.054244,0.079368,0.079368,0.079368,0.069318
4,01005,AL,Barbour County,0.107397,0.107397,0.104332,0.104332,0.104332,0.105558

üßæ Interpreting Limited Access to Healthy Foods Raw Value:

The Limited Access to Healthy Foods raw value represents the proportion of the population in a given area with limited access to healthy foods like fruits, vegetables, and other nutritious options.
	‚Ä¢	Values range from 0 (no one has limited access) to 1 (everyone has limited access).
	‚Ä¢	For example, a value of 0.079214 for Alabama in 2020 indicates that approximately 7.9% of the population has limited access to healthy foods.

This indicator is important for understanding food insecurity and health disparities in a community. Areas with higher values tend to have fewer grocery stores or longer distances to access healthy foods, which can contribute to poor diet quality and health issues such as obesity or chronic diseases.

In [101]:
# ==========================================================
# PART 30A: Load Life Expectancy raw value and Report Missing
# ==========================================================

def load_life_expectancy_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["life expectancy raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'life_expectancy_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years
life_expectancy_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_life_expectancy_column(file_path, year)
    life_expectancy_dfs.append(df)

# üß© Merge all years
life_expectancy = life_expectancy_dfs[0]
for df in life_expectancy_dfs[1:]:
    life_expectancy = pd.merge(life_expectancy, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
life_expectancy_cols = [f'life_expectancy_{y}' for y in range(2020, 2025)]
life_expectancy[life_expectancy_cols] = life_expectancy[life_expectancy_cols].apply(pd.to_numeric, errors='coerce')
life_expectancy['life_expectancy_mean'] = life_expectancy[life_expectancy_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_life_expectancy = pd.DataFrame({
    "Missing Count": life_expectancy[life_expectancy_cols].isna().sum(),
    "Missing %": (life_expectancy[life_expectancy_cols].isna().sum() / len(life_expectancy) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Life Expectancy, Before Imputation)")
print(missing_report_life_expectancy)

# üîç Show rows with missing values
rows_with_na_life_expectancy = life_expectancy[life_expectancy[life_expectancy_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_life_expectancy)}")
rows_with_na_life_expectancy.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Life Expectancy, Before Imputation)
                      Missing Count  Missing %
life_expectancy_2020             77       2.41
life_expectancy_2021             73       2.28
life_expectancy_2022             74       2.31
life_expectancy_2023             74       2.31
life_expectancy_2024             76       2.38

üîç Rows with missing values: 82

,FIPS,State,County,life_expectancy_2020,life_expectancy_2021,life_expectancy_2022,life_expectancy_2023,life_expectancy_2024,life_expectancy_mean
70,02013,AK,Aleutians East Borough,91.147161,113.462137,112.503856,112.503856,NaN,107.404252
74,02060,AK,Bristol Bay Borough,NaN,NaN,NaN,NaN,NaN,NaN
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,NaN,NaN
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,NaN,NaN
87,02164,AK,Lake and Peninsula Borough,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
# ==========================================================
# PART 30B: Impute and Recalculate Life Expectancy
# ==========================================================

# üéØ Define columns to impute (using all 5 years: 2020‚Äì2024)
life_expectancy_cols = [f'life_expectancy_{y}' for y in range(2020, 2025)]  # Using 2020 to 2024

# üßº Impute missing values using state-level means for each year
states = life_expectancy['State'].unique()
for state in states:
    state_data = life_expectancy[life_expectancy['State'] == state]
    for col in life_expectancy_cols:
        year_mean = state_data[col].mean(skipna=True)  # Using all 5 years for imputation
        missing_mask = (life_expectancy['State'] == state) & (life_expectancy[col].isna())
        life_expectancy.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation using all 5 years
life_expectancy[life_expectancy_cols] = life_expectancy[life_expectancy_cols].apply(pd.to_numeric, errors='coerce')
life_expectancy['life_expectancy_mean'] = life_expectancy[life_expectancy_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_life_expectancy = pd.DataFrame({
    "Missing Count": life_expectancy[life_expectancy_cols].isna().sum(),
    "Missing %": (life_expectancy[life_expectancy_cols].isna().sum() / len(life_expectancy) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Life Expectancy (After Imputation)")
print(missing_report_final_life_expectancy)

# üëÄ Preview
life_expectancy.head()

üìã Final Missing Value Report: Life Expectancy (After Imputation)
                      Missing Count  Missing %
life_expectancy_2020              1       0.03
life_expectancy_2021              1       0.03
life_expectancy_2022              1       0.03
life_expectancy_2023              1       0.03
life_expectancy_2024              1       0.03

,FIPS,State,County,life_expectancy_2020,life_expectancy_2021,life_expectancy_2022,life_expectancy_2023,life_expectancy_2024,life_expectancy_mean
0,00000,US,United States,79.089130,79.173088,78.528895,78.528895,77.585337,78.581069
1,01000,AL,Alabama,75.416194,75.548075,74.835949,74.835949,73.707861,74.868806
2,01001,AL,Autauga County,76.879477,77.162581,76.585650,76.585650,75.263497,76.495371
3,01003,AL,Baldwin County,78.450258,78.213405,77.724729,77.724729,76.738314,77.770287
4,01005,AL,Barbour County,75.341935,74.054741,72.867210,72.867210,72.377024,73.501624

üßæ Interpreting Life Expectancy Raw Value:

The Life Expectancy raw value represents the average life expectancy for individuals in a given county or area.
	‚Ä¢	Values are in years (e.g., 79.09 years for the United States in 2020).
	‚Ä¢	Higher values indicate longer life expectancy, typically linked to better health outcomes and higher quality of life.

This indicator is important for understanding overall health and well-being in a community. It reflects the general health of the population and can be used to inform public health initiatives and healthcare policy.

In [104]:
# ==========================================================
# PART 31A: Load Motor Vehicle Crash Deaths raw value and Report Missing
# ==========================================================

def load_motor_vehicle_crash_deaths_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["motor vehicle crash deaths raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'motor_vehicle_crash_deaths_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years
motor_vehicle_crash_deaths_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_motor_vehicle_crash_deaths_column(file_path, year)
    motor_vehicle_crash_deaths_dfs.append(df)

# üß© Merge all years
motor_vehicle_crash_deaths = motor_vehicle_crash_deaths_dfs[0]
for df in motor_vehicle_crash_deaths_dfs[1:]:
    motor_vehicle_crash_deaths = pd.merge(motor_vehicle_crash_deaths, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
motor_vehicle_crash_deaths_cols = [f'motor_vehicle_crash_deaths_{y}' for y in range(2020, 2025)]
motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols] = motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols].apply(pd.to_numeric, errors='coerce')
motor_vehicle_crash_deaths['motor_vehicle_crash_deaths_mean'] = motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols].mean(axis=1, skipna=True)

# üìã Report missing values
missing_report_motor_vehicle_crash_deaths = pd.DataFrame({
    "Missing Count": motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols].isna().sum(),
    "Missing %": (motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols].isna().sum() / len(motor_vehicle_crash_deaths) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Motor Vehicle Crash Deaths, Before Imputation)")
print(missing_report_motor_vehicle_crash_deaths)

# üîç Show rows with missing values
rows_with_na_motor_vehicle_crash_deaths = motor_vehicle_crash_deaths[motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_motor_vehicle_crash_deaths)}")
rows_with_na_motor_vehicle_crash_deaths.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Motor Vehicle Crash Deaths, Before Imputation)
                                 Missing Count  Missing %
motor_vehicle_crash_deaths_2020            448      14.01
motor_vehicle_crash_deaths_2021            456      14.26
motor_vehicle_crash_deaths_2022            455      14.23
motor_vehicle_crash_deaths_2023            455      14.23
motor_vehicle_crash_deaths_2024            458      14.32

üîç Rows with missing values: 552

,FIPS,State,County,motor_vehicle_crash_deaths_2020,motor_vehicle_crash_deaths_2021,motor_vehicle_crash_deaths_2022,motor_vehicle_crash_deaths_2023,motor_vehicle_crash_deaths_2024,motor_vehicle_crash_deaths_mean
70,02013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,NaN,NaN
71,02016,AK,Aleutians West Census Area,NaN,NaN,NaN,NaN,NaN,NaN
74,02060,AK,Bristol Bay Borough,NaN,NaN,NaN,NaN,NaN,NaN
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,NaN,NaN
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
# ==========================================================
# PART 31B: Impute and Recalculate Motor Vehicle Crash Deaths
# ==========================================================

# üéØ Define columns to impute (using all 5 years: 2020‚Äì2024)
motor_vehicle_crash_deaths_cols = [f'motor_vehicle_crash_deaths_{y}' for y in range(2020, 2025)]  # Using 2020 to 2024

# üßº Impute missing values using state-level means for each year
states = motor_vehicle_crash_deaths['State'].unique()
for state in states:
    state_data = motor_vehicle_crash_deaths[motor_vehicle_crash_deaths['State'] == state]
    for col in motor_vehicle_crash_deaths_cols:
        year_mean = state_data[col].mean(skipna=True)  # Using all 5 years for imputation
        missing_mask = (motor_vehicle_crash_deaths['State'] == state) & (motor_vehicle_crash_deaths[col].isna())
        motor_vehicle_crash_deaths.loc[missing_mask, col] = year_mean

# üîÅ Recalculate mean after imputation using all 5 years
motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols] = motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols].apply(pd.to_numeric, errors='coerce')
motor_vehicle_crash_deaths['motor_vehicle_crash_deaths_mean'] = motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols].mean(axis=1, skipna=True)

# üìã Final missing value report
missing_report_final_motor_vehicle_crash_deaths = pd.DataFrame({
    "Missing Count": motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols].isna().sum(),
    "Missing %": (motor_vehicle_crash_deaths[motor_vehicle_crash_deaths_cols].isna().sum() / len(motor_vehicle_crash_deaths) * 100).round(2)
})
print("\nüìã Final Missing Value Report: Motor Vehicle Crash Deaths (After Imputation)")
print(missing_report_final_motor_vehicle_crash_deaths)

# üëÄ Preview
motor_vehicle_crash_deaths.head()

üìã Final Missing Value Report: Motor Vehicle Crash Deaths (After Imputation)
                                 Missing Count  Missing %
motor_vehicle_crash_deaths_2020              1       0.03
motor_vehicle_crash_deaths_2021              1       0.03
motor_vehicle_crash_deaths_2022              1       0.03
motor_vehicle_crash_deaths_2023              1       0.03
motor_vehicle_crash_deaths_2024              1       0.03

,FIPS,State,County,motor_vehicle_crash_deaths_2020,motor_vehicle_crash_deaths_2021,motor_vehicle_crash_deaths_2022,motor_vehicle_crash_deaths_2023,motor_vehicle_crash_deaths_2024,motor_vehicle_crash_deaths_mean
0,00000,US,United States,11.308831,11.354834,11.591311,11.591311,12.035415,11.576341
1,01000,AL,Alabama,19.649886,20.040397,20.205515,20.205515,20.588369,20.137936
2,01001,AL,Autauga County,19.328751,19.826046,19.009600,19.009600,18.067215,19.048242
3,01003,AL,Baldwin County,15.811239,17.238938,16.849943,16.849943,15.833332,16.516679
4,01005,AL,Barbour County,22.854780,26.482174,27.969368,27.969368,29.404447,26.936027

üßæ Interpreting Motor Vehicle Crash Deaths Raw Value:

The Motor Vehicle Crash Deaths raw value represents the rate of fatalities from motor vehicle crashes per 100,000 people in a specific county or area for each year.
	‚Ä¢	Values are typically expressed per 100,000 people (e.g., 19.649886 for Alabama in 2020 means that 19.65 deaths occurred per 100,000 people).
	‚Ä¢	Higher values indicate more motor vehicle crash fatalities per capita, which may suggest poor road safety, high traffic volume, or lack of enforcement.

This metric is critical for evaluating road safety policies, traffic management, and emergency response preparedness. It reflects how effectively the region is managing traffic-related safety, and is crucial for public health and transportation planning.

In [107]:
# ==========================================================
# PART 32A: Load Suicides Raw Value and Report Missing (Reworked)
# ==========================================================

def load_suicides_raw_value_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Suicides raw value"]  # Exact column name from your dataset
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'suicides_raw_value_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Suicides raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
suicides_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_suicides_raw_value_column(file_path, year)
    suicides_dfs.append(df)

# üß© Merge all years together
suicides_raw_value = suicides_dfs[0]
for df in suicides_dfs[1:]:
    suicides_raw_value = pd.merge(suicides_raw_value, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
suicides_cols = [f'suicides_raw_value_{y}' for y in range(2020, 2025)]
suicides_raw_value[suicides_cols] = suicides_raw_value[suicides_cols].apply(pd.to_numeric, errors='coerce')
suicides_raw_value['suicides_mean'] = suicides_raw_value[suicides_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_suicides_raw_value = pd.DataFrame({
    "Missing Count": suicides_raw_value[suicides_cols].isna().sum(),
    "Missing %": (suicides_raw_value[suicides_cols].isna().sum() / len(suicides_raw_value) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Suicides Raw Value, Before Imputation)")
print(missing_report_suicides_raw_value)

# üîç Show rows with missing values (for further inspection)
rows_with_na_suicides = suicides_raw_value[suicides_raw_value[suicides_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_suicides)}")
rows_with_na_suicides.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Suicides Raw Value, Before Imputation)
                         Missing Count  Missing %
suicides_raw_value_2020            767      23.98
suicides_raw_value_2021            750      23.45
suicides_raw_value_2022            713      22.30
suicides_raw_value_2023            713      22.30
suicides_raw_value_2024            719      22.48

üîç Rows with missing values: 887

,FIPS,State,County,suicides_raw_value_2020,suicides_raw_value_2021,suicides_raw_value_2022,suicides_raw_value_2023,suicides_raw_value_2024,suicides_mean
7,01011,AL,Bullock County,NaN,NaN,NaN,NaN,NaN,NaN
13,01023,AL,Choctaw County,NaN,NaN,NaN,NaN,NaN,NaN
19,01035,AL,Conecuh County,NaN,NaN,NaN,NaN,NaN,NaN
20,01037,AL,Coosa County,17.825599,NaN,NaN,NaN,NaN,17.825599
22,01041,AL,Crenshaw County,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
# ==========================================================
# PART 32B: Impute and Recalculate Suicides Raw Value (After Imputation)
# ==========================================================

def impute_suicides_raw_value(suicides_raw_value):
    # Define the columns for suicides raw value (2020-2024)
    suicides_cols = ['suicides_raw_value_2020', 'suicides_raw_value_2021', 
                     'suicides_raw_value_2022', 'suicides_raw_value_2023', 'suicides_raw_value_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = suicides_raw_value['State'].unique()
    for state in states:
        state_data = suicides_raw_value[suicides_raw_value['State'] == state]
        for col in suicides_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (suicides_raw_value['State'] == state) & (suicides_raw_value[col].isna())
            suicides_raw_value.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    suicides_raw_value[suicides_cols] = suicides_raw_value[suicides_cols].apply(pd.to_numeric, errors='coerce')
    suicides_raw_value['suicides_mean'] = suicides_raw_value[suicides_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": suicides_raw_value[suicides_cols].isna().sum(),
        "Missing %": (suicides_raw_value[suicides_cols].isna().sum() / len(suicides_raw_value) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Suicides Raw Value (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the final DataFrame
    print("\nüëÄ Preview of the Final Data (Head):")
    return suicides_raw_value.head()  # Final name, no 'imputed'

# Example usage (assuming suicides_raw_value is the merged data for suicides)
suicides_raw_value_final = impute_suicides_raw_value(suicides_raw_value)

suicides_raw_value_final.head()  # Preview the final DataFrame

üìã Final Missing Value Report: Suicides Raw Value (After Imputation)
                         Missing Count  Missing %
suicides_raw_value_2020              1       0.03
suicides_raw_value_2021              1       0.03
suicides_raw_value_2022              1       0.03
suicides_raw_value_2023              1       0.03
suicides_raw_value_2024              1       0.03

üëÄ Preview of the Final Data (Head):

,FIPS,State,County,suicides_raw_value_2020,suicides_raw_value_2021,suicides_raw_value_2022,suicides_raw_value_2023,suicides_raw_value_2024,suicides_mean
0,00000,US,United States,13.580564,13.776778,13.818283,13.818283,13.942028,13.787187
1,01000,AL,Alabama,15.638260,15.988114,16.200670,16.200670,16.234752,16.052493
2,01001,AL,Autauga County,18.145295,18.483525,17.737296,17.737296,17.457479,17.912179
3,01003,AL,Baldwin County,19.377511,19.287661,19.645883,19.645883,18.790126,19.349413
4,01005,AL,Barbour County,12.836104,11.325918,14.267052,14.267052,13.426810,13.224587

üßæ Interpreting Suicides Raw Value Example (11.308831):

The Suicides raw value represents the rate of suicides per 100,000 people for a specific area and year.
	‚Ä¢	11.308831 for United States in 2020 means that there were 11.31 suicides per 100,000 people in the United States in that year.
	‚Ä¢	Values typically indicate the prevalence of suicides in the population, with higher values suggesting a higher suicide rate.

This metric is important for understanding the mental health landscape and assessing the effectiveness of suicide prevention efforts.

In [110]:
# ==========================================================
# PART 33A: Load Drug Overdose Deaths Raw Value and Report Missing
# ==========================================================

def load_drug_overdose_deaths_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Drug overdose deaths raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'drug_overdose_deaths_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Drug overdose deaths raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
drug_overdose_deaths_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_drug_overdose_deaths_column(file_path, year)
    drug_overdose_deaths_dfs.append(df)

# üß© Merge all years together
drug_overdose_deaths = drug_overdose_deaths_dfs[0]
for df in drug_overdose_deaths_dfs[1:]:
    drug_overdose_deaths = pd.merge(drug_overdose_deaths, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
drug_overdose_deaths_cols = [f'drug_overdose_deaths_{y}' for y in range(2020, 2025)]
drug_overdose_deaths[drug_overdose_deaths_cols] = drug_overdose_deaths[drug_overdose_deaths_cols].apply(pd.to_numeric, errors='coerce')
drug_overdose_deaths['drug_overdose_deaths_mean'] = drug_overdose_deaths[drug_overdose_deaths_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_drug_overdose_deaths = pd.DataFrame({
    "Missing Count": drug_overdose_deaths[drug_overdose_deaths_cols].isna().sum(),
    "Missing %": (drug_overdose_deaths[drug_overdose_deaths_cols].isna().sum() / len(drug_overdose_deaths) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Drug Overdose Deaths, Before Imputation)")
print(missing_report_drug_overdose_deaths)

# üîç Show rows with missing values (for further inspection)
rows_with_na_drug_overdose_deaths = drug_overdose_deaths[drug_overdose_deaths[drug_overdose_deaths_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_drug_overdose_deaths)}")
rows_with_na_drug_overdose_deaths.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Drug Overdose Deaths, Before Imputation)
                           Missing Count  Missing %
drug_overdose_deaths_2020           1424      44.53
drug_overdose_deaths_2021           1407      44.00
drug_overdose_deaths_2022           1349      42.18
drug_overdose_deaths_2023           1349      42.18
drug_overdose_deaths_2024           1247      38.99

üîç Rows with missing values: 1547

,FIPS,State,County,drug_overdose_deaths_2020,drug_overdose_deaths_2021,drug_overdose_deaths_2022,drug_overdose_deaths_2023,drug_overdose_deaths_2024,drug_overdose_deaths_mean
4,01005,AL,Barbour County,NaN,NaN,NaN,NaN,NaN,NaN
7,01011,AL,Bullock County,NaN,NaN,NaN,NaN,NaN,NaN
8,01013,AL,Butler County,NaN,NaN,NaN,NaN,17.290269,17.290269
13,01023,AL,Choctaw County,NaN,NaN,NaN,NaN,NaN,NaN
14,01025,AL,Clarke County,NaN,15.357766,14.117713,14.117713,NaN,14.531064

Note: Due to the high number of missing values across the years (especially in 2020‚Äì2024), data imputation will not be performed. The missing values are significant enough to affect the reliability of the imputation process.

In [112]:
# ==========================================================
# PART 34A: Load Insufficient Sleep Raw Value and Report Missing
# ==========================================================

def load_insufficient_sleep_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Insufficient sleep raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'insufficient_sleep_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Insufficient sleep raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
insufficient_sleep_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_insufficient_sleep_column(file_path, year)
    insufficient_sleep_dfs.append(df)

# üß© Merge all years together
insufficient_sleep_raw_value = insufficient_sleep_dfs[0]
for df in insufficient_sleep_dfs[1:]:
    insufficient_sleep_raw_value = pd.merge(insufficient_sleep_raw_value, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
insufficient_sleep_cols = [f'insufficient_sleep_{y}' for y in range(2020, 2025)]
insufficient_sleep_raw_value[insufficient_sleep_cols] = insufficient_sleep_raw_value[insufficient_sleep_cols].apply(pd.to_numeric, errors='coerce')
insufficient_sleep_raw_value['insufficient_sleep_mean'] = insufficient_sleep_raw_value[insufficient_sleep_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_insufficient_sleep = pd.DataFrame({
    "Missing Count": insufficient_sleep_raw_value[insufficient_sleep_cols].isna().sum(),
    "Missing %": (insufficient_sleep_raw_value[insufficient_sleep_cols].isna().sum() / len(insufficient_sleep_raw_value) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Insufficient Sleep Raw Value, Before Imputation)")
print(missing_report_insufficient_sleep)

# üîç Show rows with missing values (for further inspection)
rows_with_na_insufficient_sleep = insufficient_sleep_raw_value[insufficient_sleep_raw_value[insufficient_sleep_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_insufficient_sleep)}")
rows_with_na_insufficient_sleep.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Insufficient Sleep Raw Value, Before Imputation)
                         Missing Count  Missing %
insufficient_sleep_2020              4       0.13
insufficient_sleep_2021              4       0.13
insufficient_sleep_2022              4       0.13
insufficient_sleep_2023              6       0.19
insufficient_sleep_2024              6       0.19

üîç Rows with missing values: 7

,FIPS,State,County,insufficient_sleep_2020,insufficient_sleep_2021,insufficient_sleep_2022,insufficient_sleep_2023,insufficient_sleep_2024,insufficient_sleep_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,NaN,NaN
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,NaN,NaN
97,02261,AK,Valdez-Cordova Census Area,0.297950,0.310177,0.310177,NaN,NaN,0.306101
1164,22059,LA,La Salle Parish,0.364167,0.376511,0.376511,NaN,NaN,0.372396
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,0.368,0.368,0.368000

In [113]:
# ==========================================================
# PART 34B: Impute and Recalculate Insufficient Sleep Raw Value (After Imputation)
# ==========================================================

def impute_insufficient_sleep(df):
    # Define the columns for insufficient sleep (2020-2024)
    insufficient_sleep_cols = ['insufficient_sleep_2020', 'insufficient_sleep_2021', 
                               'insufficient_sleep_2022', 'insufficient_sleep_2023', 'insufficient_sleep_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = df['State'].unique()
    for state in states:
        state_data = df[df['State'] == state]
        for col in insufficient_sleep_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (df['State'] == state) & (df[col].isna())
            df.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    df[insufficient_sleep_cols] = df[insufficient_sleep_cols].apply(pd.to_numeric, errors='coerce')
    df['insufficient_sleep_mean'] = df[insufficient_sleep_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": df[insufficient_sleep_cols].isna().sum(),
        "Missing %": (df[insufficient_sleep_cols].isna().sum() / len(df) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Insufficient Sleep Raw Value (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the final DataFrame
    print("\nüëÄ Preview of the Final Data (Head):")
    return df.head()  # Final name, no 'imputed'

# Example usage (assuming insufficient_sleep_raw_value is the merged data for insufficient sleep)
insufficient_sleep_raw_value_final = impute_insufficient_sleep(insufficient_sleep_raw_value)

insufficient_sleep_raw_value_final.head()  # Preview the final DataFrame

üìã Final Missing Value Report: Insufficient Sleep Raw Value (After Imputation)
                         Missing Count  Missing %
insufficient_sleep_2020              1       0.03
insufficient_sleep_2021              1       0.03
insufficient_sleep_2022              1       0.03
insufficient_sleep_2023              1       0.03
insufficient_sleep_2024              1       0.03

üëÄ Preview of the Final Data (Head):

,FIPS,State,County,insufficient_sleep_2020,insufficient_sleep_2021,insufficient_sleep_2022,insufficient_sleep_2023,insufficient_sleep_2024,insufficient_sleep_mean
0,00000,US,United States,0.338950,0.352186,0.352765,0.33000,0.330131,0.340806
1,01000,AL,Alabama,0.377210,0.396275,0.396275,0.39243,0.392430,0.390924
2,01001,AL,Autauga County,0.359054,0.384433,0.384433,0.37500,0.375000,0.375584
3,01003,AL,Baldwin County,0.333059,0.363780,0.363780,0.35100,0.351000,0.352524
4,01005,AL,Barbour County,0.385632,0.408896,0.408896,0.43900,0.439000,0.416285

üßæ Interpreting Insufficient Sleep Raw Value:

The Insufficient Sleep Raw Value represents the percentage of adults in a given county or area who report insufficient sleep, based on surveys or health assessments.
	‚Ä¢	Values are typically expressed as a percentage of the population (e.g., 0.33 for Baldwin County in 2020 means that 33% of the population reported insufficient sleep).
	‚Ä¢	Higher values suggest that a larger portion of the population is experiencing insufficient sleep, which may be a sign of public health issues like stress, poor health, or inadequate access to healthcare.
	‚Ä¢	Lower values suggest fewer individuals are experiencing insufficient sleep, which may indicate a healthier or better-rested population.

This metric is important for assessing the overall well-being of the population, identifying areas where mental health and public health interventions may be needed, and understanding the links between sleep deprivation and broader health outcomes such as productivity, quality of life, and risk for chronic diseases.

In [115]:
# ==========================================================
# PART 35A: Load HIV Prevalence Raw Value and Report Missing
# ==========================================================

def load_hiv_prevalence_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["HIV prevalence raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'hiv_prevalence_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'HIV prevalence raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
hiv_prevalence_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_hiv_prevalence_column(file_path, year)
    hiv_prevalence_dfs.append(df)

# üß© Merge all years together
hiv_prevalence_raw_value = hiv_prevalence_dfs[0]
for df in hiv_prevalence_dfs[1:]:
    hiv_prevalence_raw_value = pd.merge(hiv_prevalence_raw_value, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
hiv_prevalence_cols = [f'hiv_prevalence_{y}' for y in range(2020, 2025)]
hiv_prevalence_raw_value[hiv_prevalence_cols] = hiv_prevalence_raw_value[hiv_prevalence_cols].apply(pd.to_numeric, errors='coerce')
hiv_prevalence_raw_value['hiv_prevalence_mean'] = hiv_prevalence_raw_value[hiv_prevalence_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_hiv_prevalence = pd.DataFrame({
    "Missing Count": hiv_prevalence_raw_value[hiv_prevalence_cols].isna().sum(),
    "Missing %": (hiv_prevalence_raw_value[hiv_prevalence_cols].isna().sum() / len(hiv_prevalence_raw_value) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (HIV Prevalence Raw Value, Before Imputation)")
print(missing_report_hiv_prevalence)

# üîç Show rows with missing values (for further inspection)
rows_with_na_hiv_prevalence = hiv_prevalence_raw_value[hiv_prevalence_raw_value[hiv_prevalence_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_hiv_prevalence)}")
rows_with_na_hiv_prevalence.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (HIV Prevalence Raw Value, Before Imputation)
                     Missing Count  Missing %
hiv_prevalence_2020            864      27.02
hiv_prevalence_2021            757      23.67
hiv_prevalence_2022            463      14.48
hiv_prevalence_2023            463      14.48
hiv_prevalence_2024            458      14.32

üîç Rows with missing values: 1057

,FIPS,State,County,hiv_prevalence_2020,hiv_prevalence_2021,hiv_prevalence_2022,hiv_prevalence_2023,hiv_prevalence_2024,hiv_prevalence_mean
70,02013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,NaN,NaN
71,02016,AK,Aleutians West Census Area,NaN,NaN,NaN,NaN,NaN,NaN
72,02020,AK,Anchorage Borough,NaN,NaN,NaN,NaN,NaN,NaN
73,02050,AK,Bethel Census Area,NaN,NaN,NaN,NaN,NaN,NaN
74,02060,AK,Bristol Bay Borough,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
# ==========================================================
# PART 35B: Impute and Recalculate HIV Prevalence Raw Value (After Imputation)
# ==========================================================

def impute_hiv_prevalence(df):
    # Define the columns for HIV prevalence (2020-2024)
    hiv_prevalence_cols = ['hiv_prevalence_2020', 'hiv_prevalence_2021', 
                           'hiv_prevalence_2022', 'hiv_prevalence_2023', 'hiv_prevalence_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = df['State'].unique()
    for state in states:
        state_data = df[df['State'] == state]
        for col in hiv_prevalence_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (df['State'] == state) & (df[col].isna())
            df.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    df[hiv_prevalence_cols] = df[hiv_prevalence_cols].apply(pd.to_numeric, errors='coerce')
    df['hiv_prevalence_mean'] = df[hiv_prevalence_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": df[hiv_prevalence_cols].isna().sum(),
        "Missing %": (df[hiv_prevalence_cols].isna().sum() / len(df) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: HIV Prevalence Raw Value (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the final DataFrame
    print("\nüëÄ Preview of the Final Data (Head):")
    return df.head()  # Final name, no 'imputed'

# Example usage (assuming hiv_prevalence_raw_value is the merged data for HIV prevalence)
hiv_prevalence_raw_value_final = impute_hiv_prevalence(hiv_prevalence_raw_value)

hiv_prevalence_raw_value_final.head()  # Preview the final DataFrame

üìã Final Missing Value Report: HIV Prevalence Raw Value (After Imputation)
                     Missing Count  Missing %
hiv_prevalence_2020             69       2.16
hiv_prevalence_2021              1       0.03
hiv_prevalence_2022              1       0.03
hiv_prevalence_2023              1       0.03
hiv_prevalence_2024              1       0.03

üëÄ Preview of the Final Data (Head):

,FIPS,State,County,hiv_prevalence_2020,hiv_prevalence_2021,hiv_prevalence_2022,hiv_prevalence_2023,hiv_prevalence_2024,hiv_prevalence_mean
0,00000,US,United States,365.5,372.8,378.0,379.7,382.2,375.64
1,01000,AL,Alabama,309.9,330.4,336.4,341.6,339.7,331.60
2,01001,AL,Autauga County,219.1,230.2,222.1,242.5,218.0,226.38
3,01003,AL,Baldwin County,166.5,169.3,172.9,176.1,174.3,171.82
4,01005,AL,Barbour County,420.6,471.0,498.2,456.5,513.7,472.00

üßæ Interpreting HIV Prevalence Raw Value:

The HIV Prevalence Raw Value represents the number of people living with HIV per 100,000 people in a given county or state for each year.
	‚Ä¢	Values are expressed per 100,000 people, so 365.5 for the United States in 2020 means that there were 365.5 people per 100,000 living with HIV in that year.
	‚Ä¢	Higher values indicate a higher prevalence of HIV in the population, which can suggest areas with more significant public health challenges or where HIV transmission is more prevalent.
	‚Ä¢	Lower values indicate fewer people living with HIV, potentially reflecting successful prevention efforts, better access to healthcare, or lower rates of transmission.

This metric is crucial for understanding the distribution of HIV across regions, identifying high-risk areas, and evaluating the effectiveness of HIV prevention, testing, and treatment programs. It‚Äôs an important indicator for public health officials and policymakers to focus resources on areas with higher HIV burdens.

In [118]:
# ==========================================================
# PART 37A: Load and Report Missing for Frequent Physical Distress Raw Value
# ==========================================================

def load_frequent_physical_distress_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Frequent physical distress raw value"]  # Exact column name from your dataset
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'frequent_physical_distress_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Frequent physical distress raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
frequent_physical_distress_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_frequent_physical_distress_column(file_path, year)
    frequent_physical_distress_dfs.append(df)

# üß© Merge all years together
frequent_physical_distress = frequent_physical_distress_dfs[0]
for df in frequent_physical_distress_dfs[1:]:
    frequent_physical_distress = pd.merge(frequent_physical_distress, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
physical_distress_cols = [f'frequent_physical_distress_{y}' for y in range(2020, 2025)]
frequent_physical_distress[physical_distress_cols] = frequent_physical_distress[physical_distress_cols].apply(pd.to_numeric, errors='coerce')
frequent_physical_distress['physical_distress_mean'] = frequent_physical_distress[physical_distress_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_physical_distress = pd.DataFrame({
    "Missing Count": frequent_physical_distress[physical_distress_cols].isna().sum(),
    "Missing %": (frequent_physical_distress[physical_distress_cols].isna().sum() / len(frequent_physical_distress) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Frequent Physical Distress, Before Imputation)")
print(missing_report_physical_distress)

# üîç Show rows with missing values (for further inspection)
rows_with_na_physical_distress = frequent_physical_distress[frequent_physical_distress[physical_distress_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_physical_distress)}")
rows_with_na_physical_distress.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Frequent Physical Distress, Before Imputation)
                                 Missing Count  Missing %
frequent_physical_distress_2020              4       0.13
frequent_physical_distress_2021              4       0.13
frequent_physical_distress_2022              4       0.13
frequent_physical_distress_2023              6       0.19
frequent_physical_distress_2024              3       0.09

üîç Rows with missing values: 7

,FIPS,State,County,frequent_physical_distress_2020,frequent_physical_distress_2021,frequent_physical_distress_2022,frequent_physical_distress_2023,frequent_physical_distress_2024,physical_distress_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.101,0.101000
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.119,0.119000
97,02261,AK,Valdez-Cordova Census Area,0.093447,0.110757,0.107,NaN,NaN,0.103735
1164,22059,LA,La Salle Parish,0.149774,0.157263,0.162,NaN,NaN,0.156346
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,0.126,0.132,0.129000

In [119]:
# ==========================================================
# PART 37B: Impute and Recalculate Frequent Physical Distress Raw Value (After Imputation)
# ==========================================================

def impute_frequent_physical_distress(df):
    # Define the columns for frequent physical distress (2020-2024)
    physical_distress_cols = ['frequent_physical_distress_2020', 'frequent_physical_distress_2021', 
                              'frequent_physical_distress_2022', 'frequent_physical_distress_2023', 'frequent_physical_distress_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = df['State'].unique()
    for state in states:
        state_data = df[df['State'] == state]
        for col in physical_distress_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (df['State'] == state) & (df[col].isna())
            df.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    df[physical_distress_cols] = df[physical_distress_cols].apply(pd.to_numeric, errors='coerce')
    df['physical_distress_mean'] = df[physical_distress_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": df[physical_distress_cols].isna().sum(),
        "Missing %": (df[physical_distress_cols].isna().sum() / len(df) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Frequent Physical Distress Raw Value (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the final DataFrame
    print("\nüëÄ Preview of the Final Data (Head):")
    return df.head()

# Example usage (assuming frequent_physical_distress is the merged data for frequent physical distress)
frequent_physical_distress_final = impute_frequent_physical_distress(frequent_physical_distress)

frequent_physical_distress_final.head()  # Preview the final DataFrame

üìã Final Missing Value Report: Frequent Physical Distress Raw Value (After Imputation)
                                 Missing Count  Missing %
frequent_physical_distress_2020              1       0.03
frequent_physical_distress_2021              1       0.03
frequent_physical_distress_2022              1       0.03
frequent_physical_distress_2023              1       0.03
frequent_physical_distress_2024              1       0.03

üëÄ Preview of the Final Data (Head):

,FIPS,State,County,frequent_physical_distress_2020,frequent_physical_distress_2021,frequent_physical_distress_2022,frequent_physical_distress_2023,frequent_physical_distress_2024,physical_distress_mean
0,00000,US,United States,0.115084,0.114199,0.116982,0.090000,0.102809,0.107815
1,01000,AL,Alabama,0.158269,0.140394,0.152785,0.110774,0.123667,0.137178
2,01001,AL,Autauga County,0.136852,0.132530,0.142000,0.107000,0.117000,0.127076
3,01003,AL,Baldwin County,0.124801,0.116116,0.125000,0.099000,0.110000,0.114983
4,01005,AL,Barbour County,0.171849,0.181321,0.191000,0.149000,0.158000,0.170234

üßæ Interpreting Frequent Physical Distress Raw Value:

The Frequent Physical Distress Raw Value represents the percentage of individuals in a specific area (county, state, or the U.S.) who report experiencing frequent physical distress, such as pain, illness, or other chronic conditions that impair daily activities.
	‚Ä¢	Values are expressed as percentages. For example, 0.115084 for the United States in 2020 means that approximately 11.5% of the population in the U.S. reported experiencing frequent physical distress that year.
	‚Ä¢	Higher values reflect a larger percentage of the population experiencing health issues, potentially indicating poor access to healthcare, higher rates of chronic diseases, or socioeconomic factors that affect health.
	‚Ä¢	Lower values suggest fewer individuals experiencing frequent physical distress, which may reflect a healthier population or better healthcare access.

This metric is useful for understanding public health trends, especially concerning chronic diseases or conditions that affect people‚Äôs ability to engage in daily activities. High values in this metric can indicate areas where health interventions or public health resources are most needed.

In [121]:
# ==========================================================
# PART 38A: Load and Report Missing for Poor or Fair Health Raw Value
# ==========================================================

def load_poor_or_fair_health_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Poor or fair health raw value"]  # Exact column name from your dataset
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'poor_or_fair_health_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Poor or fair health raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
poor_or_fair_health_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_poor_or_fair_health_column(file_path, year)
    poor_or_fair_health_dfs.append(df)

# üß© Merge all years together
poor_or_fair_health = poor_or_fair_health_dfs[0]
for df in poor_or_fair_health_dfs[1:]:
    poor_or_fair_health = pd.merge(poor_or_fair_health, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
health_cols = [f'poor_or_fair_health_{y}' for y in range(2020, 2025)]
poor_or_fair_health[health_cols] = poor_or_fair_health[health_cols].apply(pd.to_numeric, errors='coerce')
poor_or_fair_health['poor_or_fair_health_mean'] = poor_or_fair_health[health_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_health = pd.DataFrame({
    "Missing Count": poor_or_fair_health[health_cols].isna().sum(),
    "Missing %": (poor_or_fair_health[health_cols].isna().sum() / len(poor_or_fair_health) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Poor or Fair Health, Before Imputation)")
print(missing_report_health)

# üîç Show rows with missing values (for further inspection)
rows_with_na_health = poor_or_fair_health[poor_or_fair_health[health_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_health)}")
rows_with_na_health.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Poor or Fair Health, Before Imputation)
                          Missing Count  Missing %
poor_or_fair_health_2020              4       0.13
poor_or_fair_health_2021              4       0.13
poor_or_fair_health_2022              4       0.13
poor_or_fair_health_2023              6       0.19
poor_or_fair_health_2024              3       0.09

üîç Rows with missing values: 7

,FIPS,State,County,poor_or_fair_health_2020,poor_or_fair_health_2021,poor_or_fair_health_2022,poor_or_fair_health_2023,poor_or_fair_health_2024,poor_or_fair_health_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.128,0.128000
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.158,0.158000
97,02261,AK,Valdez-Cordova Census Area,0.122106,0.138782,0.156,NaN,NaN,0.138962
1164,22059,LA,La Salle Parish,0.216642,0.245029,0.253,NaN,NaN,0.238224
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,0.193,0.195,0.194000

In [122]:
# ==========================================================
# PART 38B: Impute and Recalculate Poor or Fair Health Raw Value (After Imputation)
# ==========================================================

def impute_poor_or_fair_health(poor_or_fair_health):
    # Define the columns for Poor or Fair Health Raw Value (2020-2024)
    health_cols = ['poor_or_fair_health_2020', 'poor_or_fair_health_2021', 
                   'poor_or_fair_health_2022', 'poor_or_fair_health_2023', 'poor_or_fair_health_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = poor_or_fair_health['State'].unique()
    for state in states:
        state_data = poor_or_fair_health[poor_or_fair_health['State'] == state]
        for col in health_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (poor_or_fair_health['State'] == state) & (poor_or_fair_health[col].isna())
            poor_or_fair_health.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    poor_or_fair_health[health_cols] = poor_or_fair_health[health_cols].apply(pd.to_numeric, errors='coerce')
    poor_or_fair_health['poor_or_fair_health_mean'] = poor_or_fair_health[health_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": poor_or_fair_health[health_cols].isna().sum(),
        "Missing %": (poor_or_fair_health[health_cols].isna().sum() / len(poor_or_fair_health) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Poor or Fair Health (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the imputed DataFrame
    print("\nüëÄ Preview of the Imputed Data (Head):")
    return poor_or_fair_health.head()

# Example usage (assuming poor_or_fair_health is the merged data for poor or fair health)
poor_or_fair_health_imputed = impute_poor_or_fair_health(poor_or_fair_health)

poor_or_fair_health_imputed.head()  # Preview the result after imputation

üìã Final Missing Value Report: Poor or Fair Health (After Imputation)
                          Missing Count  Missing %
poor_or_fair_health_2020              1       0.03
poor_or_fair_health_2021              1       0.03
poor_or_fair_health_2022              1       0.03
poor_or_fair_health_2023              1       0.03
poor_or_fair_health_2024              1       0.03

üëÄ Preview of the Imputed Data (Head):

,FIPS,State,County,poor_or_fair_health_2020,poor_or_fair_health_2021,poor_or_fair_health_2022,poor_or_fair_health_2023,poor_or_fair_health_2024,poor_or_fair_health_mean
0,00000,US,United States,0.171987,0.165096,0.171052,0.120,0.142,0.154027
1,01000,AL,Alabama,0.220287,0.213758,0.214102,0.189,0.178,0.203029
2,01001,AL,Autauga County,0.208830,0.198392,0.201000,0.169,0.173,0.190044
3,01003,AL,Baldwin County,0.175091,0.164607,0.172000,0.149,0.152,0.162540
4,01005,AL,Barbour County,0.295918,0.298415,0.311000,0.275,0.273,0.290667

üßæ Interpreting Poor or Fair Health Raw Value:

The Poor or Fair Health Raw Value represents the percentage of individuals in a specific area (county, state, or U.S.) who report their health as poor or fair, reflecting a lower health self-assessment.
	‚Ä¢	Values are expressed as percentages. For example, 0.171987 for the United States in 2020 means approximately 17.2% of the U.S. population reported poor or fair health that year.
	‚Ä¢	Higher values indicate a higher percentage of the population is reporting poor or fair health, which might point to higher rates of chronic diseases, inadequate healthcare access, or socioeconomic challenges.
	‚Ä¢	Lower values reflect a healthier population, where fewer individuals report poor or fair health.

The mean values (over the years 2020‚Äì2024) help identify long-term trends in health, providing a snapshot of how overall health has evolved over time.

In [124]:
# ==========================================================
# PART 39A: Load and Report Missing for Poor Physical Health Days Raw Value
# ==========================================================

def load_poor_physical_health_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Poor physical health days raw value"]  # Exact column name from your dataset
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'poor_physical_health_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Poor physical health days raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
poor_physical_health_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_poor_physical_health_column(file_path, year)
    poor_physical_health_dfs.append(df)

# üß© Merge all years together
poor_physical_health = poor_physical_health_dfs[0]
for df in poor_physical_health_dfs[1:]:
    poor_physical_health = pd.merge(poor_physical_health, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
health_cols = [f'poor_physical_health_{y}' for y in range(2020, 2025)]
poor_physical_health[health_cols] = poor_physical_health[health_cols].apply(pd.to_numeric, errors='coerce')
poor_physical_health['poor_physical_health_mean'] = poor_physical_health[health_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_health = pd.DataFrame({
    "Missing Count": poor_physical_health[health_cols].isna().sum(),
    "Missing %": (poor_physical_health[health_cols].isna().sum() / len(poor_physical_health) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Poor Physical Health, Before Imputation)")
print(missing_report_health)

# üîç Show rows with missing values (for further inspection)
rows_with_na_health = poor_physical_health[poor_physical_health[health_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_health)}")
rows_with_na_health.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Poor Physical Health, Before Imputation)
                           Missing Count  Missing %
poor_physical_health_2020              4       0.13
poor_physical_health_2021              4       0.13
poor_physical_health_2022              4       0.13
poor_physical_health_2023              6       0.19
poor_physical_health_2024              3       0.09

üîç Rows with missing values: 7

,FIPS,State,County,poor_physical_health_2020,poor_physical_health_2021,poor_physical_health_2022,poor_physical_health_2023,poor_physical_health_2024,poor_physical_health_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,3.462937,3.462937
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,3.972858,3.972858
97,02261,AK,Valdez-Cordova Census Area,3.136219,3.776202,3.464844,NaN,NaN,3.459089
1164,22059,LA,La Salle Parish,4.840557,4.962162,5.026369,NaN,NaN,4.943030
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,4.111033,4.276630,4.193831

In [125]:
# ==========================================================
# PART 39B: Impute and Recalculate Poor Physical Health Days Raw Value (After Imputation)
# ==========================================================

def impute_poor_physical_health(poor_physical_health):
    # Define the columns for Poor Physical Health Days Raw Value (2020-2024)
    health_cols = ['poor_physical_health_2020', 'poor_physical_health_2021', 
                   'poor_physical_health_2022', 'poor_physical_health_2023', 'poor_physical_health_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = poor_physical_health['State'].unique()
    for state in states:
        state_data = poor_physical_health[poor_physical_health['State'] == state]
        for col in health_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (poor_physical_health['State'] == state) & (poor_physical_health[col].isna())
            poor_physical_health.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    poor_physical_health[health_cols] = poor_physical_health[health_cols].apply(pd.to_numeric, errors='coerce')
    poor_physical_health['poor_physical_health_mean'] = poor_physical_health[health_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": poor_physical_health[health_cols].isna().sum(),
        "Missing %": (poor_physical_health[health_cols].isna().sum() / len(poor_physical_health) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Poor Physical Health (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the imputed DataFrame
    print("\nüëÄ Preview of the Imputed Data (Head):")
    return poor_physical_health.head()

# Example usage (assuming poor_physical_health is the merged data for Poor Physical Health)
poor_physical_health_imputed = impute_poor_physical_health(poor_physical_health)

poor_physical_health_imputed.head()  # Preview the result after imputation

üìã Final Missing Value Report: Poor Physical Health (After Imputation)
                           Missing Count  Missing %
poor_physical_health_2020              1       0.03
poor_physical_health_2021              1       0.03
poor_physical_health_2022              1       0.03
poor_physical_health_2023              1       0.03
poor_physical_health_2024              1       0.03

üëÄ Preview of the Imputed Data (Head):

,FIPS,State,County,poor_physical_health_2020,poor_physical_health_2021,poor_physical_health_2022,poor_physical_health_2023,poor_physical_health_2024,poor_physical_health_mean
0,00000,US,United States,3.752828,3.741935,3.907359,3.000000,3.346300,3.549684
1,01000,AL,Alabama,4.918052,4.416965,4.814633,3.482416,3.934735,4.313360
2,01001,AL,Autauga County,4.743889,4.501499,4.510042,3.432211,3.910265,4.219581
3,01003,AL,Baldwin County,4.224519,3.647978,4.168866,3.276177,3.730943,3.809697
4,01005,AL,Barbour County,5.430279,5.569267,5.884415,4.605432,5.023488,5.302576

üßæ Interpreting Poor Physical Health Raw Value:

The Poor Physical Health Raw Value represents the average number of days in the past month that individuals reported experiencing poor physical health.
	‚Ä¢	For example, in 2020, the value of 3.752828 for the United States means that, on average, individuals reported being in poor physical health for approximately 3.75 days out of the last 30 days.
	‚Ä¢	Higher values indicate that individuals in that area experienced more days of poor physical health, which could signal health challenges, chronic illnesses, or limited access to healthcare.
	‚Ä¢	Lower values reflect fewer days of poor health, indicating better overall health in the population.

This metric is valuable for understanding the overall health burden in a region and can help target health interventions.

In [127]:
# ==========================================================
# PART 40A: Load Uninsured Raw Value and Report Missing
# ==========================================================

def load_uninsured_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # Define stable ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Uninsured raw value"]  # Exact column name from your dataset
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'uninsured_raw_value_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Uninsured raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
uninsured_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_uninsured_column(file_path, year)
    uninsured_dfs.append(df)

# üß© Merge all years together
uninsured_raw_value = uninsured_dfs[0]
for df in uninsured_dfs[1:]:
    uninsured_raw_value = pd.merge(uninsured_raw_value, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
uninsured_cols = [f'uninsured_raw_value_{y}' for y in range(2020, 2025)]
uninsured_raw_value[uninsured_cols] = uninsured_raw_value[uninsured_cols].apply(pd.to_numeric, errors='coerce')
uninsured_raw_value['uninsured_mean'] = uninsured_raw_value[uninsured_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_uninsured = pd.DataFrame({
    "Missing Count": uninsured_raw_value[uninsured_cols].isna().sum(),
    "Missing %": (uninsured_raw_value[uninsured_cols].isna().sum() / len(uninsured_raw_value) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Uninsured Raw Value, Before Imputation)")
print(missing_report_uninsured)

# üîç Show rows with missing values (for further inspection)
rows_with_na_uninsured = uninsured_raw_value[uninsured_raw_value[uninsured_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_uninsured)}")
rows_with_na_uninsured.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Uninsured Raw Value, Before Imputation)
                          Missing Count  Missing %
uninsured_raw_value_2020              5       0.16
uninsured_raw_value_2021              5       0.16
uninsured_raw_value_2022              5       0.16
uninsured_raw_value_2023              5       0.16
uninsured_raw_value_2024              4       0.13

üîç Rows with missing values: 7

,FIPS,State,County,uninsured_raw_value_2020,uninsured_raw_value_2021,uninsured_raw_value_2022,uninsured_raw_value_2023,uninsured_raw_value_2024,uninsured_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.149150,0.149150
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.160192,0.160192
97,02261,AK,Valdez-Cordova Census Area,0.148957,0.129943,0.147470,0.151561,NaN,0.144483
563,15005,HI,Kalawao County,NaN,NaN,NaN,NaN,NaN,NaN
1164,22059,LA,La Salle Parish,0.120289,0.107938,0.115786,NaN,NaN,0.114671

In [128]:
# ==========================================================
# PART 40B: Impute and Recalculate Uninsured Raw Value (After Imputation)
# ==========================================================

def impute_uninsured_raw_value(uninsured_raw_value):
    # Define the columns for uninsured raw value (2020-2024)
    uninsured_cols = ['uninsured_raw_value_2020', 'uninsured_raw_value_2021', 
                     'uninsured_raw_value_2022', 'uninsured_raw_value_2023', 'uninsured_raw_value_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = uninsured_raw_value['State'].unique()
    for state in states:
        state_data = uninsured_raw_value[uninsured_raw_value['State'] == state]
        for col in uninsured_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (uninsured_raw_value['State'] == state) & (uninsured_raw_value[col].isna())
            uninsured_raw_value.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    uninsured_raw_value[uninsured_cols] = uninsured_raw_value[uninsured_cols].apply(pd.to_numeric, errors='coerce')
    uninsured_raw_value['uninsured_mean'] = uninsured_raw_value[uninsured_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": uninsured_raw_value[uninsured_cols].isna().sum(),
        "Missing %": (uninsured_raw_value[uninsured_cols].isna().sum() / len(uninsured_raw_value) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Uninsured Raw Value (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the imputed DataFrame
    print("\nüëÄ Preview of the Imputed Data (Head):")
    return uninsured_raw_value.head()

# Example usage (assuming uninsured_raw_value is the merged data for uninsured)
uninsured_raw_value_imputed = impute_uninsured_raw_value(uninsured_raw_value)

uninsured_raw_value_imputed.head()  # Preview the imputed data

üìã Final Missing Value Report: Uninsured Raw Value (After Imputation)
                          Missing Count  Missing %
uninsured_raw_value_2020              1       0.03
uninsured_raw_value_2021              1       0.03
uninsured_raw_value_2022              1       0.03
uninsured_raw_value_2023              1       0.03
uninsured_raw_value_2024              1       0.03

üëÄ Preview of the Imputed Data (Head):

,FIPS,State,County,uninsured_raw_value_2020,uninsured_raw_value_2021,uninsured_raw_value_2022,uninsured_raw_value_2023,uninsured_raw_value_2024,uninsured_mean
0,00000,US,United States,0.102234,0.104289,0.108405,0.104450,0.102285,0.104333
1,01000,AL,Alabama,0.110448,0.118847,0.115995,0.118227,0.116934,0.116090
2,01001,AL,Autauga County,0.087217,0.100473,0.093512,0.105594,0.100186,0.097396
3,01003,AL,Baldwin County,0.113334,0.131690,0.109068,0.108749,0.109971,0.114562
4,01005,AL,Barbour County,0.122428,0.135040,0.129915,0.143683,0.126776,0.131568

The Uninsured Raw Value represents the percentage of the population in a specific county or area that is without health insurance for each year.
	‚Ä¢	Values: These are expressed as proportions between 0 and 1, where:
	‚Ä¢	0 indicates no individuals without health insurance.
	‚Ä¢	1 indicates that the entire population is without health insurance.
	‚Ä¢	For example, 0.110448 for Alabama in 2020 means that 11.04% of the population in Alabama was uninsured in 2020.
	‚Ä¢	Interpretation:
	‚Ä¢	Higher values indicate a larger portion of the population without health insurance, which may suggest gaps in access to healthcare or issues with healthcare coverage policies.
	‚Ä¢	Lower values indicate better health insurance coverage, meaning fewer people are without health insurance.

This indicator is vital for evaluating public health initiatives, the affordability of healthcare, and determining areas that might benefit from improved insurance policies.

In [130]:
# ==========================================================
# PART 41A: Load Primary Care Physicians Raw Value and Report Missing
# ==========================================================

def load_primary_care_physicians_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Primary Care Physicians raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'primary_care_physicians_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Primary Care Physicians raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
primary_care_physicians_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_primary_care_physicians_column(file_path, year)
    primary_care_physicians_dfs.append(df)

# üß© Merge all years together
primary_care_physicians = primary_care_physicians_dfs[0]
for df in primary_care_physicians_dfs[1:]:
    primary_care_physicians = pd.merge(primary_care_physicians, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
primary_care_physicians_cols = [f'primary_care_physicians_{y}' for y in range(2020, 2025)]
primary_care_physicians[primary_care_physicians_cols] = primary_care_physicians[primary_care_physicians_cols].apply(pd.to_numeric, errors='coerce')
primary_care_physicians['primary_care_physicians_mean'] = primary_care_physicians[primary_care_physicians_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_primary_care_physicians = pd.DataFrame({
    "Missing Count": primary_care_physicians[primary_care_physicians_cols].isna().sum(),
    "Missing %": (primary_care_physicians[primary_care_physicians_cols].isna().sum() / len(primary_care_physicians) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Primary Care Physicians Raw Value, Before Imputation)")
print(missing_report_primary_care_physicians)

# üîç Show rows with missing values (for further inspection)
rows_with_na_primary_care_physicians = primary_care_physicians[primary_care_physicians[primary_care_physicians_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_primary_care_physicians)}")
rows_with_na_primary_care_physicians.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Primary Care Physicians Raw Value, Before Imputation)
                              Missing Count  Missing %
primary_care_physicians_2020            151       4.72
primary_care_physicians_2021            154       4.82
primary_care_physicians_2022            157       4.91
primary_care_physicians_2023            151       4.72
primary_care_physicians_2024            160       5.00

üîç Rows with missing values: 211

,FIPS,State,County,primary_care_physicians_2020,primary_care_physicians_2021,primary_care_physicians_2022,primary_care_physicians_2023,primary_care_physicians_2024,primary_care_physicians_mean
20,01037,AL,Coosa County,NaN,NaN,NaN,NaN,NaN,NaN
39,01075,AL,Lamar County,NaN,NaN,NaN,NaN,NaN,NaN
70,02013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,NaN,NaN
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.001585,0.001585
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.000380,0.000380

In [131]:
# ==========================================================
# PART 41B: Impute and Recalculate Primary Care Physicians Raw Value (After Imputation)
# ==========================================================

def impute_primary_care_physicians(suicides_raw_value):
    # Define the columns for primary care physicians (2020-2024)
    primary_care_physicians_cols = ['primary_care_physicians_2020', 'primary_care_physicians_2021', 
                                    'primary_care_physicians_2022', 'primary_care_physicians_2023', 'primary_care_physicians_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = suicides_raw_value['State'].unique()
    for state in states:
        state_data = suicides_raw_value[suicides_raw_value['State'] == state]
        for col in primary_care_physicians_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (suicides_raw_value['State'] == state) & (suicides_raw_value[col].isna())
            suicides_raw_value.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    suicides_raw_value[primary_care_physicians_cols] = suicides_raw_value[primary_care_physicians_cols].apply(pd.to_numeric, errors='coerce')
    suicides_raw_value['primary_care_physicians_mean'] = suicides_raw_value[primary_care_physicians_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": suicides_raw_value[primary_care_physicians_cols].isna().sum(),
        "Missing %": (suicides_raw_value[primary_care_physicians_cols].isna().sum() / len(suicides_raw_value) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Primary Care Physicians Raw Value (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the imputed DataFrame
    print("\nüëÄ Preview of the Imputed Data (Head):")
    return suicides_raw_value.head()

# Example usage (assuming suicides_raw_value is the merged data for suicides)
primary_care_physicians_imputed = impute_primary_care_physicians(primary_care_physicians)

primary_care_physicians_imputed.head()

üìã Final Missing Value Report: Primary Care Physicians Raw Value (After Imputation)
                              Missing Count  Missing %
primary_care_physicians_2020              1       0.03
primary_care_physicians_2021              1       0.03
primary_care_physicians_2022              1       0.03
primary_care_physicians_2023              1       0.03
primary_care_physicians_2024              1       0.03

üëÄ Preview of the Imputed Data (Head):

,FIPS,State,County,primary_care_physicians_2020,primary_care_physicians_2021,primary_care_physicians_2022,primary_care_physicians_2023,primary_care_physicians_2024,primary_care_physicians_mean
0,00000,US,United States,0.000755,0.000758,0.000765,0.000764,0.000749,0.000758
1,01000,AL,Alabama,0.000648,0.000652,0.000658,0.000658,0.000637,0.000651
2,01001,AL,Autauga County,0.000450,0.000468,0.000447,0.000445,0.000440,0.000450
3,01003,AL,Baldwin County,0.000729,0.000702,0.000690,0.000654,0.000627,0.000680
4,01005,AL,Barbour County,0.000317,0.000322,0.000365,0.000325,0.000401,0.000346

Interpretation of Primary Care Physicians Raw Value:

The Primary Care Physicians raw value represents the ratio of primary care physicians to the population in a given area (county or state). It helps assess how accessible primary healthcare is relative to the number of people in a region.
	1.	Values:
	‚Ä¢	Higher values indicate better access to primary care physicians, meaning there are more physicians available per capita.
	‚Ä¢	Lower values indicate limited access, suggesting that fewer physicians are available to the population.
	2.	Interpretation:
	‚Ä¢	For example, in 2020, the United States had a primary care physician raw value of 0.0007637606, reflecting approximately 0.76 physicians per 1,000 people.
	‚Ä¢	Alabama in 2020 had a raw value of 0.0006579252, meaning it had 0.66 physicians per 1,000 people, indicating slightly fewer physicians compared to the national average.
	3.	Significance:
	‚Ä¢	A higher ratio indicates better healthcare access, while a lower ratio suggests challenges such as fewer physicians available to serve the population.
	‚Ä¢	This metric is essential for understanding healthcare availability and disparities, especially in rural areas, where the ratio tends to be lower, and the population may have reduced access to necessary healthcare services.

In [133]:
# ==========================================================
# PART 42A: Load Dentists Raw Value and Report Missing
# ==========================================================

def load_dentists_raw_value_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Dentists raw value"]  # Exact column name from your dataset
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'dentists_raw_value_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Dentists raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
dentists_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_dentists_raw_value_column(file_path, year)
    dentists_dfs.append(df)

# üß© Merge all years together
dentists_raw_value = dentists_dfs[0]
for df in dentists_dfs[1:]:
    dentists_raw_value = pd.merge(dentists_raw_value, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
dentists_cols = [f'dentists_raw_value_{y}' for y in range(2020, 2025)]
dentists_raw_value[dentists_cols] = dentists_raw_value[dentists_cols].apply(pd.to_numeric, errors='coerce')
dentists_raw_value['dentists_mean'] = dentists_raw_value[dentists_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_dentists_raw_value = pd.DataFrame({
    "Missing Count": dentists_raw_value[dentists_cols].isna().sum(),
    "Missing %": (dentists_raw_value[dentists_cols].isna().sum() / len(dentists_raw_value) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Dentists Raw Value, Before Imputation)")
print(missing_report_dentists_raw_value)

# üîç Show rows with missing values (for further inspection)
rows_with_na_dentists = dentists_raw_value[dentists_raw_value[dentists_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_dentists)}")
rows_with_na_dentists.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Dentists Raw Value, Before Imputation)
                         Missing Count  Missing %
dentists_raw_value_2020             92       2.88
dentists_raw_value_2021             93       2.91
dentists_raw_value_2022             94       2.94
dentists_raw_value_2023             90       2.81
dentists_raw_value_2024             90       2.81

üîç Rows with missing values: 106

,FIPS,State,County,dentists_raw_value_2020,dentists_raw_value_2021,dentists_raw_value_2022,dentists_raw_value_2023,dentists_raw_value_2024,dentists_mean
16,01029,AL,Cleburne County,NaN,NaN,NaN,NaN,NaN,NaN
20,01037,AL,Coosa County,NaN,NaN,NaN,NaN,NaN,NaN
33,01063,AL,Greene County,0.000121,0.000123,NaN,NaN,NaN,0.000122
44,01085,AL,Lowndes County,NaN,NaN,NaN,NaN,NaN,NaN
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.000436,0.000436

In [134]:
# ==========================================================
# PART 42B: Impute and Recalculate Dentists Raw Value (After Imputation)
# ==========================================================

def impute_dentists_raw_value(dentists_raw_value):
    # Define the columns for dentists raw value (2020-2024)
    dentists_cols = ['dentists_raw_value_2020', 'dentists_raw_value_2021', 
                     'dentists_raw_value_2022', 'dentists_raw_value_2023', 'dentists_raw_value_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = dentists_raw_value['State'].unique()
    for state in states:
        state_data = dentists_raw_value[dentists_raw_value['State'] == state]
        for col in dentists_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (dentists_raw_value['State'] == state) & (dentists_raw_value[col].isna())
            dentists_raw_value.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    dentists_raw_value[dentists_cols] = dentists_raw_value[dentists_cols].apply(pd.to_numeric, errors='coerce')
    dentists_raw_value['dentists_mean'] = dentists_raw_value[dentists_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": dentists_raw_value[dentists_cols].isna().sum(),
        "Missing %": (dentists_raw_value[dentists_cols].isna().sum() / len(dentists_raw_value) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Dentists Raw Value (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the imputed DataFrame
    print("\nüëÄ Preview of the Imputed Data (Head):")
    return dentists_raw_value.head()

# Example usage (assuming dentists_raw_value is the merged data for dentists)
dentists_raw_value_imputed = impute_dentists_raw_value(dentists_raw_value)

dentists_raw_value_imputed.head()  # It will display the first few rows after imputation

üìã Final Missing Value Report: Dentists Raw Value (After Imputation)
                         Missing Count  Missing %
dentists_raw_value_2020              1       0.03
dentists_raw_value_2021              1       0.03
dentists_raw_value_2022              1       0.03
dentists_raw_value_2023              1       0.03
dentists_raw_value_2024              1       0.03

üëÄ Preview of the Imputed Data (Head):

,FIPS,State,County,dentists_raw_value_2020,dentists_raw_value_2021,dentists_raw_value_2022,dentists_raw_value_2023,dentists_raw_value_2024,dentists_mean
0,00000,US,United States,0.000691,0.000712,0.000715,0.000725,0.000735,0.000715
1,01000,AL,Alabama,0.000482,0.000499,0.000494,0.000487,0.000496,0.000491
2,01001,AL,Autauga County,0.000324,0.000340,0.000338,0.000322,0.000301,0.000325
3,01003,AL,Baldwin County,0.000495,0.000493,0.000488,0.000476,0.000471,0.000485
4,01005,AL,Barbour County,0.000362,0.000365,0.000366,0.000320,0.000324,0.000347

üßæ Interpreting Dentists Raw Value (Example: 0.000691):

The Dentists raw value represents the ratio of dentists per 100,000 people in a specific area (county or state) for a given year.
	‚Ä¢	Example Value: 0.000691 means there are 0.000691 dentists for every person in the population of that area (per 100,000 people).
	‚Ä¢	Higher values suggest better access to dental care, indicating a greater density of dentists relative to the population, which could reflect better healthcare infrastructure.
	‚Ä¢	Lower values suggest limited access to dental care, potentially due to fewer available dental professionals relative to the population, which may point to rural or underserved areas.

This metric is important for understanding healthcare accessibility, particularly dental care, and can be used to assess the adequacy of healthcare infrastructure in different regions.

In [136]:
# ==========================================================
# PART 43A: Load Mental Health Providers Raw Value and Report Missing
# ==========================================================

def load_mental_health_providers_raw_value_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Mental Health Providers raw value"]  # Exact column name from your dataset
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'mental_health_providers_raw_value_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Mental Health Providers raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
mental_health_providers_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_mental_health_providers_raw_value_column(file_path, year)
    mental_health_providers_dfs.append(df)

# üß© Merge all years together
mental_health_providers_raw_value = mental_health_providers_dfs[0]
for df in mental_health_providers_dfs[1:]:
    mental_health_providers_raw_value = pd.merge(mental_health_providers_raw_value, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
mental_health_providers_cols = [f'mental_health_providers_raw_value_{y}' for y in range(2020, 2025)]
mental_health_providers_raw_value[mental_health_providers_cols] = mental_health_providers_raw_value[mental_health_providers_cols].apply(pd.to_numeric, errors='coerce')
mental_health_providers_raw_value['mental_health_providers_mean'] = mental_health_providers_raw_value[mental_health_providers_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_mental_health_providers_raw_value = pd.DataFrame({
    "Missing Count": mental_health_providers_raw_value[mental_health_providers_cols].isna().sum(),
    "Missing %": (mental_health_providers_raw_value[mental_health_providers_cols].isna().sum() / len(mental_health_providers_raw_value) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Mental Health Providers Raw Value, Before Imputation)")
print(missing_report_mental_health_providers_raw_value)

# üîç Show rows with missing values (for further inspection)
rows_with_na_mental_health_providers = mental_health_providers_raw_value[mental_health_providers_raw_value[mental_health_providers_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_mental_health_providers)}")
rows_with_na_mental_health_providers.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Mental Health Providers Raw Value, Before Imputation)
                                        Missing Count  Missing %
mental_health_providers_raw_value_2020            234       7.32
mental_health_providers_raw_value_2021            225       7.04
mental_health_providers_raw_value_2022            208       6.50
mental_health_providers_raw_value_2023            205       6.41
mental_health_providers_raw_value_2024            188       5.88

üîç Rows with missing values: 250

,FIPS,State,County,mental_health_providers_raw_value_2020,mental_health_providers_raw_value_2021,mental_health_providers_raw_value_2022,mental_health_providers_raw_value_2023,mental_health_providers_raw_value_2024,mental_health_providers_mean
13,01023,AL,Choctaw County,NaN,0.000079,0.000081,0.00008,0.000080,0.000080
44,01085,AL,Lowndes County,NaN,NaN,NaN,NaN,0.000102,0.000102
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,0.002037,0.002037
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,0.003862,0.003862
77,02068,AK,Denali Borough,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
# ==========================================================
# PART 43B: Impute and Recalculate Mental Health Providers Raw Value (After Imputation)
# ==========================================================

def impute_mental_health_providers_raw_value(mental_health_providers_raw_value):
    # Define the columns for mental health providers raw value (2020-2024)
    mental_health_providers_cols = ['mental_health_providers_raw_value_2020', 'mental_health_providers_raw_value_2021',
                                    'mental_health_providers_raw_value_2022', 'mental_health_providers_raw_value_2023', 
                                    'mental_health_providers_raw_value_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = mental_health_providers_raw_value['State'].unique()
    for state in states:
        state_data = mental_health_providers_raw_value[mental_health_providers_raw_value['State'] == state]
        for col in mental_health_providers_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (mental_health_providers_raw_value['State'] == state) & (mental_health_providers_raw_value[col].isna())
            mental_health_providers_raw_value.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    mental_health_providers_raw_value[mental_health_providers_cols] = mental_health_providers_raw_value[mental_health_providers_cols].apply(pd.to_numeric, errors='coerce')
    mental_health_providers_raw_value['mental_health_providers_mean'] = mental_health_providers_raw_value[mental_health_providers_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": mental_health_providers_raw_value[mental_health_providers_cols].isna().sum(),
        "Missing %": (mental_health_providers_raw_value[mental_health_providers_cols].isna().sum() / len(mental_health_providers_raw_value) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Mental Health Providers Raw Value (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the imputed DataFrame
    print("\nüëÄ Preview of the Imputed Data (Head):")
    return mental_health_providers_raw_value.head()

# Example usage (assuming mental_health_providers_raw_value is the merged data for mental health providers)
mental_health_providers_raw_value_imputed = impute_mental_health_providers_raw_value(mental_health_providers_raw_value)

mental_health_providers_raw_value_imputed.head()  # Preview after imputation

üìã Final Missing Value Report: Mental Health Providers Raw Value (After Imputation)
                                        Missing Count  Missing %
mental_health_providers_raw_value_2020              1       0.03
mental_health_providers_raw_value_2021              1       0.03
mental_health_providers_raw_value_2022              1       0.03
mental_health_providers_raw_value_2023              1       0.03
mental_health_providers_raw_value_2024              1       0.03

üëÄ Preview of the Imputed Data (Head):

,FIPS,State,County,mental_health_providers_raw_value_2020,mental_health_providers_raw_value_2021,mental_health_providers_raw_value_2022,mental_health_providers_raw_value_2023,mental_health_providers_raw_value_2024,mental_health_providers_mean
0,00000,US,United States,0.002480,0.002612,0.002819,0.002957,0.003139,0.002801
1,01000,AL,Alabama,0.001012,0.001083,0.001182,0.001254,0.001351,0.001177
2,01001,AL,Autauga County,0.000234,0.000286,0.000374,0.000355,0.000368,0.000324
3,01003,AL,Baldwin County,0.000963,0.000986,0.000994,0.001045,0.001104,0.001018
4,01005,AL,Barbour County,0.000080,0.000122,0.000244,0.000240,0.000283,0.000194

üßæ Interpreting Mental Health Providers Raw Value (Example: 0.002480):

The Mental Health Providers raw value represents the ratio of mental health providers per 100,000 people in a specific area (county or state) for a given year.
	‚Ä¢	Example Value: 0.002480 means that there are 0.002480 mental health providers for every person in the population (per 100,000 people).
	‚Ä¢	Higher values suggest better access to mental health services, indicating a greater density of mental health providers relative to the population, which is important for addressing mental health needs in the community.
	‚Ä¢	Lower values suggest limited access to mental health services, potentially due to a shortage of providers in that region, often seen in rural or underserved areas.

This indicator helps evaluate the accessibility of mental health services and is crucial for understanding the adequacy of mental health care in different communities. It can inform policy decisions related to mental health resource allocation and health equity.

In [139]:
# ==========================================================
# PART A: Load Flu Vaccinations Raw Value and Report Missing
# ==========================================================

def load_flu_vaccinations_raw_value_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Flu vaccinations raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'flu_vaccinations_raw_value_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Flu vaccinations raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
flu_vaccinations_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_flu_vaccinations_raw_value_column(file_path, year)
    flu_vaccinations_dfs.append(df)

# üß© Merge all years together
flu_vaccinations_raw_value = flu_vaccinations_dfs[0]
for df in flu_vaccinations_dfs[1:]:
    flu_vaccinations_raw_value = pd.merge(flu_vaccinations_raw_value, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
flu_vaccinations_cols = [f'flu_vaccinations_raw_value_{y}' for y in range(2020, 2025)]
flu_vaccinations_raw_value[flu_vaccinations_cols] = flu_vaccinations_raw_value[flu_vaccinations_cols].apply(pd.to_numeric, errors='coerce')
flu_vaccinations_raw_value['flu_vaccinations_mean'] = flu_vaccinations_raw_value[flu_vaccinations_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_flu_vaccinations_raw_value = pd.DataFrame({
    "Missing Count": flu_vaccinations_raw_value[flu_vaccinations_cols].isna().sum(),
    "Missing %": (flu_vaccinations_raw_value[flu_vaccinations_cols].isna().sum() / len(flu_vaccinations_raw_value) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Flu Vaccinations Raw Value, Before Imputation)")
print(missing_report_flu_vaccinations_raw_value)

# üîç Show rows with missing values (for further inspection)
rows_with_na_flu_vaccinations = flu_vaccinations_raw_value[flu_vaccinations_raw_value[flu_vaccinations_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_flu_vaccinations)}")
rows_with_na_flu_vaccinations.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Flu Vaccinations Raw Value, Before Imputation)
                                 Missing Count  Missing %
flu_vaccinations_raw_value_2020             22       0.69
flu_vaccinations_raw_value_2021             22       0.69
flu_vaccinations_raw_value_2022             23       0.72
flu_vaccinations_raw_value_2023             22       0.69
flu_vaccinations_raw_value_2024             23       0.72

üîç Rows with missing values: 25

,FIPS,State,County,flu_vaccinations_raw_value_2020,flu_vaccinations_raw_value_2021,flu_vaccinations_raw_value_2022,flu_vaccinations_raw_value_2023,flu_vaccinations_raw_value_2024,flu_vaccinations_mean
70,02013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,NaN,NaN
71,02016,AK,Aleutians West Census Area,NaN,NaN,NaN,NaN,NaN,NaN
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,NaN,NaN
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,NaN,NaN
77,02068,AK,Denali Borough,NaN,NaN,NaN,NaN,NaN,NaN

In [140]:
# ==========================================================
# PART B: Impute and Recalculate Flu Vaccinations Raw Value (After Imputation)
# ==========================================================

def impute_flu_vaccinations_raw_value(flu_vaccinations_raw_value):
    # Define the columns for flu vaccinations raw value (2020-2024)
    flu_vaccinations_cols = ['flu_vaccinations_raw_value_2020', 'flu_vaccinations_raw_value_2021', 
                             'flu_vaccinations_raw_value_2022', 'flu_vaccinations_raw_value_2023', 
                             'flu_vaccinations_raw_value_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = flu_vaccinations_raw_value['State'].unique()
    for state in states:
        state_data = flu_vaccinations_raw_value[flu_vaccinations_raw_value['State'] == state]
        for col in flu_vaccinations_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (flu_vaccinations_raw_value['State'] == state) & (flu_vaccinations_raw_value[col].isna())
            flu_vaccinations_raw_value.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    flu_vaccinations_raw_value[flu_vaccinations_cols] = flu_vaccinations_raw_value[flu_vaccinations_cols].apply(pd.to_numeric, errors='coerce')
    flu_vaccinations_raw_value['flu_vaccinations_mean'] = flu_vaccinations_raw_value[flu_vaccinations_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": flu_vaccinations_raw_value[flu_vaccinations_cols].isna().sum(),
        "Missing %": (flu_vaccinations_raw_value[flu_vaccinations_cols].isna().sum() / len(flu_vaccinations_raw_value) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Flu Vaccinations Raw Value (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the imputed DataFrame
    print("\nüëÄ Preview of the Imputed Data (Head):")
    return flu_vaccinations_raw_value.head()

# Example usage (assuming flu_vaccinations_raw_value is the merged data for flu vaccinations)
flu_vaccinations_raw_value_imputed = impute_flu_vaccinations_raw_value(flu_vaccinations_raw_value)

flu_vaccinations_raw_value_imputed.head()  # Preview after imputation

üìã Final Missing Value Report: Flu Vaccinations Raw Value (After Imputation)
                                 Missing Count  Missing %
flu_vaccinations_raw_value_2020              1       0.03
flu_vaccinations_raw_value_2021              1       0.03
flu_vaccinations_raw_value_2022              1       0.03
flu_vaccinations_raw_value_2023              1       0.03
flu_vaccinations_raw_value_2024              1       0.03

üëÄ Preview of the Imputed Data (Head):

,FIPS,State,County,flu_vaccinations_raw_value_2020,flu_vaccinations_raw_value_2021,flu_vaccinations_raw_value_2022,flu_vaccinations_raw_value_2023,flu_vaccinations_raw_value_2024,flu_vaccinations_mean
0,00000,US,United States,0.46,0.48,0.48,0.51,0.46,0.478
1,01000,AL,Alabama,0.41,0.43,0.42,0.44,0.39,0.418
2,01001,AL,Autauga County,0.41,0.42,0.42,0.42,0.37,0.408
3,01003,AL,Baldwin County,0.44,0.46,0.46,0.47,0.42,0.450
4,01005,AL,Barbour County,0.37,0.39,0.36,0.40,0.35,0.374

üßæ Interpreting Flu Vaccinations Raw Value:

The Flu Vaccinations raw value represents the percentage of the population that has received the flu vaccine in a specific county or area during the year.

For example, a value of 0.46 means that 46% of the population in that area received the flu vaccine in that year.

This metric is crucial for evaluating the public health efforts to prevent flu outbreaks, especially in vulnerable populations. Higher values indicate better vaccination coverage, which is associated with reduced flu-related illness and deaths.

It reflects the effectiveness of health initiatives, vaccination accessibility, and public awareness campaigns.

In [142]:
# ==========================================================
# PART 44A: Load Mammography Screening Raw Value and Report Missing
# ==========================================================

def load_mammography_screening_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Mammography screening raw value"]  # Exact column name from your dataset
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'mammography_screening_raw_value_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Mammography screening raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years (2020-2024)
mammography_screening_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_mammography_screening_column(file_path, year)
    mammography_screening_dfs.append(df)

# üß© Merge all years together
mammography_screening = mammography_screening_dfs[0]
for df in mammography_screening_dfs[1:]:
    mammography_screening = pd.merge(mammography_screening, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
mammography_screening_cols = [f'mammography_screening_raw_value_{y}' for y in range(2020, 2025)]
mammography_screening[mammography_screening_cols] = mammography_screening[mammography_screening_cols].apply(pd.to_numeric, errors='coerce')
mammography_screening['mammography_screening_mean'] = mammography_screening[mammography_screening_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_mammography_screening = pd.DataFrame({
    "Missing Count": mammography_screening[mammography_screening_cols].isna().sum(),
    "Missing %": (mammography_screening[mammography_screening_cols].isna().sum() / len(mammography_screening) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Mammography Screening, Before Imputation)")
print(missing_report_mammography_screening)

# üîç Show rows with missing values (for further inspection)
rows_with_na_mammography_screening = mammography_screening[mammography_screening[mammography_screening_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_mammography_screening)}")
rows_with_na_mammography_screening.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Mammography Screening, Before Imputation)
                                      Missing Count  Missing %
mammography_screening_raw_value_2020             23       0.72
mammography_screening_raw_value_2021             24       0.75
mammography_screening_raw_value_2022             24       0.75
mammography_screening_raw_value_2023             25       0.78
mammography_screening_raw_value_2024             25       0.78

üîç Rows with missing values: 28

,FIPS,State,County,mammography_screening_raw_value_2020,mammography_screening_raw_value_2021,mammography_screening_raw_value_2022,mammography_screening_raw_value_2023,mammography_screening_raw_value_2024,mammography_screening_mean
70,02013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,NaN,NaN
71,02016,AK,Aleutians West Census Area,NaN,NaN,NaN,NaN,NaN,NaN
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,NaN,NaN
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,NaN,NaN
77,02068,AK,Denali Borough,NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
# ==========================================================
# PART 44B: Impute and Recalculate Mammography Screening Raw Value (After Imputation)
# ==========================================================

def impute_mammography_screening(suicides_raw_value):
    # Define the columns for mammography screening raw value (2020-2024)
    mammography_cols = ['mammography_screening_raw_value_2020', 'mammography_screening_raw_value_2021', 
                         'mammography_screening_raw_value_2022', 'mammography_screening_raw_value_2023', 'mammography_screening_raw_value_2024']

    # üéØ Impute missing values using state-level mean for each year
    states = suicides_raw_value['State'].unique()
    for state in states:
        state_data = suicides_raw_value[suicides_raw_value['State'] == state]
        for col in mammography_cols:
            year_mean = state_data[col].mean(skipna=True)  # Using all years for imputation
            missing_mask = (suicides_raw_value['State'] == state) & (suicides_raw_value[col].isna())
            suicides_raw_value.loc[missing_mask, col] = year_mean

    # üîÅ Recalculate mean after imputation using all 5 years
    suicides_raw_value[mammography_cols] = suicides_raw_value[mammography_cols].apply(pd.to_numeric, errors='coerce')
    suicides_raw_value['mammography_screening_mean'] = suicides_raw_value[mammography_cols].mean(axis=1, skipna=True)

    # üìã Final missing value report after imputation
    missing_report_final = pd.DataFrame({
        "Missing Count": suicides_raw_value[mammography_cols].isna().sum(),
        "Missing %": (suicides_raw_value[mammography_cols].isna().sum() / len(suicides_raw_value) * 100).round(2)
    })
    print("\nüìã Final Missing Value Report: Mammography Screening Raw Value (After Imputation)")
    print(missing_report_final)

    # üëÄ Preview after imputation and print the head of the imputed DataFrame
    print("\nüëÄ Preview of the Imputed Data (Head):")
    return suicides_raw_value.head()

# Example usage (assuming suicides_raw_value is the merged data for suicides)
mammography_screening_imputed = impute_mammography_screening(mammography_screening)

mammography_screening_imputed.head() # Show final output with imputed data

üìã Final Missing Value Report: Mammography Screening Raw Value (After Imputation)
                                      Missing Count  Missing %
mammography_screening_raw_value_2020              1       0.03
mammography_screening_raw_value_2021              1       0.03
mammography_screening_raw_value_2022              1       0.03
mammography_screening_raw_value_2023              1       0.03
mammography_screening_raw_value_2024              1       0.03

üëÄ Preview of the Imputed Data (Head):

,FIPS,State,County,mammography_screening_raw_value_2020,mammography_screening_raw_value_2021,mammography_screening_raw_value_2022,mammography_screening_raw_value_2023,mammography_screening_raw_value_2024,mammography_screening_mean
0,00000,US,United States,0.42,0.42,0.43,0.37,0.43,0.414
1,01000,AL,Alabama,0.40,0.40,0.42,0.36,0.41,0.398
2,01001,AL,Autauga County,0.41,0.39,0.42,0.38,0.40,0.400
3,01003,AL,Baldwin County,0.43,0.43,0.44,0.39,0.44,0.426
4,01005,AL,Barbour County,0.45,0.44,0.46,0.41,0.42,0.436

üßæ Interpreting Mammography Screening Raw Value:

The Mammography Screening raw value represents the percentage of women aged 50 to 74 who have received a mammogram in a specific year.

For example, a value of 0.42 means that 42% of women in that area received a mammogram in the given year.

This indicator is crucial for assessing access to preventive healthcare services, particularly for breast cancer screening. Higher values indicate a greater proportion of women participating in regular screenings, which can lead to earlier detection and improved outcomes.

This metric reflects the effectiveness of healthcare programs, awareness campaigns, and accessibility of screening services for women.

In [145]:
# ==========================================================
# PART 45A: Load Population Raw Value and Report Missing
# ==========================================================
def load_population_raw_value_column(filename, year):
    df = pd.read_csv(os.path.join(input_path, filename), low_memory=False)
    df.columns = df.columns.str.strip()

    # ID columns
    fips_col = "5-digit FIPS Code"
    state_col = "State Abbreviation"
    county_col = "Name"

    # Match target column (case-insensitive)
    target_cols = ["Population raw value"]
    match = [col for col in df.columns if col.strip().lower() in [tc.lower() for tc in target_cols]]
    value_col = match[0] if match else None
    new_col = f'population_raw_value_{year}'

    # Validate required columns
    required_cols = [fips_col, state_col, county_col]
    for col in required_cols:
        if col not in df.columns:
            raise KeyError(f"‚ùå Missing required column: '{col}' in {filename}")

    out_df = df[required_cols].copy()
    out_df.columns = ['FIPS', 'State', 'County']

    if value_col:
        out_df[new_col] = df[value_col]
    else:
        print(f"‚ö†Ô∏è Column 'Population raw value' not found in {filename}. Filling {new_col} with NA.")
        out_df[new_col] = pd.NA

    return out_df

# üì• Load for all 5 years
population_dfs = []
for year in range(2020, 2025):
    file_path = get_file_path(year)
    df = load_population_raw_value_column(file_path, year)
    population_dfs.append(df)

# üß© Merge all years together
population_raw_value = population_dfs[0]
for df in population_dfs[1:]:
    population_raw_value = pd.merge(population_raw_value, df, on=["FIPS", "State", "County"], how="outer")

# üìä Convert values and calculate pre-imputation mean
population_cols = [f'population_raw_value_{y}' for y in range(2020, 2025)]
population_raw_value[population_cols] = population_raw_value[population_cols].apply(pd.to_numeric, errors='coerce')
population_raw_value['population_mean'] = population_raw_value[population_cols].mean(axis=1, skipna=True)

# üìã Report missing values for each year
missing_report_population_raw_value = pd.DataFrame({
    "Missing Count": population_raw_value[population_cols].isna().sum(),
    "Missing %": (population_raw_value[population_cols].isna().sum() / len(population_raw_value) * 100).round(2)
})
print("\nüìã Summary Missing Value Report (Population Raw Value, Before Imputation)")
print(missing_report_population_raw_value)

# üîç Show rows with missing values (for further inspection)
rows_with_na_population = population_raw_value[population_raw_value[population_cols].isna().any(axis=1)]
print(f"\nüîç Rows with missing values: {len(rows_with_na_population)}")
rows_with_na_population.head()

‚úÖ Found file for 2020: analytic_data2020.csv
‚úÖ Found file for 2021: analytic_data2021.csv
‚úÖ Found file for 2022: analytic_data2022.csv
‚úÖ Found file for 2023: analytic_data2023.csv
‚úÖ Found file for 2024: analytic_data2024.csv

üìã Summary Missing Value Report (Population Raw Value, Before Imputation)
                           Missing Count  Missing %
population_raw_value_2020              4       0.13
population_raw_value_2021              4       0.13
population_raw_value_2022              4       0.13
population_raw_value_2023              4       0.13
population_raw_value_2024              3       0.09

üîç Rows with missing values: 6

,FIPS,State,County,population_raw_value_2020,population_raw_value_2021,population_raw_value_2022,population_raw_value_2023,population_raw_value_2024,population_mean
75,02063,AK,Chugach Census Area,NaN,NaN,NaN,NaN,6874.0,6874.000000
76,02066,AK,Copper River Census Area,NaN,NaN,NaN,NaN,2589.0,2589.000000
97,02261,AK,Valdez-Cordova Census Area,9164.0,9202.0,9346.0,9571.0,NaN,9320.750000
1164,22059,LA,La Salle Parish,14917.0,14892.0,15021.0,NaN,NaN,14943.333333
1165,22059,LA,LaSalle Parish,NaN,NaN,NaN,14834.0,14729.0,14781.500000

In [146]:
all_variables = dir()
dataframes = [var for var in all_variables if isinstance(globals()[var], pd.DataFrame)]

In [147]:
mental_health_providers_raw_val = mental_health_providers_raw_value

In [148]:
# Show which selected DataFrames are available in memory
selected_dfs = [
    "air_pollution", "available_by_state_year", "children_lunch", "children_poverty", "dentists_raw_value",
    "disconnected_youth", "drinking_water", "drive_alone", "drug_overdose_deaths", "exercise_access",
    "firearm_fatalities", "flu_vaccinations_raw_value", "food_environment_index", "food_insecurity",
    "frequent_physical_distress", "high_housing_cost", "high_school_graduation", "hiv_prevalence_raw_value",
    "homeownership", "homicides", "housing_facilities", "income_inequality", "injury_deaths",
    "insufficient_sleep_raw_value", "juvenile_arrests", "life_expectancy", "limited_access_healthy_foods",
    "long_commute", "mammography_screening", "math_scores", "median_income", "mental_health_providers_raw_val",
    "motor_vehicle_crash_deaths", "not_proficient_english", "poor_or_fair_health", "poor_physical_health",
    "population_raw_value", "primary_care_physicians", "reading_scores", "severe_housing",
    "severe_housing_problems", "some_college", "suicides_raw_value", "traffic_volume", "unemployment",
    "uninsured_raw_value", "violent_crime"
]

all_variables = dir()
available = [name for name in selected_dfs if name in all_variables and isinstance(globals()[name], pd.DataFrame)]
missing = [name for name in selected_dfs if name not in available]

print("‚úÖ Available:", available)
print("‚ùå Missing:", missing)

‚úÖ Available: ['air_pollution', 'available_by_state_year', 'children_lunch', 'children_poverty', 'dentists_raw_value', 'disconnected_youth', 'drinking_water', 'drive_alone', 'drug_overdose_deaths', 'exercise_access', 'firearm_fatalities', 'flu_vaccinations_raw_value', 'food_environment_index', 'food_insecurity', 'frequent_physical_distress', 'high_housing_cost', 'high_school_graduation', 'hiv_prevalence_raw_value', 'homeownership', 'homicides', 'housing_facilities', 'income_inequality', 'injury_deaths', 'insufficient_sleep_raw_value', 'juvenile_arrests', 'life_expectancy', 'limited_access_healthy_foods', 'long_commute', 'mammography_screening', 'math_scores', 'median_income', 'mental_health_providers_raw_val', 'motor_vehicle_crash_deaths', 'not_proficient_english', 'poor_or_fair_health', 'poor_physical_health', 'population_raw_value', 'primary_care_physicians', 'reading_scores', 'severe_housing', 'severe_housing_problems', 'some_college', 'suicides_raw_value', 'traffic_volume', 'unemployment', 'uninsured_raw_value', 'violent_crime']
‚ùå Missing: []

In [149]:
# List of selected DataFrames
selected_dfs = [
    "air_pollution", "available_by_state_year", "children_lunch", "children_poverty", "dentists_raw_value",
    "disconnected_youth", "drinking_water", "drive_alone", "drug_overdose_deaths", "exercise_access",
    "firearm_fatalities", "flu_vaccinations_raw_value", "food_environment_index", "food_insecurity",
    "frequent_physical_distress", "high_housing_cost", "high_school_graduation", "hiv_prevalence_raw_value",
    "homeownership", "homicides", "housing_facilities", "income_inequality", "injury_deaths",
    "insufficient_sleep_raw_value", "juvenile_arrests", "life_expectancy", "limited_access_healthy_foods",
    "long_commute", "mammography_screening", "math_scores", "median_income", "mental_health_providers_raw_val",
    "motor_vehicle_crash_deaths", "not_proficient_english", "poor_or_fair_health", "poor_physical_health",
    "population_raw_value", "primary_care_physicians", "reading_scores", "severe_housing",
    "severe_housing_problems", "some_college", "suicides_raw_value", "traffic_volume", "unemployment",
    "uninsured_raw_value", "violent_crime"
]

# Merge them
unified_df = None
for name in selected_dfs:
    df = globals()[name]
    if all(col in df.columns for col in ["FIPS", "State", "County"]):
        if unified_df is None:
            unified_df = df
        else:
            unified_df = pd.merge(unified_df, df, on=["FIPS", "State", "County"], how="outer")

print("‚úÖ Unified DataFrame created")

‚úÖ Unified DataFrame created

In [150]:
unified_df.columns = unified_df.columns.str.strip()
unified_df = unified_df.loc[:, ~unified_df.columns.duplicated()]

In [151]:
print(unified_df.shape)     # Rows √ó Columns
unified_df.head(3)          # First 3 rows

(5371, 278)

,FIPS,State,County,air_pollution_2020,air_pollution_2021,air_pollution_2022,air_pollution_2023,air_pollution_2024,air_pollution_mean,children_lunch_2020,...,uninsured_raw_value_2022,uninsured_raw_value_2023,uninsured_raw_value_2024,uninsured_mean,violent_crime_2020,violent_crime_2021,violent_crime_2022,violent_crime_2023,violent_crime_2024,violent_crime_mean
0,21021,KY,Boyle County,8.880902,8.880902,8.880902,8.880902,8.3,8.764721,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21023,KY,Bracken County,10.500000,8.500000,8.800000,8.300000,8.3,8.880000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21025,KY,Breathitt County,9.700000,9.000000,7.900000,7.700000,7.7,8.400000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [152]:
unified_df.isnull().sum().sort_values(ascending=False).head(10)

violent_crime_2024         5371
violent_crime_2023         5371
disconnected_youth_2024    4146
disconnected_youth_2023    4115
disconnected_youth_2022    4098
homicides_2020             4035
homicides_2021             4019
disconnected_youth_2021    4013
homicides_2023             3993
homicides_2022             3993
dtype: int64

In [153]:
unified_df.describe()

,air_pollution_2020,air_pollution_2021,air_pollution_2022,air_pollution_2023,air_pollution_2024,air_pollution_mean,children_lunch_2020,children_lunch_2021,children_lunch_2022,children_lunch_2023,...,uninsured_raw_value_2022,uninsured_raw_value_2023,uninsured_raw_value_2024,uninsured_mean,violent_crime_2020,violent_crime_2021,violent_crime_2022,violent_crime_2023,violent_crime_2024,violent_crime_mean
count,3198.000000,3198.000000,3198.000000,3198.000000,3198.000000,3198.000000,3080.000000,3080.000000,3176.000000,2612.000000,...,3197.000000,3197.000000,3197.000000,3197.000000,3197.000000,3197.000000,3197.000000,0.0,0.0,3197.000000
mean,8.994573,7.636341,8.010087,7.531178,7.531163,7.940668,0.538236,0.542070,0.542498,0.547508,...,0.119113,0.118123,0.114876,0.116253,253.385042,253.385042,253.385042,NaN,NaN,253.385042
std,1.964202,1.678671,1.647059,1.706489,1.706490,1.627649,0.185337,0.185019,0.186047,0.204143,...,0.051035,0.051871,0.052504,0.050582,188.085234,188.085234,188.085234,NaN,NaN,188.085234
min,3.000000,1.500000,2.500000,0.900000,0.900000,2.720000,0.000000,0.000000,0.012085,0.029595,...,0.023549,0.022783,0.023897,0.023337,0.000000,0.000000,0.000000,NaN,NaN,0.000000
25%,7.700000,6.400000,6.900000,6.500000,6.500000,6.940000,0.412364,0.419465,0.421725,0.410761,...,0.080126,0.079677,0.074624,0.077082,124.366651,124.366651,124.366651,NaN,NaN,124.366651
50%,9.300000,7.900000,8.100000,7.800000,7.800000,8.180000,0.523628,0.523208,0.523836,0.523113,...,0.109512,0.106461,0.103397,0.106722,210.928746,210.928746,210.928746,NaN,NaN,210.928746
75%,10.400000,8.800000,9.100000,8.800000,8.800000,9.180000,0.637716,0.641959,0.639804,0.653500,...,0.149696,0.148173,0.145488,0.145806,333.737864,333.737864,333.737864,NaN,NaN,333.737864
max,19.700000,16.000000,20.900000,15.600000,15.600000,16.100000,1.000000,1.000000,1.000000,1.000000,...,0.357532,0.414384,0.463235,0.339297,1819.514406,1819.514406,1819.514406,NaN,NaN,1819.514406

In [154]:
# Sort the DataFrame alphabetically by state
sorted_df = unified_df.sort_values("State")

In [155]:
cols_to_drop = [
    'pop_2020_x', 'pop_2021_x', 'pop_2022_x', 'pop_2023_x', 'pop_2024_x',
    'pop_2020_y', 'pop_2021_y', 'pop_2022_y', 'pop_2023_y', 'pop_2024_y',
    'pop_2020', 'pop_2021', 'pop_2022', 'pop_2023', 'pop_2024'
]

# Drop only if present
sorted_df = sorted_df.drop(columns=[col for col in cols_to_drop if col in sorted_df.columns])

In [156]:
# Find fully duplicated rows
duplicates = sorted_df[sorted_df.duplicated(keep=False)]

# Show the duplicated rows
print(duplicates)

# Optional: Count how many there are
print(f"Total fully duplicated rows: {duplicates.shape[0]}")

Empty DataFrame
Columns: [FIPS, State, County, air_pollution_2020, air_pollution_2021, air_pollution_2022, air_pollution_2023, air_pollution_2024, air_pollution_mean, children_lunch_2020, children_lunch_2021, children_lunch_2022, children_lunch_2023, children_lunch_2024, children_lunch_mean, children_poverty_2020, children_poverty_2021, children_poverty_2022, children_poverty_2023, children_poverty_2024, children_poverty_mean, dentists_raw_value_2020, dentists_raw_value_2021, dentists_raw_value_2022, dentists_raw_value_2023, dentists_raw_value_2024, dentists_mean, disconnected_youth_2020, disconnected_youth_2021, disconnected_youth_2022, disconnected_youth_2023, disconnected_youth_2024, disconnected_youth_mean, drinking_water_2020, drinking_water_2021, drinking_water_2022, drinking_water_2023, drinking_water_2024, drinking_water_mean, drive_alone_numerator_2020, drive_alone_numerator_2021, drive_alone_numerator_2022, drive_alone_numerator_2023, drive_alone_numerator_2024, drug_overdose_deaths_2020, drug_overdose_deaths_2021, drug_overdose_deaths_2022, drug_overdose_deaths_2023, drug_overdose_deaths_2024, drug_overdose_deaths_mean, exercise_access_2020, exercise_access_2021, exercise_access_2022, exercise_access_2023, exercise_access_2024, exercise_access_mean, firearm_fatalities_2020, firearm_fatalities_2021, firearm_fatalities_2022, firearm_fatalities_2023, firearm_fatalities_2024, firearm_fatalities_mean, flu_vaccinations_raw_value_2020, flu_vaccinations_raw_value_2021, flu_vaccinations_raw_value_2022, flu_vaccinations_raw_value_2023, flu_vaccinations_raw_value_2024, flu_vaccinations_mean, food_environment_index_2020, food_environment_index_2021, food_environment_index_2022, food_environment_index_2023, food_environment_index_2024, food_environment_index_mean, food_insecurity_2020, food_insecurity_2021, food_insecurity_2022, food_insecurity_2023, food_insecurity_2024, food_insecurity_mean, frequent_physical_distress_2020, frequent_physical_distress_2021, frequent_physical_distress_2022, frequent_physical_distress_2023, frequent_physical_distress_2024, physical_distress_mean, high_housing_cost_2020, high_housing_cost_2021, high_housing_cost_2022, high_housing_cost_2023, high_housing_cost_2024, high_housing_cost_mean, high_school_graduation_2020, high_school_graduation_2021, high_school_graduation_2022, high_school_graduation_2023, high_school_graduation_2024, high_school_graduation_mean, hiv_prevalence_2020, hiv_prevalence_2021, ...]
Index: []

[0 rows x 278 columns]
Total fully duplicated rows: 0

In [157]:
# Count of unique rows without modifying the DataFrame
num_unique_rows = sorted_df.drop_duplicates().shape[0]
print(f"Number of unique rows: {num_unique_rows}")

Number of unique rows: 5371

In [158]:
# Find duplicated rows based on FIPS, State, and County
duplicates_subset = sorted_df[
    sorted_df.duplicated(subset=['FIPS', 'State', 'County'], keep=False)
]

# Display duplicated rows
print(duplicates_subset[['FIPS', 'State', 'County']])

Empty DataFrame
Columns: [FIPS, State, County]
Index: []

In [159]:
# 1. Fully duplicated rows
full_dupes = sorted_df.duplicated(keep=False)
print(f"Fully duplicated rows: {full_dupes.sum()}")

# 2. Duplicated rows based on FIPS, State, County
key_dupes = sorted_df.duplicated(subset=['FIPS', 'State', 'County'], keep=False)
print(f"Duplicated FIPS+State+County rows: {key_dupes.sum()}")

# 3. Duplicated column names
dupe_columns = sorted_df.columns[sorted_df.columns.duplicated()]
print(f"Duplicated column names: {list(dupe_columns)}")

# 4. Duplicated values in specific columns (e.g., FIPS)
dupe_fips_values = sorted_df['FIPS'].duplicated(keep=False)
print(f"Rows with duplicated FIPS values: {dupe_fips_values.sum()}")

Fully duplicated rows: 0
Duplicated FIPS+State+County rows: 0
Duplicated column names: []
Rows with duplicated FIPS values: 4

In [160]:
# Find FIPS values that are duplicated
duplicated_fips_rows = sorted_df[sorted_df['FIPS'].duplicated(keep=False)]

# Show those rows
print(duplicated_fips_rows)

       FIPS State           County  air_pollution_2020  air_pollution_2021  \
3337  22059    LA  La Salle Parish                 NaN                 NaN
3338  22059    LA   LaSalle Parish                 NaN                 NaN
140   22059    LA  La Salle Parish            9.100000            8.500000
141   22059    LA   LaSalle Parish            8.953333            8.953333

      air_pollution_2022  air_pollution_2023  air_pollution_2024  \
3337                 NaN                 NaN                 NaN
3338                 NaN                 NaN                 NaN
140             9.100000            8.953333            8.953333
141             8.953333            8.400000            8.400000

      air_pollution_mean  children_lunch_2020  ...  uninsured_raw_value_2022  \
3337                 NaN             0.510189  ...                  0.115786
3338                 NaN             0.590555  ...                  0.102509
140             8.921333                  NaN  ...                       NaN
141             8.732000                  NaN  ...                       NaN

      uninsured_raw_value_2023  uninsured_raw_value_2024  uninsured_mean  \
3337                  0.097240                  0.093133        0.106877
3338                  0.116141                  0.096858        0.101051
140                        NaN                       NaN             NaN
141                        NaN                       NaN             NaN

      violent_crime_2020  violent_crime_2021  violent_crime_2022  \
3337          245.898878          245.898878          245.898878
3338          431.204624          431.204624          431.204624
140                  NaN                 NaN                 NaN
141                  NaN                 NaN                 NaN

      violent_crime_2023  violent_crime_2024  violent_crime_mean
3337                 NaN                 NaN          245.898878
3338                 NaN                 NaN          431.204624
140                  NaN                 NaN                 NaN
141                  NaN                 NaN                 NaN

[4 rows x 278 columns]

In [161]:
sorted_df

,FIPS,State,County,air_pollution_2020,air_pollution_2021,air_pollution_2022,air_pollution_2023,air_pollution_2024,air_pollution_mean,children_lunch_2020,...,uninsured_raw_value_2022,uninsured_raw_value_2023,uninsured_raw_value_2024,uninsured_mean,violent_crime_2020,violent_crime_2021,violent_crime_2022,violent_crime_2023,violent_crime_2024,violent_crime_mean
2250,02068,AK,Denali Borough,8.145,8.145,8.145,8.145,8.145,8.145,0.012461,...,0.115148,0.125355,0.135135,0.127261,404.499130,404.499130,404.499130,NaN,NaN,404.499130
2242,02000,AK,Alaska,8.145,6.450,6.150,7.550,7.550,7.169,0.445528,...,0.126761,0.129587,0.131843,0.134980,720.263271,720.263271,720.263271,NaN,NaN,720.263271
2243,02013,AK,Aleutians East Borough,8.145,8.145,8.145,8.145,8.145,8.145,0.039648,...,0.232895,0.207541,0.220598,0.239150,404.499130,404.499130,404.499130,NaN,NaN,404.499130
2244,02016,AK,Aleutians West Census Area,8.145,8.145,8.145,8.145,8.145,8.145,0.204499,...,0.176942,0.208119,0.202140,0.193174,294.617564,294.617564,294.617564,NaN,NaN,294.617564
2245,02020,AK,Anchorage Borough,8.145,6.400,5.400,8.300,8.300,7.309,0.465113,...,0.111427,0.108993,0.114652,0.116678,1006.657195,1006.657195,1006.657195,NaN,NaN,1006.657195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2152,56005,WY,Campbell County,5.800,4.100,4.900,2.400,2.400,3.920,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2151,56003,WY,Big Horn County,5.400,4.600,5.400,3.600,3.600,4.520,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2150,56001,WY,Albany County,3.700,3.900,5.000,3.700,3.700,4.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2160,56021,WY,Laramie County,4.600,5.500,4.800,3.800,3.800,4.500,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5370,fipscode,state,county,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [162]:
# Total rows in the combined dataset
print(f"Total rows in sorted_df: {sorted_df.shape[0]}")

# Unique FIPS values
print(f"Unique FIPS codes: {sorted_df['FIPS'].nunique()}")

Total rows in sorted_df: 5371
Unique FIPS codes: 5369

In [163]:
# Count rows where FIPS == 'fipscode' (i.e., accidental header rows)
print(sorted_df[sorted_df['FIPS'] == 'fipscode'])

# Count how many FIPS appear more than once
dupes = sorted_df['FIPS'][sorted_df['FIPS'].duplicated()]
print(dupes.value_counts())

          FIPS  State  County  air_pollution_2020  air_pollution_2021  \
5370  fipscode  state  county                 NaN                 NaN

      air_pollution_2022  air_pollution_2023  air_pollution_2024  \
5370                 NaN                 NaN                 NaN

      air_pollution_mean  children_lunch_2020  ...  uninsured_raw_value_2022  \
5370                 NaN                  NaN  ...                       NaN

      uninsured_raw_value_2023  uninsured_raw_value_2024  uninsured_mean  \
5370                       NaN                       NaN             NaN

      violent_crime_2020  violent_crime_2021  violent_crime_2022  \
5370                 NaN                 NaN                 NaN

      violent_crime_2023  violent_crime_2024  violent_crime_mean
5370                 NaN                 NaN                 NaN

[1 rows x 278 columns]
FIPS
22059    1
22059    1
Name: count, dtype: int64

In [164]:
dupes = sorted_df[sorted_df['FIPS'].duplicated(keep=False)]
print(dupes[['FIPS', 'State', 'County']])

       FIPS State           County
3337  22059    LA  La Salle Parish
3338  22059    LA   LaSalle Parish
140   22059    LA  La Salle Parish
141   22059    LA   LaSalle Parish